### ISSUE TITLE
Add browserify-friendly field to package.json

### ISSUE THREAD

**Issue by dgerber** [dc-js/dc.js#1005]
Adding a field `browser: "dc.js"` to package.json will [tell browserify](https://github.com/substack/browserify-handbook#browser-field) not to try including jsdom in the bundle, nor tamper with globals. It's done this way in d3.js and works well.

**Comment by gordonwoodhull** [comment]
Thanks @dgerber, I rely on help from the community on the browserify support, since I don't use it myself (yet!)
