### ISSUE TITLE
css-rule .axis line is missing specifier .dc-chart

### ISSUE THREAD

**Issue by arjanvanderleden** [dc-js/dc.js#1007]
In dc.css (line 68) there is a double rule  for .axis path and .axis line within a .dc-chart
the rule for .axis line is missing the parent specifier .dc-chart 

https://github.com/dc-js/dc.js/blob/develop/dc.css#L68

That can (and does) conflict with other parties css rules

**Comment by gordonwoodhull** [comment]
Thanks @arjanvanderleden, the precedence of the css selector `,` operator is a frequent stumbling block.

It looks like this one is also wrong, although less harmful:
https://github.com/dc-js/dc.js/blob/develop/dc.css#L256

Putting a line break after the `,` would make the precedence clearer, as done here:
https://github.com/dc-js/dc.js/blob/develop/dc.css#L275-L276

**Comment by gordonwoodhull** [comment]
fixed by #1011
