### ISSUE TITLE
Rowchart has Infinite height  when _rowData.length is 0

### ISSUE THREAD

**Issue by nordfjord** [dc-js/dc.js#1008]
See: https://github.com/dc-js/dc.js/blob/6e95388b9ae37d12eaf2009a4c8f28d48f71a698/src/row-chart.js#L169

when you filter such that a rowchart has no rows, its height becomes Infinity, which translates to a lot of errors along the lines of:

`Error: Invalid value for <g> attribute transform="translate(NaN,0)"`

**Comment by gordonwoodhull** [comment]
Seems like a legitimate bug, reopening (?)

**Comment by nordfjord** [comment]
It might be a legitimate bug.

But the errors I was receiving had nothing to do with this, I was way off base.

They were caused by a preRedraw function I had which calculated the xAxis domain and didn't check for infinity/NaN. I haven't seen any errors crop up around the height being Infinity, so I think it should be safe to close.

Regards,

Einar

**Comment by alisabzevari** [comment]
I think this is related to a calculation in `updateElements` function (https://github.com/dc-js/dc.js/blob/develop/src/row-chart.js#L173). This error happened to me:
`Invalid negative value for <rect> attribute height="-1.3095238095238095"`
It happened when I had too many rows and the chart has a small height. So the calculation made the height of every row to become negative.

**Comment by gordonwoodhull** [comment]
I looked and looked, but couldn't find any way to detect invalid DOM attributes being set in tests? Seems really weird that this can't be tested (via Jasmine). However, I did add a test and verified that it was creating errors before the fix (described in #1024) but not after.

**Comment by gordonwoodhull** [comment]
@alisabzevari, that's actually a different error - the opposite error. This one has to do with having no rows, not lots of rows. 

If you'd care to file a separate issue, I'd appreciate it. Even better with a test case (fiddle or jasmine).

**Comment by gordonwoodhull** [comment]
Fixed in 2.0 beta 32
