### ISSUE TITLE
dc.dataTable has two properties ".order" in the latest api

### ISSUE THREAD

**Issue by Lozzi** [dc-js/dc.js#1009]
First ".order" is the actual order function for the dataTable. The second one appears to be ".showGroups". The problem I ran into was that the chart had no function called "showGroups()".

Link to the API: https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#dc.dataTable+order

Best regards, Lozzi

**Comment by gordonwoodhull** [comment]
Thanks @Lozzi!
