### ISSUE TITLE
Undocumented .yAxisLabel() and .xAxisLabel() functions

### ISSUE THREAD

**Issue by tayden** [dc-js/dc.js#1010]
These two chart getter/setter methods are not mentioned anywhere in the API and probably should be.

**Comment by gordonwoodhull** [comment]
They seem to be...

https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#dc.coordinateGridMixin+xAxisLabel
https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#dc.coordinateGridMixin+yAxisLabel

**Comment by tayden** [comment]
Ah, I didn't look in the latest API. The stable API doesn't have any reference to these functions.

**Comment by gordonwoodhull** [comment]
Aha, thanks @tayden. Yes, we mostly don't maintain the 1.7.* branch - the 2.0 beta is very stable, just needs a few more fixes to a real release.
