### ISSUE TITLE
cannot apply filters to barChart externally

### ISSUE THREAD

**Issue by jenicar** [dc-js/dc.js#1020]
On the dc.js example page the code below moves the filters but doesn't update any of the other charts. 

fluctuationChart.filter([8, 9]);
dc.redrawAll(); 

This works perfectly for the other charts e.g. the below works perfectly.

quarterChart.filter("Q4");
dc.redrawAll();

**Comment by gordonwoodhull** [comment]
Not an issue, just a strange API.

http://stackoverflow.com/questions/28939020/initial-range-selection-in-dc-js-chart

**Comment by jenicar** [comment]
Thanks! I can get this to work on the example page but when I try it in my application I get the error 
Cannot read property 'RangedFilter' of undefined

When I inspect in the API in the console it looks like dc.filters doesn't exist? 
I'm on version 1.7.4

any ideas?

**Comment by gordonwoodhull** [comment]
Ah there you probably want your original construction, but precede it with `filter(null)`:

From the way it's invoked internally:
```{js}
                _chart.filter(null);
                _chart.filter([extent[0], extent[1]]);
```
https://github.com/dc-js/dc.js/blob/1.7/src/coordinate-grid-chart.js#L696

**Comment by jenicar** [comment]
That fixed it! Thanks so much.
Code below works exactly as expected

fluctuationChart.filterAll();
fluctuationChart.filter([8, 9]);
dc.redrawAll();
