### ISSUE TITLE
dataTable not working with fancy columns

### ISSUE THREAD

**Issue by stevemandl** [dc-js/dc.js#1030]
When passing an array of objects to dataTable.columns() as suggested in the docs, _doColumnValueFormat throws an error that v.format is not a function. Instead of using this template for the columns:

```
chart.columns([
    ["Date",   // Specify an Object = [Label, Fn]
        function (d) { return d.date; }], ...
```

This one works instead:
```
.columns([
     {label: "Period", format:
      function (d) { return d.p; }}, ...
```

Either the docs should be changed (using a similar template to the one I pasted above), or the code should be changed:

```
    _chart._doColumnValueFormat = function (v, d) {
        return ((typeof v === 'function') ?
                v(d) :                          // v as function
                ((typeof v === 'string') ?
                 d[v] :                         // v is field name string
//                 v.format(d)                        // v is Object, use fn (element 2)
//use element 2 instead:
                 v.[1](d)                        // v is Object, use fn (element 2)
                )
               );
    };
```

to call  so they match. If the code is changed, `_doColumnHeaderFormat` is also impacted by a similar issue.

**Comment by gordonwoodhull** [comment]
I see. [I requested the API change](https://github.com/dc-js/dc.js/pull/560#issuecomment-40826887) but didn't verify that the docs had been changed accordingly. So this is a documentation bug

Thanks @stevemandl for the report!
