### ISSUE TITLE
How to completely dispose a chart

### ISSUE THREAD

**Issue by alisabzevari** [dc-js/dc.js#1035]
I have created a dashboard with dcjs. In my dashboard, there is a check box which lets user to toggle dashboard behavior between count and amount. To do this I have recreated the crossfilter with a different reduceSum for all of my groups. (Althought, I do not know if this is the proper way to do this or not.) After recreating crossfilter I have to recreate dcjs charts as well. I think this could lead to some memory leaks and performance issues because I have defined filtered event for all of my charts and don't know how to turn off that event. Also after checking and unchecking the checkbox page slows down.

My question: Is there other ways to completely change crossfilter data without recreating dcjs chart? If not, how to properly remove dcjs charts to avoid memory leaks and performance problems?

**Comment by gordonwoodhull** [comment]
Sorry, I haven't had a chance to answer the question on SO yet.

http://stackoverflow.com/questions/33460320/dcjs-crossfilter-how-to-completely-dispose-a-chart

That's the right place for support questions. (This issue tracker is only for feature requests and bug reports.)
