### ISSUE TITLE
Vertical grid lines on a bar chart are black (not light gray)

### ISSUE THREAD

**Issue by mikemsq** [dc-js/dc.js#1046]
Vertical grid lines on a bar chart are black (not light gray) - see the image.
Probable cause - style override ???
![dc 2 0 0-beta 21](https://cloud.githubusercontent.com/assets/3779501/11401592/412dc3f6-9361-11e5-8641-3fd9f8be2494.PNG)

**Comment by gordonwoodhull** [comment]
Good eye. I think we can just replace the selector instead of having both, since the new one is strictly more specific. Right?

**Comment by mikemsq** [comment]
That would do.
I wasn't sure if the other one is used anywhere else.
I'll update the fix.

Thanks,
Mike

**Comment by gordonwoodhull** [comment]
You were right the first time. Thanks, merging in beta 24!
