### ISSUE TITLE
Execute group asynchronously 

### ISSUE THREAD

**Issue by yosiat** [dc-js/dc.js#1050]
Hi,

I am currently working on a project (in a node environment, specifically electron) where I need to load dataset which is larger than the maximum js heap.
For doing so, I am creating a library that mimics the crossfilter API and execute the group and filters in sqlite store.

As a result the developer is calling filter(..)/filterFunction(..) etc and when he is calling "group()" or "groupAll()" a sql query executed (matching the filters criteria),
the result is asynchronous (I thought about waiting sync for the sql query to finish but then I will block the UI for 200ms ~).

Currently my approach for doing this, is something like this:

```js
function promiseGroup(promise) {
  return {
    all: function() {
        if(promise resolved)  {
                 return promise values;
        }


       return old results;
    }
  }
}


group: function() {
   /*
      I have some code for making the filters is new one,
      If I won't do this my code will result in infinite loop (dc.redrawAll -> calls group -> execute -> dc.redrawAll)
   */
   var sqlPromise = /* code that execute the promise */;
   sqlPromise.then(function() {
      // when the promise is returned we want to call dc.redraw 
     dc.redrawAll();
   });
   return promiseGroup(sqlPromise);

}
```

Do you have any other way for doing this? Maybe adding support to crossfilter for async groups? and supporting this for dc (I will be more than happy to sumit PR)?

(Posted as well in crossfilter repo - https://github.com/square/crossfilter/issues/166)

**Comment by yosiat** [comment]
Just found out about - commitHandler (https://github.com/dc-js/dc.js/blob/58766e518a6e171c18a057e2886ff4d7b7fe4fdf/web/docs/api-latest.md#dc.baseMixin+commitHandler)

look it will solve my problem :+1:

**Comment by gordonwoodhull** [comment]
Yes, I just added this API a few weeks ago, for exactly that purpose.

The only limitation with this approach is that it is on the chart rather than the chart group, so you have to apply the commitHandler to every chart and you have to call `chart.redrawGroup` and `chart.renderGroup` where you ordinarily would call `dc.redrawAll` or `dc.renderAll`. This is a little ugly.

So I'm thinking about also adding something at the (currently undocumented) chart registry level, to prevent the confusion of having to do the same thing in different ways.

**Comment by gordonwoodhull** [comment]
Please let us know if you open source your library, @yosiat! People are always looking for solutions for when the data gets too large for crossfilter.

**Comment by yosiat** [comment]
Hi @gordonwoodhull ,
Used this api and it's awesome :+1: , If the commitHandler will be on the registry it will be great, currently my commitHandler is duplicated across all charts.

I have an open source library - https://github.com/yosiat/crossfilter-sqlite, published it today.

**Comment by gordonwoodhull** [comment]
Great, glad it works! 

I am going to add a Crossfilter Alternatives section to the wiki soon, and will be sure to link to Crossfilter-SQLite. (Note: you should add a LICENSE. :)

I'll comment back when I've added the new API.
