### ISSUE TITLE
Sunburst

### ISSUE THREAD

**Issue by csymill26** [dc-js/dc.js#1069]
The sunburst is an awesome graph. Is there a way to make it zoomable? I have not been able to make it do so. Also, .innerRadius does not seem to work for me either. No matter the value I give it, the inner ring is the same size. I saw someone else mentioned having this problem. Is there a fix? Another thing, is it possible to add spaces between the levels? Thanks!

I commented in a previous issue (https://github.com/dc-js/dc.js/issues/781), but after no replies for 2 days, I figured I'd create a new one.

**Comment by gordonwoodhull** [comment]
Hi @csymill26, the sunburst hasn't yet been included in dc.js - I guess you are using the code in the PR #907? I'm going to move this comment there and close this. We will have to verify these things before we merge. 

Thanks for the report!

**Comment by gordonwoodhull** [comment]
This did not get implemented before the feature was merged. 

Probably not too hard, but I think right now there are no in-out transitions, only resizing of slices within their rings.

Reopening

**Comment by gordonwoodhull** [comment]
Right, or here's the canonical one from Mike: https://beta.observablehq.com/@mbostock/d3-zoomable-sunburst

I clarified the title & text a little bit - looks like `innerRadius` does work, but we don't have zooming or a way to control the spacing between rings (or the width of the rings).
