### ISSUE TITLE
Document that numberDisplay is better than dataCount

### ISSUE THREAD

**Issue by ubershmekel** [dc-js/dc.js#1076]
I want to show what's the percentage of the filtered items. I'm not sure how to do that with `dc.dataCount`.

I could have easily implemented it if `.html` took a function that allowed me to do anything instead of the string manipulation in the current API. https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#datacounthtml--object--datacount

        .html({
            some: '<strong>%filter-count</strong> selected out of <strong>%total-count</strong> records' +
                ' | <a href=\'javascript:dc.filterAll(); dc.renderAll();\'\'>Reset All</a>',
            all: 'All <strong>%total-count</strong> records shown. Click on the graphs to apply filters.'
        })

Would you be interested in such a pull request?

**Comment by gordonwoodhull** [comment]
I think you probably want to use the numberDisplay, which is more general.

**Comment by ubershmekel** [comment]
Yes. That worked. Thank you. Perhaps I can mention in the docs of dataCount and numberDisplay that they are related.

For future searchers this was my solution:

    var createRowCounter = function() {
        var humanize = function(x) {
            // http://stackoverflow.com/questions/661562/how-to-format-a-float-in-javascript/29249277#29249277
            return x.toPrecision(2).replace(/\.?0*$/,'');
        }
    
        var rowCounterId = 'rowCounter'
        addDiv(rowCounterId);
        var rowCounter = dc.numberDisplay ('#' + rowCounterId);
        rowCounter
            .dimension(ndx)
            .group(ndx.groupAll())
            .formatNumber(function() {
                var selectedCount = rowCounter.group().value();
                var total = rowCounter.dimension().size();
                if(selectedCount == total) {
                    return 'All <strong>' + total + '</strong> records shown. Click on the graphs to apply filters.'
                }
                var resetButton = '<a href="javascript:dc.filterAll(); dc.renderAll();">Reset All</a>';
                var percent = humanize(100 * selectedCount / total);
                return 'Selected ' + percent + '% (' + selectedCount + ' out of ' + total + ' records) | ' + resetButton;
        });
    }

**Comment by gordonwoodhull** [comment]
Good idea. Thanks for the report!
