### ISSUE TITLE
html docs: relative links are gone

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1098]
JSDoc / docstrap is stripping out any links which point within the documentation. These were previously handled by relative hash-links (e.g. `{@link #dc.coordinateGridMixin+brushOn}`) which obviously won't work. 

Probably JSDoc has a way to specify links semantically within a body of documentation.

Follow up to #1086

**Comment by gordonwoodhull** [comment]
As far as I can tell this is the only real blocker for "going live" with the HTML docs. (They're already online but not linked to anywhere.)

Internal links are pretty important; it looks like we have 64 of them:

```
$ grep 'link #' src/* | wc
      64     665    6281
```

Examples of missing links:

"brush" in http://dc-js.github.io/dc.js/docs/html/dc.lineChart.html#xyTipsOn__anchor
"itemWidth" in http://dc-js.github.io/dc.js/docs/html/dc.legend.html#autoItemWidth__anchor

**Comment by mtraynham** [comment]
Figured it out, our links should take the format:

`{@link dc.redrawAll dc.redrawAll}`
`{@link dc.baseMixin#redraw redraw}`

Took me a while to find the class format.  Will add a PR shortly.

**Comment by gordonwoodhull** [comment]
Sweet!

**Comment by gordonwoodhull** [comment]
fixed by #1109
