### ISSUE TITLE
stack-mixin: setting custom stack layout algorithm not working

### ISSUE THREAD

**Issue by jetsnguns** [dc-js/dc.js#1102]
The chart.stackLayout method is not working correctly when you try to change the layout algorithm. Unlike its default initialization on line 28 of stack-mixin.js:
```javascript
    var _stackLayout = d3.layout.stack()
        .values(prepareValues);
```
the method code on line 263 lacks binding values:
```javascript
    _stackLayout = stack;
```
Changing it to
```javascript
     _stackLayout = stack.values(prepareValues);
```
fixes the issue (tested with d3.layout.stack().offset("expand")).

**Comment by gordonwoodhull** [comment]
Documentation link for `d3.layout.stack.values`: 
https://github.com/mbostock/d3/wiki/Stack-Layout#values

**Comment by gordonwoodhull** [comment]
Cool! Does this mean that we have [normalized stacked bar charts](http://bl.ocks.org/mbostock/3886394)?

I agree - although this feature goes back to the very early days of dc.js, it doesn't look like it could ever have worked without specifying `.values()`.

I'm not sure if it's a good idea, but in case anyone is intentionally setting `.values()` differently, we could check if it is already set and only set it if not:

```js
     _stackLayout = stack;
     if(_stackLayout.values() === d3.layout.stack().values()) {
          _stackLayout.values(prepareValues);
```

Kinda ugly though. The default is `d3_identity` but that's not exposed.

**Comment by gordonwoodhull** [comment]
I'm fixing this in 2.0 beta 28 - unfortunately I don't have time to implement tests for a different stack layout and `stackLayout` remains untested. 😦
