### ISSUE TITLE
html docs: "new" shown on pseudo-classes

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1106]
@mtraynham pointed out in #1101:

> Minor caveat on #1097 (the classes). Both jsdoc2md and grunt-jsdoc (with docstrap) add the "new" keyword to these classes. Most of the documentation doesn't use it, but dc.js will work with/without the keyword...

For example, the HTML docs show `new compositeChart(parent, chartGroup)`, which works but is not idiomatic for dc.js. (For that matter, one would have to specify `dc.compositeChart`)

It probably means an extra object is created only to be thrown away.

**Comment by mtraynham** [comment]
https://github.com/jsdoc3/jsdoc/blob/master/templates/default/tmpl/method.tmpl#L10
https://github.com/docstrap/docstrap/blob/master/template/tmpl/method.tmpl#L7

Looks pretty static.  Maybe we could just provide our own `method.tmpl` based on the docstrap one..

**Comment by gordonwoodhull** [comment]
Meh.
