### ISSUE TITLE
dataTable fail to order ascending

### ISSUE THREAD

**Issue by fokomas** [dc-js/dc.js#1115]
hi
I just try to follow this to create my data table. 
/examples/table-on-aggregated-data.html

but if i change to `.order(d3.ascending)` there is a js error

```
data-table.js:166 Uncaught TypeError: _chart.dimension(...).bottom is not a function
```

is that a known issue ?
thanks

**Comment by gordonwoodhull** [comment]
Right, that example is demonstrating that you can pass a group for the dimension property of the `dataTable`, and you've found an interesting case where that does not work.

If you don't need the aggregation and can pass a dimension, I'd recommend doing that. 

Or if you can reverse the order of the group using [group.order](https://github.com/square/crossfilter/wiki/API-Reference#group_order) that would also be a good option.

If both of those fail, we land in the realm of super hacky workarounds, so familiar to dc.js fans! Is it a fake group? Yes! It's a fake group!

You can wrap your group like so:

```js 
function reversible_group(group) {
    return {
        top: function(N) {
            return group.top(N);
        },
        bottom: function(N) {
            return group.top(Infinity).slice(-N).reverse();
        }
    };
}
```

(Probably belongs in the FAQ, feel like I wrote this somewhere before.)

Please confirm this works and we can mark this as a documentation issue, to be added to the example and FAQ.

**Comment by fernandrez** [comment]
I used the d3.ascending function definition as an argument and it worked.

**Comment by gordonwoodhull** [comment]
@fernandrez is correct that you can also fool the dataTable into using the ascending function with `group.top()` by writing out the d3.ascending function yourself. 

This will work fine as long as the actual length of your data is less than [`dataTable.size()`](https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#dc.dataTable+size) but if there are more items than the size you can end up displaying in ascending order but dropping the lowest values, which is usually undesirable.

**Comment by privateOmega** [comment]
@gordonwoodhull I don't remember seeing this anywhere in the docs except when you mentioned this issue in gitter, It would be nice it to be added in docs so a newbie won't be stuck.

**Comment by gordonwoodhull** [comment]
Thanks @privateOmega, good idea. The note on `dataTable` says that you can use a group but have to use `d3.ascending`.

I think I'll create a "fake dimension" section in the FAQ, and link to it from the docs. Then this issue can be closed, since it's really the best solution given the current architecture.

**Comment by gordonwoodhull** [comment]
Added to the example and documentation.
