### ISSUE TITLE
Docs on how to build custom charts

### ISSUE THREAD

**Issue by lmatteis** [dc-js/dc.js#1122]
I have some experience with d3.js and I'd like to be able to create charts that are compatible dc.js charts. However, even after somewhat reading the code, I find it hard understanding how new charts can be implemented. Any help?

**Comment by gordonwoodhull** [comment]
Right now I think the best resource is this Q&A and comments on SO:
http://stackoverflow.com/questions/25336528/dc-js-listening-for-chart-group-render

(I mentioned the [chart registry docs](https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#dcchartregistry--object) already on irc.)

It would be great to document this somewhere, if only in the wiki.

**Comment by lmatteis** [comment]
Thanks! I'm trying to build a "sticky" bubble chart for DC.js http://bl.ocks.org/mbostock/4063269

I didn't know there was an irc, or you mean gitter? I'll be trying it out and share a blocks once I get it working so it can hopefully also serve as a base for others willing to implement other charts.

**Comment by gordonwoodhull** [comment]
Yeah I just meant gitter. 

That sounds great, I don't think we have a minimal example. The numberDisplay is too weird to serve that purpose.
