### ISSUE TITLE
Bubble chart labels

### ISSUE THREAD

**Issue by mukherjeea** [dc-js/dc.js#1125]
I've noticed a unusual behaviour with labels of the bubbles in the bubble chart. When I set elasticX(false), elasticY(false) and elasticRadius(true) the labels only show up for the bubbles where they can fit inside the circle and the rest don't show. I've tried different combination of elasticX/Y/Radius passing true/false values and the behaviour is erratic. What is the cause of this and how can I make the labels show up even when it doesn't fit inside the circle?

Thanks
A

**Comment by gordonwoodhull** [comment]
Please lmk if you are having trouble with the documentation.

https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#dc.bubbleMixin+minRadiusWithLabel

**Comment by mukherjeea** [comment]
Thanks Gordon!

I completely missed it in the documentation.
