### ISSUE TITLE
dc.line Chart filter programmatically

### ISSUE THREAD

**Issue by sourabh1985** [dc-js/dc.js#1132]
dc.line Chart filter pro-grammatically.

something like auto filter  on click of button.

**Comment by gordonwoodhull** [comment]
http://stackoverflow.com/questions/28939020/initial-range-selection-in-dc-js-chart

**Comment by sourabh1985** [comment]
Thats working fine I want brushing (auto play).
means on click of any button brush should move from starting to end using dc js

some thing like this.
http://bl.ocks.org/mbostock/4349545
