### ISSUE TITLE
First bar is cut off, when using centerBar(true) with an ordinal x-axis

### ISSUE THREAD

**Issue by echen** [dc-js/dc.js#114]
I have a bar chart that looks like:

```
dc.barChart("#chart")
   .x(d3.scale.ordinal().domain(["core", "casual", "new"]))
   .xUnits(dc.units.ordinal)
   .centerBar(true)
```

![dc-bar-chart-cutoff](https://f.cloud.github.com/assets/102375/73817/3f1568b4-6063-11e2-9cc3-c4a17bc9bfcb.png)

You can see that the first bar is cut in half.

But if I remove `centerBar(true)`, the first bar is fine:

![dc-bar-chart-fine](https://f.cloud.github.com/assets/102375/73822/5db32716-6063-11e2-9ab9-f1b24b3139bc.png)

**Comment by visby** [comment]
Adding a blank label at the beginning doesn't work well with a linear scale.
I can add an empty fact that will appear at the beginning, but that would be mess up my data and the crossfilter...

**Comment by gordonwoodhull** [comment]
@visby, for a linear scale you ought to be able to just adjust the domain of the scale, the min value. Of course this does mean forgoing `elasticX`. This issue is about ordinal scales, where it's less obvious how to change the domain.

I agree it would be great not to need these workarounds.

**Comment by madebydna** [comment]
I've also run into the issue of displaying the first / last bar for bar charts with linear scales and even prepared a fiddle to submit a bug report when I realized that it's not really a bug, but rather a somewhat confusing interaction between three bar chart attributes: the user set x domain of the linear scale, `elasticX` and `xAxisPadding`.

1. When using `elasticX` you can set an `xAxisPadding` value to make room for first / last bar. However, any user-set `.x()` domain will be ignored and reset to the min / max according to the data (while taking into account the `xAxisPadding`). Note that `elasticX` needs to be turned off for zoom / focus to work.

2. Without `elasticX` (e.g. when zoom functionality is needed) you can adjust the x domain of the linear scale. `xAxisPadding` setting will be ignored, however.

Here is the fiddle for reference: [http://jsfiddle.net/madebydna/e4d1mr4a/1/](http://jsfiddle.net/madebydna/e4d1mr4a/1/)
