### ISSUE TITLE
Getting a custom geochoropleth to Zoom/Pan

### ISSUE THREAD

**Issue by WFullen** [dc-js/dc.js#1140]
Hello,

I am trying to get my world map (with states included) to smoothly zoom in and out as well as pan around; I noticed from reading around that this is possible, but I would greatly appreciate some pointers. Here is my code:

```
d3.json("new.geo.json", function (statesJson) {
			
		
                        var height = 1850;
			var width = 1700;
			
				var projection = d3.geo.mercator()
					.center([0,40])
					.scale(300)
					.rotate([-12,0]);
				var path = d3.geo.path().projection(projection);

				
				userChart.width(width)
						.height(height)
						.dimension(states)
						.group(stateRaisedSum)
						.colors(d3.scale.quantize().range(["#E2F2FF", "#C4E4FF", "#9ED2FF", "#81C5FF", "#6BBAFF", "#51AEFF", "#36A2FF", "#1E96FF", "#0089FF", "#0061B5"]))
						.colorDomain([0, 40])
						.colorCalculator(function (d) { return d ? userChart.colors()(d) : '#000000'; })
						.overlayGeoJson(statesJson.features, "state", function (d) {
							return d.properties.name;
						})
						.projection(projection);

				dc.renderAll();
			
			});
```

Thank you for the help!

**Comment by XaserAcheron** [comment]
Do you suspect there's an issue with dc.js, or is this a general help request? If the latter, it's better to post to the [official mailing list](https://groups.google.com/forum/?fromgroups#!forum/dc-js-user-group) -- GitHub Issues are for bug reports and feature requests.

**Comment by WFullen** [comment]
It says that I do not have permission to post to the group - any ideas?

Thanks!

**Comment by XaserAcheron** [comment]
You'll need to join the group first -- there'll be a button for that a bit below the "Ask question" button once you're logged in to Google.

Funny, I hadn't gotten around to doing this myself yet. Fixed now. Thanks for the unintentional reminder. :)

**Comment by mtraynham** [comment]
May want to take a look at https://github.com/dc-js/dc.js/pull/719
I rebased it this morning against master, so it should be up to date.

Close this?

**Comment by gordonwoodhull** [comment]
I guess... As a support request @WFullen moved on to the other forum and hopefully got some help. As a feature request I guess it would still be open until we merge #719. Unclear.
