### ISSUE TITLE
AMD definition with crossfilter2

### ISSUE THREAD

**Issue by cforcloud** [dc-js/dc.js#1141]
**dc.js-2.0.0-beta.29**
The "define" call is still using "crossfilter" and not "crossfilter2".

Changing it to this works:
`define(["d3", "crossfilter2"], _dc);
`

[Line: 10730](https://github.com/dc-js/dc.js/blob/develop/dc.js#L10730)

**Comment by MarkHerhold** [comment]
I think this is incorrect.

The module itself is called `crossfilter2` in npm and if you were to use it in node, you would do `var crossfilter = require('crossfilter2')` but the AMD export is for "crossfilter". I'm not sure if this discrepancy should be addressed on crossfilter's side of things or not though... I think it's better for backwards compatibility to keep the AMD definition as "crossfilter".

**Comment by gordonwoodhull** [comment]
I agree with @MarkHerhold - the file isn't named crossfilter2.js and at least requireJS uses the filename as the name of the module.

If this is causing problems with other module frameworks, please give more specifics and I'll reopen this. Thanks @cforcloud!
