### ISSUE TITLE
Use bower Crossfilter2 ~1.4

### ISSUE THREAD

**Issue by mtraynham** [dc-js/dc.js#1149]
Seems that Crossfilter2 1.3 line doesn't actually have a `bower.json` file, and therefore never specifies `main` in the json.  Most people on the [wiredep](https://github.com/taptapship/wiredep) bandwagon will be affected by this.

**Comment by gordonwoodhull** [comment]
Ugh. My impression is that 1.4 is still not stable and has some performance regressions. 

@esjewett, do you think it's ready? I'd be willing to add the bower to 1.3 if no.

**Comment by esjewett** [comment]
We can add a bower.json to the 1.3 branch. 1.4 alpha releases can be used via Bower, and it is being used in some places, but especially the new features are not well-tested and there are performance regressions we would like to address.

**Comment by esjewett** [comment]
So is the question how to make a bower dependency for one of the alpha releases? If so, that should be 'bower install crossfilter2#1.4.0-alpha.05 --save' IIRC.

**Comment by mtraynham** [comment]
I believe adding a 1.3.X release to Crossfilter2 with a `bower.json` would ultimately resolve the problem.  Fortunately, with Wiredep you can override the `main` field for a dependency and I've done so locally, but anyone using `dc.js` with a bundling mechanism that looks at bower `main` fields (like Wiredep) are potentially broken.

**Comment by esjewett** [comment]
Yeah, sorry, I didn't realize what wiredep did when I responded. Let's do that. I hope I can get to it over the weekend. or if you have time to make a pull request based on the latest 1.3 tag, feel free.

**Comment by mtraynham** [comment]
Will do, thanks @esjewett
