### ISSUE TITLE
Why not drawing dots when brushOn

### ISSUE THREAD

**Issue by tornord** [dc-js/dc.js#1152]
I'll like to remove the brushOn criteria in drawDots, line 5891 in dc.js. Why is the test there?

```
function drawDots (chartBody, layers) {
    if (!_chart.brushOn() && _chart.xyTipsOn()) {
```

**Comment by gordonwoodhull** [comment]
I think that is because the tooltip / title / popup function of the dots will interfere with the brush. 

Do you want the tips or just the dots?

**Comment by tornord** [comment]
I understand. I want the dots and skip tips when brushOn. 

Comment out brushOn check gives me that feature

function drawDots (chartBody, layers) {
    if (/*!_chart.brushOn() &&*/ _chart.xyTipsOn()) {

**Comment by gordonwoodhull** [comment]
Links to previous discussion.

The current functionality was implemented somewhat backward from how you might expect, for historical reasons, see #735. Previously the dots always appeared when the brush was off. 

#689 discussed this feature, of forcing the dots always on when `xyTipsOn` is set. @mtraynham mentions a workaround for composite charts.

I'm not sure, but I think that changing the flag to a three-way switch could be a backward-compatible solution. Default is 'auto', turn on or off depending on brush. False always disables the dots. True always enables them (and disables crosshairs and tips when the brush is on). This assumes that no one is setting the flag true currently. 

Alternately, even more paranoidly backward compatible, true is auto and 'always' enables them always.

**Comment by tornord** [comment]
Thanks for a very detailed answer. I'm using D3/DC/Crossfilter more and more and hope I also will contribute

**Comment by gordonwoodhull** [comment]
I see now. There is no issue with the tips interfering with the brush, because the events don't get through.

But I'm going to pull the @dalle fix from https://github.com/Kurappu/dc.js/tree/mks_patches for this, which implements the paranoid solution I described above, because `xyTipsOn()` defaults to true and I don't want to change the current behavior in 2.0.
