### ISSUE TITLE
Changelog says 2.1 is the latest but there's nothing under releases

### ISSUE THREAD

**Issue by nitinsurana** [dc-js/dc.js#1154]
https://github.com/dc-js/dc.js/blob/develop/Changelog.md points to 2.1 but there's no such release - https://github.com/dc-js/dc.js/releases

**Comment by gordonwoodhull** [comment]
2.1 is the develop branch. There have been no releases. If you want to reference it as a dependency from an npm package, use the following:

```js
    "dc": "dc-js/dc.js#develop"
```

Once 2.0 is officially released (soon), we'll start numbering 2.1.* releases as well.
