### ISSUE TITLE
Pie Chart No Legends

### ISSUE THREAD

**Issue by rohit-guitar** [dc-js/dc.js#1159]
Hello ,

I have been trying to render the legends in Pie Chart.
I am using this code in order to get the legends. 

".legend(dc.legend().x(100).y(10).itemHeight(13).gap(5));"

I couldn't make it work.

I am using dc.js 1.7.5 version.

**Comment by gordonwoodhull** [comment]
It does not look like the pie chart supported legends in 1.7.*; are you getting an error?

Please try using the 2.0 betas - 2.0 is very close to release. There will be some api changes you need to make but the interface is stable now.
