### ISSUE TITLE
Could someone reopen closed issue: Does seriesChart work well with rangeChart? #479

### ISSUE THREAD

**Issue by peterh2** [dc-js/dc.js#1170]
The issue is: Does seriesChart work well with rangeChart? #479 

I haven't gotten it to work.  I posted a jsfiddle exampe.  Can't see what I am doing wrong.  I also posted this to stackOverflow: [stackOverflow](http://stackoverflow.com/questions/37868612/dc-js-serieschart-doesnt-seem-to-work-with-the-rangechart) in case it is better to respond there.  Thanks.

**Comment by gordonwoodhull** [comment]
Thanks @peterh2, good call.
