### ISSUE TITLE
scatter plot zoom disabled after redraw

### ISSUE THREAD

**Issue by altcomGaillard** [dc-js/dc.js#1178]
I'm working on a scatter plot.
I set my chart as mouseZoomable(true).

That chart needs to refresh as soon as the data changes, so I update the CrossFilter object and I run a redraw and everything works fine apart from the mouse zoom which doesn't work. I don't know how to put it back on apart from running a dc.renderAll().
So now I run a dc.renderAll() instead, but it doesn't look as nice as with the dc.redrawAll().

**Comment by gordonwoodhull** [comment]
Hmm, I just tried this the simplest way I could, by adding `.mouseZoomable(true)` to both of the charts in this example:

http://dc-js.github.io/dc.js/examples/scatter-brushing.html

Aside from the kind of strange behavior that zooming resets the filter to the current x-range (appropriate for line graphs, maybe, but strange here), this seems to work and zooming continues after I filter each chart.

Are you able to create a fiddle or a bl.ock demonstrating the problem

**Comment by altcomGaillard** [comment]
Hi,
I've created a fiddle which shows both #1178 and #1179 bugs.
http://jsfiddle.net/altcom_gaillard/djchar8o/2/

When loading you can zoom in and out, but as soon as you press the button "Reset zoom", the zoom stops working. This is because of the redrawAll line 88. If you replace it by renderAll, it works fine.

**Comment by gordonwoodhull** [comment]
If you do it like this, it's okay:

```js
    $scope.chart.x().domain([$scope.minDepth, $scope.maxDepth]);
```
http://jsfiddle.net/gordonwoodhull/Lb9vmj29/5/

I think if you want to assign a new scale we'll have to have some way to tell dc.js that you've done that, because in d3.js v3, the zoom behavior is bound to the scale. (I think this changes in v4, but that's a pretty big update and may not happen very soon.)

**Comment by altcomGaillard** [comment]
Works great thanks!!
I didn't realize I was setting a new scale by doing so.

**Comment by gordonwoodhull** [comment]
I'm going to close this, but it's worth thinking about better ways to integrate the feature in the future. dc.js is kind of a leaky abstraction, on purpose.
