### ISSUE TITLE
"labelAccessor" Feature

### ISSUE THREAD

**Issue by XaserAcheron** [dc-js/dc.js#1180]
I've run into multiple scenarios where I've had to modify a crossfilter dataset to translate a numeric `id` column to some sort of `name` value, for display purposes. Thus far I've been using the naive approach of just changing the raw data before feeding it to crossfilter, but now I've run into a point where I need to retrieve a numeric key from a filtered chart to make second API call, which naturally no longer exists in the crossfilter set. Doh!

To remedy this, I tried to set up a dictionary lookup via `keyFormatter` to map the raw `id`s to `name`s, but changing `keyAccessor` also changes the value used for filtering. If a group has an `id` of 3 that is modified by `keyAccessor` to display "George" in a chart, filtering the chart on that group will attempt to match `id` to "George", which results in an empty set. Double-doh!

*Hence the request*: Could we have some sort of `labelAccessor` function which affects *only* the value used for display purposes? This would allow us to modify the value used for chart displays without actually mucking about with the crossfilter set or the keys.

An alternative name could be something like "keyFormatter", I suppose, since you could also do something like pass in a `d3.time.format` function if your key is a date. Same concept.

For the record, this is something I'd be interested in developing + PRing myself, though I wanted to collect some feedback on the idea before starting anything.

Comment away, folks.

**Comment by gordonwoodhull** [comment]
Hi @XaserAcheron, which labels are you talking about in particular? I absolutely agree there should be a formatter or an accessor between the data and the display in all cases.

For the axis ticks, there is [d3.axis.tickFormat](https://github.com/d3/d3-3.x-api-reference/blob/master/SVG-Axes.md#tickFormat). 

We also have the (maybe inconsistently named) [`.label() function](https://github.com/dc-js/dc.js/blob/develop/web/docs/api-latest.md#dc.baseMixin+label) which should be used in most other circumstances. It could be that the text you want to control overlooked this.

A more serious effort would be to grep through the source and determine which of the 49 occurrences of `keyAccessor` are used for text. (Quite a few of them are just the default `titleAccessor`, so those are already customizeable.)

**Comment by XaserAcheron** [comment]
Welp. The `.label()` function is exactly what I had in mind. I'd missed it while looking since I was stubbornly checking for the word "accessor". :P

This can probably be closed. I haven't done a comprehensive look-through to see if it covers absolutely everything, but a brief glance shows it covers pie, bar, and row charts, which at the very least is exactly what I was looking for.

**Comment by gordonwoodhull** [comment]
Great! 

Yes, the name is inconsistent for sure.

I actually somewhat prefer the short name, but it's sort of unclear. In dc.graph.js I went the other way and assume everything is an accessor because just about everything is.
