### ISSUE TITLE
elasticY works with comosite chart?

### ISSUE THREAD

**Issue by leo-combes** [dc-js/dc.js#1182]
Hi!
It seems that the elasticY() option does not work in composite chart.
It is a known bug or limitation dc?

Here is an fiddle that shows how the Y axis starts at zero. Should not start in +/-600?
http://jsfiddle.net/u57bfje8/31/

Regards.

**Comment by gordonwoodhull** [comment]
Hi @leo-combes, thanks for the report!

This is a duplicate of #667, which concludes that the behavior is really at the stack mixin level (affecting single charts as well as composite/series charts). I'll comment further there.

**Comment by leo-combes** [comment]
Thanks!
