### ISSUE TITLE
Remove gh-pages branch in favor of master/docs directory.

### ISSUE THREAD

**Issue by mtraynham** [dc-js/dc.js#1193]
https://github.com/blog/2228-simpler-github-pages-publishing

I think this would remove some of the weird Grunt bloat around maintaining the web directory on master and pushing it to the `gh-pages` branch.  The only caveat I can think of is if the build is bad, the docs might be bad.

**Comment by gordonwoodhull** [comment]
Cool! Yeah master /web should always be ready to publish. 

There will be link breakage from renaming web/ to docs/ but I think it's just the API documentation markdown and the source of the examples. Have to think that part through

**Comment by gordonwoodhull** [comment]
We looked at this but it makes the checkins huge and noisy. 

Probably makes more sense for projects where the web content is the more important part of the repo, or where the docs aren't as sprawling as ours are.
