### ISSUE TITLE
When using with webpack, crossfilter is undefined

### ISSUE THREAD

**Issue by cramatt** [dc-js/dc.js#1214]
Using the latest 2-beta.32 

When using with webpack the following check is true

```
if(typeof define === "function" && define.amd) {
  define(["d3", "crossfilter"], _dc);
}
```

But since you are using crossfilter2 this is undefined. 

Changing this line to `define(["d3", "crossfilter2"], _dc);` fixes things.

**Comment by gordonwoodhull** [comment]
Thanks @cramatt, I think there are differences between how different module systems treat module names. We've been trying to keep crossfilter2 as a drop-in replacement for crossfilter, so we didn't change the filename crossfilter.js. And this is okay for npm but I guess it doesn't work in webpack. 

#1213 addresses this too.

+ @esjewett

**Comment by cramatt** [comment]
Makes sense - I'm not really sure why webpack environment causes the first condition to evaluate to true - I guess webpack uses amd but this is not really clear. 

Short of changing the name it might be something that can be fixed with a webpack config, maybe something like [resolve](http://webpack.github.io/docs/configuration.html#resolve-alias)?

**Comment by gordonwoodhull** [comment]
I don't know much about webpack. I guess the way it imports modules looks sufficiently like AMD to follow that path. (RequireJS can also do bundling, so maybe it's doing something similar

Resolve does look promising. If you can figure out a small config file to contribute to dc.js, that would be awesome!

**Comment by nordfjord** [comment]
In my config it's a simple:

```js
{
  resolve: {
    alias: {
     'crossfilter': 'crossfilter2'
    }
  }
}
```

**Comment by Anima-t3d** [comment]
For anyone else using webpack and doesn't get the `resolve` fix working... just make sure that it's the only resolve in the config. My config is quite long and I forgot I declared a `resolve` at the bottom.. ended up overwriting my `resolve` fix from @nordfjord . Once I consolidated it, it worked like a charm! Thanks.

**Comment by gordonwoodhull** [comment]
It is too bad about the confusion of crossfilter names but unless someone suggests something dc.js can do about it, I consider this solved.

**Comment by gordonwoodhull** [comment]
As of dc.js 2.0.3 / 2.1.6, we'll break requireJS compatibility in favor of webpack compatibility. 

See #1304 if this creates problems for you.
