### ISSUE TITLE
.on("filtered") not called for row and pie charts

### ISSUE THREAD

**Issue by eamonnmag** [dc-js/dc.js#1219]
Is there another approach for these charts? For bar charts and composite charts things work fine.

**Comment by gordonwoodhull** [comment]
That's surprising to hear. Row and pie charts use the same filter method, which invokes the filtered handler here:

https://github.com/dc-js/dc.js/blob/develop/src/base-mixin.js#L1059

**Comment by eamonnmag** [comment]
Ah, never mind. It was another issue that was only happening on row charts. Solved, thanks!
