### ISSUE TITLE
Problems with dispose() and deregisterChart()

### ISSUE THREAD

**Issue by ruben-romar** [dc-js/dc.js#1220]
I just copied this from SO: http://stackoverflow.com/questions/39829773/dc-js-problems-with-dispose-and-deregisterchart.

I am creating an application where I can add and remove charts dynamically. Everything works fine but deleting a chart.

The problem I'm having is occurring when I have a line chart and a bar chart, one of them being a composite, and I delete one of them (dispose the dimension and de-register the chart). At this point the chart that I have not disposed of stops reacting to filters from other charts and stops reacting to its own events even thought the other charts get filtered by them. Also, as you can see in the fiddle, the line chart I removed from dc is still reacting to the other chart filters.

I found out that the problem is on the deregisterChart dc call but since my application can create and delete infinity charts I need a way of removing from dc the ones I don't need any more without breaking the ones left behind.

This is the fiddle I created with my problem: https://jsfiddle.net/nofknndf/9/

Regards, 

Ruben

**Comment by gordonwoodhull** [comment]
Sorry, I did see you question, but I've been short on time the past few weeks. 

I'll answer on SO, and probably close this because I don't think it's a bug in dc.js.

**Comment by gordonwoodhull** [comment]
SO link: http://stackoverflow.com/questions/39829773/dc-js-problems-with-dispose-and-deregisterchart
