### ISSUE TITLE
Color issue on dc.js bar chart when filtered into a narrow range

### ISSUE THREAD

**Issue by paigelowe** [dc-js/dc.js#1222]
I'm working on a dc.js bar chart with filterable values.The chart has three colors in it's color array, based on the barchart's value and whether they're above, below, or at average for the numerical range. If you filter it on the chart's y value to a narrow range, the bar becomes a single colored chart (specifically the third color in the color arrange).

The color changes correctly when the range is wider, but when it gets to be a narrow range, suddenly the bars all become the same color.

The chart:
```
 that.ownerChart
            .width(400)
            .height(400)
            .margins({top: 0, left: 10, right: 10, bottom: 20})
            .dimension(that.dims.dOwner)
            .group(that._remove_empty_bins(that.groups.gOwner, (d) => { return d.value.avg; }))
            .ordering(function (x) {
                return x.value.avg * -1;
            })
            .on('filtered', onFilter)
            .fixedBarHeight(30)
            .cap(cap).othersGrouper(false)
            .elasticX(true)
            .renderTitleLabel(false)
            .leftLabel(function(x) {
                return x.key;
            })
            .leftLabelWidth(160)
            //The problematic line might be here
            .colorScale(d3.scale.quantize().range(that.colors));

```

**Comment by gordonwoodhull** [comment]
Hi @paigelowe, it's not necessary to cross-post questions to SO and GitHub.

I think I've answered the question over there, please check it out:
http://stackoverflow.com/questions/40410469/color-issue-on-dc-js-bar-chart-when-filtered-into-a-narrow-range
