### ISSUE TITLE
dc.js in Electron App

### ISSUE THREAD

**Issue by DeviMJ** [dc-js/dc.js#1248]
Hi,

I am trying to use dc.js in a node environment (Electron). When i run node_modules\.bin\electron . i get to see the dc.js graphs. However, when i create the executable binary and try to run it, i get an error saying "Uncaught Error: Cannot find module 'dc'".

**Comment by jdylanstewart** [comment]
Can you post a copy of your electron run file and the entry point for your app?

On Jan 11, 2017, at 7:01 PM, DeviMJ <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

I am trying to use dc.js in a node environment (Electron). When i run node_modules.bin\electron . i get to see the dc.js graphs. However, when i create the executable binary and try to run it, i get an error saying "Uncaught Error: Cannot find module 'dc'".

**Comment by gordonwoodhull** [comment]
I don't know Electron, but this sounds like an AMD (UMD) issue - `dc` is not made global if a module system is found.

**Comment by DeviMJ** [comment]
![run](https://cloud.githubusercontent.com/assets/13823480/21875572/fdb6756c-d8b7-11e6-808c-e1284767f3bb.PNG)

![error](https://cloud.githubusercontent.com/assets/13823480/21875571/fd8658a0-d8b7-11e6-98a4-b015647ab5f2.PNG)

I'm not sure if these are what you asked for...

**Comment by gordonwoodhull** [comment]
Can you `require('dc')` somehow, instead of assuming it's already loaded? Again, I don't know what module system Electron uses, but I'm guessing dc gets loaded as a plain file in one configuration, and as a module in the other.

**Comment by eapyl** [comment]
DC.js works fine with Electron. I just checked it. 
You can review [stock.js](https://bitbucket.org/snippets/upyl/74AMj) and [template](https://bitbucket.org/snippets/upyl/q4AMo). I used the same approach to create Electron app as it is in [electron-api-demos](https://github.com/electron/electron-api-demos)

**Comment by gordonwoodhull** [comment]
Thanks @eapyl. I'm going to close this as a configuration issue. @DeviMJ, if you're still having trouble, please comment and I'll open this back up.
