### ISSUE TITLE
Add Mindmap to core dc.js library 

### ISSUE THREAD

**Issue by robertjliguori** [dc-js/dc.js#1255]
Add Mindmap to core dc.js library 
http://dc-js.github.io/dc.js/docs/html/

Reference: 
http://www.primefaces.org/showcase/ui/data/mindmap.xhtml

**Comment by gordonwoodhull** [comment]
dc.js integrates with [dc.graph.js](https://github.com/dc-js/dc.js/issues/1255), which provides automatic layout of network visualizations.
