### ISSUE TITLE
Add Range Slider to core dc.js library

### ISSUE THREAD

**Issue by robertjliguori** [dc-js/dc.js#1258]
Add Range Slider to core dc.js library
http://dc-js.github.io/dc.js/docs/html/

References: 
https://plot.ly/javascript/range-slider/
https://github.com/shutterstock/rickshaw/blob/master/src/js/Rickshaw.Graph.RangeSlider.js

**Comment by gordonwoodhull** [comment]
The plotly example wasn't too clear to me but I think dc.js has this in the form of the [range chart](http://dc-js.github.io/dc.js/docs/html/dc.coordinateGridMixin.html#rangeChart) feature, which connects the brush of one chart to the domain and zoom of another chart.

You can see this in action on [the main page](http://dc-js.github.io/dc.js/), the last pair of charts before the data table.
