### ISSUE TITLE
Issue with crossfilter dependency

### ISSUE THREAD

**Issue by eapyl** [dc-js/dc.js#1261]
Hi there, I have a small problem with running dc example (stock.js). I added the next dependencies to my package.json:
```
  "dependencies": {
    "colorbrewer": "^1.0.0",
    "dc": "^2.1.1",
```
After that I got the next error: Uncaught Error: Cannot find module 'crossfilter'. 
To fix this issue I changed node_modules/dc/index.js:
```
d3 = require("d3");
crossfilter = require("crossfilter2");
module.exports = require("./dc");
```
from **crossfilter** to **crossfilter2**. Could you please help me with this issue? What is the proper fix? Or it is a problem with crossfilter ?
Thank you for your help in advance.

**Comment by gordonwoodhull** [comment]
Unfortunately I am not familiar with Node, and the folks who contributed Node support are no longer here. 

Should the argument to `require` be the name of the module, or the filename of the js file? This varies in the crazy ridiculous number of JavaScript module loaders.

The underlying issue is that crossfilter2 is the name of a drop-in replacement for crossfilter. So the name of the module is not the name of the file. 

See #1214 for the related problem when using webpack.

**Comment by eapyl** [comment]
Hmm, I just checked what npm loaded using `npm install`:
![image](https://cloud.githubusercontent.com/assets/1629511/21956703/728a50d2-da86-11e6-829f-67270d9a1ad8.png)
As I know, nodejs just looked at the name of folder. But the name of module is also crossfilter2.

**Comment by eapyl** [comment]
Anyway, I am planning to use webpack also. So the issue will be solved using `resolve` functionality from webpack. 
So feel free to close the issue.
Thank you for your quick help and response!

**Comment by gordonwoodhull** [comment]
We probably need to update `index.js` then. Thanks for the report! I'll change it in the next release.

Probably not a lot of people are using dc.js in Node. The switch to crossfilter2 was almost nine months ago.

**Comment by jdylanstewart** [comment]
I've just been aliasing it.

Joseph Dylan Stewart

On Jan 14, 2017, at 9:36 AM, Gordon Woodhull <notifications@github.com<mailto:notifications@github.com>> wrote:


We probably need to update index.js then. Thanks for the report! I'll change it in the next release.

Probably not a lot of people are using dc.js in Node. The switch to crossfilter2 was almost nine months ago.

**Comment by gordonwoodhull** [comment]
Thanks @jdylanstewart - you mean you alias it using webpack? Or are there other ways?

**Comment by jdylanstewart** [comment]
I alias in webpack and babel

On Jan 15, 2017, at 1:15 AM, Gordon Woodhull <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @jdylanstewart<https://github.com/jdylanstewart> - you mean you alias it using webpack? Or are there other ways?

**Comment by akuji1993** [comment]
Hm, why can't you just import the crossfilter library in your package.json. Using webpack here, I just added these three lines: 

`  "crossfilter": "^1.3.12",  
    "d3": "^3.5.17",
    "dc": "^2.1.1",`
to my dependencies in package.json and import them like this: 

`  
import * as d3 from 'd3';
import * as dc from 'dc';
import crossfilter from 'crossfilter';`

Works fine for me.

**Comment by emiguevara** [comment]
I am also getting this issue, using webpack and yarn. If I let `dc` install its own dependencies, `crossfilter2` is fetched correctly (I can see it in mu modules folder), but dc still complains about `crossfilter` not being available:

```
Uncaught Error: Cannot find module "crossfilter"
    at webpackMissingModule (dc.js:10707)
    at eval (dc.js:10707)
    at eval (dc.js:10724)
    at Object.<anonymous> (app.bundle.js?68580d4…:12370)
    at __webpack_require__ (app.bundle.js?68580d4…:556)
    at fn (app.bundle.js?68580d4…:87)
    at Object.eval (directives.js:42)
    at Object.eval (directives.js:3725)
    at eval (directives.js:3726)
    at Object.<anonymous> (app.bundle.js?68580d4…:12352)
```

Using the proposal by @akuji1993 is wrong: `"crossfilter": "^1.3.12"` will install the last version by https://github.com/square/crossfilter which is not maintained and is missing functionality in `"crossfilter2": "^1.3.14"`

**Comment by akuji1993** [comment]
Good to know. Still works for the stuff, that I have to do with it, but then it's probably not the right way if you want the newer stuff. Have to keep this in mind for more recent projects, thank you.

**Comment by gordonwoodhull** [comment]
@emiguevara did you try the alias solution from #1214?

**Comment by emiguevara** [comment]
@gordonwoodhull yes, just tried it now. I can confirm that `resolve.alias` in webpack solves the issue with yarn and webpack. Thanks!

**Comment by gordonwoodhull** [comment]
I'm going to close this. If there are any recommendations to help dc.js work with webpack without requiring special configuration, please lmk.

**Comment by KhodeN** [comment]
`define(["d3", "crossfilter"], _dc);` 
You can just change to
`define(["d3", "crossfilter2"], _dc);` 

Why not? I can't edit webpack config in my angular-cli project, and the way to use `resolve.alias` is not available for me.

**Comment by gordonwoodhull** [comment]
As explained in #1214, this does not work in AMD environments, where this specifies the name of the file instead of the name of the module. 

Sorry for the inconvenience - it seems that the only way to make both AMD and Webpack happy is to make http://github.com/crossfilter/crossfilter use the same name for its filename as for its NPM project name.

**Comment by shusson** [comment]
Any updates on this issue?

**Comment by gordonwoodhull** [comment]
Hi @shusson.

We discussed it in crossfilter/crossfilter#75, and I will release new 2.0.* and 2.1.* versions of dc.js which break requireJS in favor of webpack. Both `index.js` and the UMD asynchronous-looking `require()` will read `crossfilter2` instead of `crossfilter`.

requireJS users will have to either set up their builds to copy `crossfilter.js` as `crossfilter2.js`, or do the aliasing in their requireJS configurations.

**Comment by shusson** [comment]
👍  awesome, thanks @gordonwoodhull

**Comment by gordonwoodhull** [comment]
As of dc.js 2.0.3 / 2.1.6, we'll break requireJS compatibility in favor of webpack compatibility. 

See #1304 if this creates problems for you.

**Comment by KhodeN** [comment]
Thanks! Thanks!
