### ISSUE TITLE
LeafletMarkerChart hangs when popup moves chart 2 times

### ISSUE THREAD

**Issue by thebarbarian** [dc-js/dc.js#1263]
I am not sure if it's a bug or my terrible JS-coding, please remove this if i messed up.

When displaying a LeafletMarkerChart and clicking a marker on the edge of the map, the creation of the textballoon will move the map slighly until it fits inside the frame. If i do this two times, i'm unable to drag the map. It's stuck.
The console gave me the following error after the map is stuck and i click a marker:
_markerList.indexOf is not a function(…)

After changing line 583 of dc-leaflet.js : 
(_markerList.indexOf(_chart.filter()) !== -1 &&

into this:
(_markerList.toString().indexOf(_chart.filter()) !== -1 &&

the problem is solved. Adding the toString()-method doesn't seem to affect any of the other graphs on my dashboard.

My apologies if this isn't a bug, but it seemed to make sense to let the developers know.

**Comment by gordonwoodhull** [comment]
This issue was moved to dc-js/dc.leaflet.js#26
