### ISSUE TITLE
Disable pieCharts's "others" slice

### ISSUE THREAD

**Issue by akuji1993** [dc-js/dc.js#1272]
I can't seem to find any setting of piechart in the documentation that can be used to disable the "others" slice in piecharts. I would like to completely disable that part and just let the other capped slices take all of the available room. 

I'm fairly certain that I've seen this setting already, but I can't seem to find it now, that I need it. If this is not a feature, yet, I'd like to report it as improvement.

**Comment by gordonwoodhull** [comment]
Yep it's `.othersGrouper(null)`

http://dc-js.github.io/dc.js/docs/html/dc.capMixin.html#othersGrouper

Should we mention it in the section on the `pieChart` itself?

**Comment by akuji1993** [comment]
Thanks, I think I even was in capMixin, but apparently I didn't see it. I think it'd be helpful to mention it in the pieChart section. Thanks for your help!
