### ISSUE TITLE
limited chart types

### ISSUE THREAD

**Issue by davidpjensen** [dc-js/dc.js#1280]
Hi Gordon & all, I love the dcjs library in terms of syntax, ease of use, etc. However, the chart types supported by dcjs is very limited... Are there plans to add more charts from the d3 library to dcjs?

thanks!

DJ

**Comment by gordonwoodhull** [comment]
There are a few which which have been submitted as PRs which I am in the process of reviewing. 

Please take a look and try those out that you like, and perhaps consider contributing. 

It's also possible to use charts with dc.js without them being part of the library - good examples are [dc-addons](https://github.com/Intellipharm/dc-addons), [dc.leaflet.js](https://github.com/dc-js/dc.leaflet.js), and [dc.graph.js](https://github.com/dc-js/dc.graph.js). Another option is to connect other charts or chart libraries via the chart registry - [this Q&A outlines the necessary steps and links to the documentation](http://stackoverflow.com/questions/25336528/dc-js-listening-for-chart-group-render).

Many charts are not appropriate for linking to crossfilter - this is not a general-purpose UI library, but only for stuff which filters or can be filtered by crossfilter.

It would be more constructive to request particular charts, or to search through the issues to see if they have already been requested and if there has been any progress. So I'm going to close this. General discussion is also [welcome on the users group](https://groups.google.com/forum/?fromgroups=#!forum/dc-js-user-group).
