### ISSUE TITLE
Ordering data table. d3.descending vs d3.ascending.

### ISSUE THREAD

**Issue by pyotr777** [dc-js/dc.js#1287]
I am following this tutorial: https://www.codeproject.com/articles/703261/making-dashboards-with-dc-js-part-3-tips-and-trick

In datatable created with dc.dataTable() I can order rows with .order(d3.descending) (sort by Year column). But if I change to d3.ascending I get the following error:

`TypeError: _chart.dimension().bottom is not a function. (In '_chart.dimension().bottom(_size)', '_chart.dimension().bottom' is undefined)`

I use DC 2.0.1 or 2.0.0 (same error).

Here is my code:
[index.html.txt](https://github.com/dc-js/dc.js/files/835733/index.html.txt)

I changed extension to txt to upload to github.

**Comment by gordonwoodhull** [comment]
Hi @pyotr777!

You are using the trick where a crossfilter group can be passed as the dimension, although the `dataTable` was originally designed to be used with crossfilter dimension objects. (Just to keep everything linked up, here is [the associated example](http://dc-js.github.io/dc.js/examples/table-on-aggregated-data.html).)

If you sort ascending, the data table will attempt to take the N lowest rows (or bins), and groups don't support `.bottom()`. 

https://github.com/dc-js/dc.js/issues/1115#issuecomment-194098201 shows how to write a group wrapper that will allow it to be used with the ascending sort. I'll close this, but please comment if you run into trouble with that technique. Thanks!
