### ISSUE TITLE
Issue with crossfilter dependency in angular-cli

### ISSUE THREAD

**Issue by alexkibler** [dc-js/dc.js#1302]
As referenced in https://github.com/dc-js/dc.js/issues/1214, I recognize why this is an issue, but angular-cli's webpack configuration is not exposed, so I can't simply alias it as other webpack users have done.  I can fix it by changing `define(["d3", "crossfilter"], _dc);` like other people have mentioned, but I propose that either dcjs or crossfilter2 change something in order to make this work the way it's intended.

It seems extremely hacky to have all of our developers have to change a line of code in a node_module whenever we set up the dev environment, and that will be overwritten any time we update the package or reinstall node modules.

**Comment by gordonwoodhull** [comment]
Okay, I've opened an issue in the crossfilter org about this (linked above). 

Personally, I think it's kind of bizarre how webpack uses the AMD spec but then changes this one crucial detail. I guess they are doing it for backward compatibility and they are implementing the [requirejs optimization step](http://requirejs.org/docs/optimization.html). 

But still, it's a compile step, it's not asynchronous, so why does it look asynchronous?

**Comment by alexkibler** [comment]
Yeah, great question.  I have no idea.  Thanks for opening that issue though.  I wasn't sure if that was something that would need to change in dc or in crossfilter so I figured I'd start here since it's dc that's blowing up.  Thanks for the quick response too

**Comment by gordonwoodhull** [comment]
@alexkibler, would you be able to share a simple example project that breaks with the current dc and crossfilter?

**Comment by alexkibler** [comment]
Yep, no problem!  I conveniently made one yesterday for the issue I submitted to angular-cli

https://github.com/alexkibler/DCJSCrossfilterProblem

**Comment by gordonwoodhull** [comment]
Thanks for bumping this, @alexkibler!

As of dc.js 2.0.3 / 2.1.6, we'll break requireJS compatibility in favor of webpack compatibility. 

(Any requireJS users encountering trouble should consult #1304.)
