### ISSUE TITLE
is there any method to find out if filter is applied on any chart in dashboard ?

### ISSUE THREAD

**Issue by asadmkhan** [dc-js/dc.js#1305]
_chart.hasFilter() method returns true if the filter is applied on particular chart false otherwise, I have multiple charts on the dashboard, I want method or property in renderlet function which can tell if any filter is applied on any chart in a dashboard?

Please Help

**Comment by gordonwoodhull** [comment]
There are two answers, depending on whether you want to know if any filters are applied, or whether anything is filtered out.

### Are any filters applied?

You can [use the chart registry to get a list of charts](http://dc-js.github.io/dc.js/docs/html/dc.chartRegistry.html#.list__anchor) for the chart group you're interested in.

So, this one-liner in ES6 will tell you if any filter in the default chart group has filters applied:

```js
dc.chartRegistry.list().some(c=>c.hasFilter())
```

If you need it to work on IE:
```js
!!dc.chartRegistry.list().filter(function(c) { return c.hasFilter(); }).length
```

### Is any data filtered out?

On the other hand, there may be filters applied which aren't actually filtering any data. For example, the brush might include all the data, or all the items in an ordinal chart may be selected.

If you want to handle this case, you can get a count of records using [crossfilter.groupAll()](https://github.com/crossfilter/crossfilter/wiki/API-Reference#crossfilter_groupAll) and compare it to the size of the crossfilter:

```js
var cf = crossfilter(/* your data */);
var countFiltered = cf.groupAll(); // only do this once!
// ... then, where you want to know if any data is filtered out
countFiltered.value() != ndx.size()
```

**Comment by asadmkhan** [comment]
Thanks, that was helpful

**Comment by asadmkhan** [comment]
is there any way to specify column width in dc.js datatable ?
