### ISSUE TITLE
how to remove empty values/bar in dc.js row chart

### ISSUE THREAD

**Issue by asadmkhan** [dc-js/dc.js#1313]
How can i remove empty bars from dc.js row chart, whenever the dimension is null or empty, there appears an empty bar on row chart.
![emptydimension](https://user-images.githubusercontent.com/28774748/27224364-3757263e-52ae-11e7-8cba-f358f4eb425d.png)

**Comment by gordonwoodhull** [comment]
Duplicate here: https://stackoverflow.com/questions/44587863/how-can-i-remove-empty-bars-from-dc-js-row-chart-whenever-the-dimension-is-null

There's no need to cross-post questions, the same folks are here as on SO.
