### ISSUE TITLE
quicksort error

### ISSUE THREAD

**Issue by leninworld** [dc-js/dc.js#1316]
I am getting below error
"dc.js:1342 Uncaught TypeError: Cannot read property 'quicksort' of undefined(…)"

Please let me know if there is any fix for this or I do something wrong.

Thank you!

**Comment by gordonwoodhull** [comment]
Sounds like crossfilter is coming up undefined somehow. dc.js can take any group- and dimension-like objects that look like crossfilter objects, but it still depends on crossfilter for some sorting functions.

What package manager are you using (requireJS, webpack, ...?)

**Comment by leninworld** [comment]
It's requireJS

**Comment by gordonwoodhull** [comment]
I'm going to guess this is #1304, although I'm surprised crossfilter is undefined instead of producing an error earlier (like a 404).

**Comment by gordonwoodhull** [comment]
Hope my guess was correct. Please comment if it was something else.
