### ISSUE TITLE
Add HTML legend support

### ISSUE THREAD

**Issue by manju-reddys** [dc-js/dc.js#1325]
[Something like PR](https://github.com/dc-js/dc.js/pull/577) and I have [asked question](https://stackoverflow.com/questions/45292893/dcjs-customize-the-legend-with-html) but I don't think if some take a look into closed PR so opened this bug for further discussions.

I strongly feel that HTML legend make more sense and it in-fact make life much easy atleast in the following cases [Issue](https://github.com/dc-js/dc.js/issues/1259), [Issue](https://github.com/dc-js/dc.js/issues/1300):

Case-1: huge list of items (see image 1 in our application - summarize data of 300K records since we couldn't show the complete list we added ```"Others"``` to show there more items below )

- Showing them as a vertical list would be impossible because the SVG size may not be enough to fit all of them within the view-able area.
- Even if we manage to show with adjusting gaps etc... it will be nightmare for user to walk through the list to find the particular item in the list.
- Otherwise we must provide the arrow (up/down) to indicate more items are available and this logic would be too complicate and also its too much burden to user to click through the list to find the item of interest.

Case-2: Add advance features:

- Its not easy to implement the search or filter feature in SVG when the list is huge to find the item of interest (see google maps - search by typing address - for example how it will be helpful).
- In many cases it will be convenient to take controls of legends items to enable/disable filter on click of item based on certain condition (ex: if user is Guest / Author) - this just an example.
- Would allow to taking advantage of JS frameworks data binding (Angular 2) and custom template to add meaningful presentation etc...
- Add collapse and expand the legend or add more features like drag to position on the chart.

Case-3: Customize (see the google map image)

- Allow to skin the legend to the application theme (material design!).
- Not everyone JS developer are styling experts, many of the JS developer use the CSS frameworks like bootstrap to develop the website/web-applications and those frameworks doesn't provide the styling feature for SVG.

![legend](https://user-images.githubusercontent.com/1906881/28609049-df52affe-7197-11e7-9b75-5b371a278f28.PNG)
![google-maps](https://user-images.githubusercontent.com/1906881/28609055-e37a1ac2-7197-11e7-9074-9105507e5c80.PNG)

**Comment by gordonwoodhull** [comment]
Thanks for posting these arguments. They are persuasive.

I agree with all of your points except for one. 

For the advanced features, I don't think it will be any easier to take control over the legend click action. You can easily change the click behavior using d3, for example see [this answer about toggling composite child charts on legend click](https://stackoverflow.com/questions/43071163/dc-js-composite-chart-toggle-chart).

I also think it would be easy to add collapse/expand functionality with a similar "renderlet", but I agree it would be nice to use existing JavaScript libraries to do drag-and-drop. Sadly, it doesn't seem that the d3 ecosystem has developed reusable behaviors to quite the degree that there are HTML DOM libraries.

The quickest way to get this feature into the library is to review @davejlong's PR (or start your own `dc.htmlLegend` if for some reason you don't like it). 

If you don't want to rebase the branch, you should be able to try it out just by copying the content of `src/html-legend.js` into your local copy of dc.js.

Once you've tried it out, please comment on #577 and I'll reopen it.

Please carefully review the interface of the original legend:
http://dc-js.github.io/dc.js/docs/html/dc.legend.html

I think that almost all of these are layout-related and can better be done with CSS, but `legendText` and `maxItems` should probably be added to #577 if we go with that. Would you be willing to start a new PR and add these, along with tests?

**Comment by rrameshkumar76** [comment]
I did not realize that Html legend [PR](https://github.com/dc-js/dc.js/pull/577) exists. I will first try this by copying the content in my project. We do use legendText currently with dc.legend.

**Comment by rrameshkumar76** [comment]
I tired the code copying the html legend into my project with some modifications. It worked great as expected. I can make a PR from my [fork](https://github.com/rrameshkumar76/dc.js). I have added legendText and maxItems and made some changes to make render method common for horizontal/vertical. Please let me know if it is fine for me to make a pull request.

**Comment by rrameshkumar76** [comment]
I tired the code copying the html legend into my project with some modifications. It worked great as expected. I can make a PR from my [fork](https://github.com/rrameshkumar76/dc.js). I have added legendText and maxItems and made some changes to make render method common for horizontal/vertical. Please let me know if it is fine for me to make a pull request.

**Comment by gordonwoodhull** [comment]
I took a quick look at your fork. This is great. Thanks for updating the tests along with adding the new functions.

Please open a new PR to replace #577. I will review it more closely, and then merge it for 2.1.x.

**Comment by rrameshkumar76** [comment]
Thanks, I have made the [PR](https://github.com/dc-js/dc.js/pull/1329)

**Comment by gordonwoodhull** [comment]
Implemented in 3.0.0
