### ISSUE TITLE
Tooltip for the stacked bar chart

### ISSUE THREAD

**Issue by imran-nd** [dc-js/dc.js#1327]
I want to add the tooltip for the stacked bar chart in dc.js. I am able to add title and it is displaying correctly. But i feel its response time is little higher than d3 tool tip.

Please help me out to add tooltip for the stacked bar chart in dc.js.

**Comment by gordonwoodhull** [comment]
d3-tip isn't integrated in the core library, but it's so easy to add that I've never felt it was needed.

Please take a look at this Q&A and ask there, users group, or here if you have any further questions.

https://stackoverflow.com/questions/24664079/d3-tooltips-for-multiple-linked-dc-js-charts
