### ISSUE TITLE
Errors for Geo choropleth chart using crossfilter 

### ISSUE THREAD

**Issue by 8sam** [dc-js/dc.js#1332]
I have been following some tutorials and trying to make a geo choropleth chart which gets filtered on clicking on a pie chart. I am using the exact code from the example, but just using cdn instead of downloading the stuff.

The following is the error:

TypeError: dc.leafletCustomChart is not a function
    at geo-choropleth--piechart.html:76
    at d3.js:2011
    at Object.<anonymous> (d3.js:1996)
    at Object.event (d3.js:504)
    at XMLHttpRequest.respond (d3.js:1949)

Here is the code:
`<!DOCTYPE html>
<html>
 
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.2.0/dist/leaflet.css" integrity="sha512-M2wvCLH6DSRazYeZRIm1JnYyh22purTM+FDB5CsyxtQJYeKq83arPe5wgbNmcFXGqiSH2XR8dT/fJISVA1r/zQ==" crossorigin=""/>
    
    <script src="https://unpkg.com/leaflet@1.2.0/dist/leaflet.js" integrity="sha512-lInM/apFSqyy1o6s89K4iQUKg6ppXEgsVxT35HbzUupEVRh2Eu9Wdl4tHj7dZO0s1uvplcYGmt3498TtHq+log==" crossorigin=""></script>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/MarkerCluster.Default.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/0.4.0/leaflet.markercluster.js"></script>
     
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js" charset="utf-8"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.12/crossfilter.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/dc/1.7.5/dc.js"></script>
    
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/dc/1.7.5/dc.css"/>
     
    <meta http-equiv="content-type" content="text/html; charset=UTF8"> 
    
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <style>
        #holder {
          width:850px;
          margin:20px auto;
        }
        #holder>div {
          padding:30px 0;
          clear:both;
        }
        .map {
          width:600px;
          height:400px;
        }
        .pie {
          margin-left:30px;
        }
      </style>
</head>
<body>

    <div id="holder">
        <div id="demo1">
            <div class="map"></div>
            <div class="pie"></div>
        </div>
    </div>

    <script>
        /*     Markers      */
        d3.tsv("data/demo1.tsv", function(data) {
          var xf = crossfilter(data);
          var facilities = xf.dimension(function(d) { return [d.type, d.geo]; });
          var facilitiesGroup = facilities.group().reduceCount();

          var markers = {};

          dc.leafletCustomChart("#demo1 .map")
              .dimension(facilities)
              .group(facilitiesGroup)
              .width(600)
              .height(400)
              .center([42.69, 25.42])
              .zoom(7)
              .renderItem(function(chart, map, d, i) {

                  var icon = null;

                  if (d.key[0] === 'solar') {
                      icon = 'http://maps.google.com/mapfiles/ms/icons/red-dot.png';
                  } else if (d.key[0] === 'wind') {
                      icon = 'http://maps.google.com/mapfiles/ms/icons/purple-dot.png';
                  } else if (d.key[0] === 'hydro') {
                      icon = 'http://maps.google.com/mapfiles/ms/icons/blue-dot.png';
                  } else if (d.key[0] === 'hydro_waste') {
                      icon = 'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png';
                  } else if (d.key[0] === 'biomass') {
                      icon = 'http://maps.google.com/mapfiles/ms/icons/green-dot.png';
                  } else if (d.key[0] === 'gas_waste') {
                      icon = 'http://maps.google.com/mapfiles/ms/icons/orange-dot.png';
                  }

                  var marker = new L.Marker(chart.toLocArray(d.key[1]), {
                      title: d.key[0] + " : " + d.value,
                      alt: d.key[0] + " : " + d.value,
                      icon: new L.icon({
                          iconUrl: icon,
                          iconSize: [25, 25],
                          className: 'dot'
                      }),
                  });

                  marker.addTo(map);

                  markers[i] = marker;
              })
              .redrawItem(function(chart, map, d, i) {
                  markers[i].setOpacity(d.filtered ? 0 : 1);
              });

            var types = xf.dimension(function(d) { return d.type; });
            var typesGroup = types.group().reduceCount();

          dc.pieChart("#demo1 .pie")
              .dimension(types)
              .group(typesGroup)
              .width(200)
              .height(200)
              .renderLabel(true)
              .renderTitle(true)
              .ordering(function (p) {
                return -p.value;
              });

            dc.renderAll();
        });
    </script>
</body>`

On running this code, I get a blank page, which on inspecting I see the error mentioned above. Where am I going wrong?

Any help would be greatly appreciated. Thanks.

**Comment by gordonwoodhull** [comment]
Thanks @vparpoil!

I think I saw this over vacation and came to the same conclusion, but didn't have time to respond.
