### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by kranthibhagath** [dc-js/dc.js#1336]
![script](https://user-images.githubusercontent.com/31399202/30310243-210ce492-97ad-11e7-811d-9c8958cf7a34.jpg)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://52.76.150.154/PasuraWs/dashboardreports/Filter_state_desig_select.php. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
XMLHttpRequest cannot load http://52.76.150.154/PasuraWs/dashboardreports/Filter_state_desig_select.php. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Hai 
please can anyone slove this issue
i am getting data form server and using firefox and iam getting this error

**Comment by gordonwoodhull** [comment]
The browser will not allow you to use data that comes from a server different from the one serving your html page, unless this special http header is included with the data.

The mechanism is called CORS: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

You are probably using a file:// for your html. You'll either have to put your html on the same server (origin) as the data or change the server to include this header.
