### ISSUE TITLE
Using date as dimension, can I change the date format shown in the bar chart tittle.

### ISSUE THREAD

**Issue by Smmw** [dc-js/dc.js#1341]
What I mean is change the date format in the range: yyyy-MM-dd - yyyy-MM-dd

![image](https://user-images.githubusercontent.com/3632980/30640360-b57a8d1e-9e56-11e7-9b61-72557485e24c.png
The actual format in the csv file is 
![image](https://user-images.githubusercontent.com/3632980/30640383-ca0d72be-9e56-11e7-9a45-fee46d846ae0.png)

**Comment by gordonwoodhull** [comment]
Yes.

http://dc-js.github.io/dc.js/docs/html/dc.baseMixin.html#filterPrinter__anchor

**Comment by Smmw** [comment]
Thanks!!!
