### ISSUE TITLE
Uncaught TypeError: Cannot read property 'format' of undefined

### ISSUE THREAD

**Issue by unnur28** [dc-js/dc.js#1343]
I keep getting the following error:

Uncaught TypeError: Cannot read property 'format' of undefined
    at _dc (dc.js:sourcemap:501)
    at dc.js:sourcemap:10721
    at dc.js:sourcemap:10724

I am using dc.js-2.0.2 and d3.js-3.5.17 as was recommend in another answer.

**Comment by gordonwoodhull** [comment]
You'd have to share your code for us to know what's going wrong. Given the name "format", it's likely that either  

 1. you are trying to use dc.js with d3v4 (I know, you say you're using 3.5.17 but maybe something went wrong). It's possible to include both in one page but one of them will have to be renamed.
 2. one of your columns is specified incorrectly for your dataTable - if a column spec is not a string and not a function, dc.js will assume it's an object with a member named `format`

**Comment by gordonwoodhull** [comment]
Given line 501, it's definitely the former. I don't know what you did wrong, but you definitely have the wrong version of d3.
