### ISSUE TITLE
dc.js and d3.js are not working in eclipse?

### ISSUE THREAD

**Issue by Smmw** [dc-js/dc.js#1345]
When I load the web page:
![image](https://user-images.githubusercontent.com/3632980/31051581-4dc9757a-a6c8-11e7-922d-09847fba3247.png)

This is how I link to external js files
`	<script src="JS/jquery-3.2.1.min.js" type="text/javascript"></script>
<script src="JS/crossfilter-master/crossfilter.js" type="text/javascript"></script>			
<script src="JS/d3-3.5.17/d3.js" type="text/javascript"></script>
<script src="JS/dc.js-2.0.2/dc.js" type="text/javascript"></script>
<script src="JS/d3-queue/d3-queue.js" type="text/javascript"></script>`

**Comment by gordonwoodhull** [comment]
d3.js 3.* used Unicode characters in its code. You probably ran into this:

https://github.com/d3/d3/issues/1195

The subsequent errors are due to d3 not loading.

**Comment by Smmw** [comment]
Yes, It solved my problem! thanks!
