### ISSUE TITLE
create multiple charts from data groups of the same column

### ISSUE THREAD

**Issue by gubzh** [dc-js/dc.js#1349]
How create multiple charts from data groups of the same column, using dc.js?

This issue is on https://stackoverflow.com/questions/46757188/create-multiple-charts-from-data-groups-of-the-same-column.

Thank you in advance.

**Comment by gordonwoodhull** [comment]
Yeah I saw it in the other places, just haven't had time to write it up. SO or the user group are the right places.

**Comment by gubzh** [comment]
I found similar question 

https://stackoverflow.com/questions/42998197/multiple-numberdisplays-from-group

but I need to add sparklines in dashboard.
