### ISSUE TITLE
develop branch IE fix to master

### ISSUE THREAD

**Issue by cmorgan** [dc-js/dc.js#1350]
Is there anything stopping @vparpoil 's IE fix merged into master? I notice the test Travis is failing - but this seems like a config error?

**Comment by gordonwoodhull** [comment]
Thanks @cmorgan - I had hoped to do more extensive testing but this languished as a result.

(It would be great to have an automated test for this problem, but it's a good amount of work to write such a test.)

I went ahead and released 2.1.9 today.

**Comment by rrameshkumar76** [comment]
Has 2.1.9 been published to npm? I could not find it in https://www.npmjs.com/package/dc

**Comment by gordonwoodhull** [comment]
Ahem! Sorry for the delay. It is published now.

**Comment by rrameshkumar76** [comment]
Thanks a lot gordon. I can see it.
