### ISSUE TITLE
How to color all bars grey when filters are empty?

### ISSUE THREAD

**Issue by coolpopo** [dc-js/dc.js#1377]
Is there a way to color all bars grey if the filters are empty? It's confusing when users deselect all the bars and all of a sudden, they're all colored again.

**Comment by gordonwoodhull** [comment]
Hi @coolpopo! There's no need to cross-post for this library. I'm thinking over your question and hope to have an answer on SO soon.

https://stackoverflow.com/questions/49387809/how-to-make-all-bars-on-barchart-grey-on-no-filters-selected-dc-js
