### ISSUE TITLE
TypeError: setting getter-only property "event"

### ISSUE THREAD

**Issue by Justus-Maier** [dc-js/dc.js#1396]
I'm using d3-ng2-service to integrate D3 into Angular, now I'm also trying to use dc.js (3.0 branch), but I get errors when trying to draw a simple barchart, because d3-ng2-service builds it's own D3 with the modularised parts, and dc.js brings another instance of D3 (copying inbetween gives read-only errors).
```
TypeError: setting getter-only property "event"
Stack trace:
_dc/dc.coordinateGridMixin/_chart._brushing@webpack:///./node_modules/dc/dc.js?:3956:9
```
@kum-deepak did you touch #1175 yet? Can't follow your reference to it..
It feels the solution for me lies within..

How can I inject my instance of D3 into DC.js?

**Comment by Justus-Maier** [comment]
@gordonwoodhull what about importing only the parts of D3 that are actually used by DC.js? How would you interface with d3-ng2-service?

**Comment by gordonwoodhull** [comment]
Sorry, I don't know anything about d3-ng2-service. I agree it's going to be a problem if you try to use dc.js with a custom build of d3 designed for some other library.

I'd consider adding a custom build of d3 to dc.js (e.g. an `index.js` for rollup to assemble the relevant bits). I don't know if that would help you or not. I'm focused on getting 3.0 out the door, so for now I recommend using the kitchen-sink d3.js.

**Comment by Justus-Maier** [comment]
The index.js approach will be fine I guess. That will deduplicate the d3(-*) dependencies and reduce overall footprint of DC.js. Obviously treeshakable chart modules would be better, when only using one or a few charts from DC.

**Comment by gordonwoodhull** [comment]
Yes, rollup supports tree shaking - I think we'd just need to `import` the specific functions needed, rather than importing `*`. 

I hope to break up dc.js into dozens of rollup modules, but it's a huge effort so I hope to find volunteers to help with that. I guess that would be dc.js 4.0.

Contributions are welcome for other module systems - I just don't personally intend to learn/support anything but rolllup.

**Comment by Justus-Maier** [comment]
@kum-deepak thank you, I'm no longer encountering this error.

**Comment by gordonwoodhull** [comment]
Glad to hear it!
