### ISSUE TITLE
@types/dc v0.0.27 seems not to define everything

### ISSUE THREAD

**Issue by sergey-br-st** [dc-js/dc.js#1397]
Hello.

I'm using these npm packages:
- **@&#8203;types/dc v0.0.27**
- **dc v2.1.10**

Visual Studio 2017 IntelliSense doesn't see certain members from **dc** in my TypeScript code, for example, these ones:
- drawPaths
- externalRadiusPadding
- externalLabels

In connection with this, I have to write something like this casting **dc.PieChart** to **any** so that my code can compile:
```
const pieChart: dc.PieChart = dc.pieChart('#pieChart');
const pieChartWeaklyTyped = <any>pieChart;
pieChartWeaklyTyped.drawPaths(true);
pieChartWeaklyTyped.externalRadiusPadding(123);
pieChartWeaklyTyped.externalLabels(123);
```

How could I overcome this nuance?

Thanks.

**Comment by gordonwoodhull** [comment]
Hi @sergey-br-st, the TypeScript definitions in DefinitelyTyped are maintained by others, so I think you'd have to file an issue or (better) a PR at https://github.com/DefinitelyTyped/DefinitelyTyped

I've never looked at them before, but in a quick search it looked like the definitions are simply out of date. These features go back to around 2.0 beta 13, but the definitions may be even older. 

I don't know who the champion for dc was within that project, but maybe they moved on.
