### ISSUE TITLE
restore brush animation and correct height on resize

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1399]
In this example you can resize the browser window to test chart resizing:

http://127.0.0.1:8888/web/resizing/resizing-bar.html

The brush used to transition at the same speed as the chart; now it changes immediately. (This was the purpose of the `doTransition` argument to `redrawBrush`, used in `drawChart`.)

Also it seems to get the width right but height stays at the original height.

If you fix the `onresize` bug (thank you @kum-deepak!), this example works in 2.1: http://dc-js.github.io/dc.js/resizing/resizing-bar.html

**Comment by kum-deepak** [comment]
On to it :)

**Comment by kum-deepak** [comment]
Looks like I have to practice first some transition examples.

As of now I am able to handle the resizing correctly, animate the brush handles. Unable to animate the brush selection rectangle (it is done by d3.brush, but the documentation says that transitions can be applied on that).

**Comment by gordonwoodhull** [comment]
Don't you just pass a transition to `_brush.move` instead of a selection? That is sort of how it used to work, except that it was just `something.call(_brush)` before.

**Comment by kum-deepak** [comment]
Started work #1402. Based on your feedback, I will implement for other classes as well.

**Comment by gordonwoodhull** [comment]
fixed in 3.0 alpha 7
