### ISSUE TITLE
exiting bars turn grey first

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1401]
From https://github.com/dc-js/dc.js/pull/1363/#issuecomment-373955979

> In the multi focus example, bars turn grey before being filtered/focused (?) out instead of just disappearing. Not sure which behavior is better here, but we should figure out what is going on here and decide one way or the other.

Also, the bars stay deselected when the range chart is reset to no filter:

<img width="880" alt="image" src="https://user-images.githubusercontent.com/1366709/38468880-2dca867e-3b1a-11e8-93e1-f630992327d0.png">

Looks like the reset bug can be fixed by simplifying the example. Applying `fadeDeselected` to the focus charts is arguably correct but distracting & annoying.

**Comment by gordonwoodhull** [comment]
Feel free to take it. I guess we are applying `fadeDeselected` earlier than we used to.

**Comment by kum-deepak** [comment]
Tried to find a solution. However I am unable to find any simple code fix. Please see if you are able to find a solution.

**Comment by kum-deepak** [comment]
Please check #1422

**Comment by gordonwoodhull** [comment]
Your fix makes sense. Will check this morning.

**Comment by gordonwoodhull** [comment]
Fixed in 3.0 beta 1
