### ISSUE TITLE
remove schemeCategory20c in a backward-compatible way

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1403]
In #1394 I wrote:
> There are good reasons why schemeCategory20c was removed. So we should switch probably to schemeCategory10c or a colorbrewer scheme e.g. as suggested in #831.
>
> This means fixing a lot of tests, documenting the change pointing to the rationale in d3v5, and offering the workaround used here in the documentation. IMO we should not provide schemeCategory20c in the library because it is misleading.

@kum-deepak wrote:
> Alternatively we can introduce a global switch to keep current behavior with a warning. In 3.1 we can make full switch.

I replied:
> The color brewer colors are dramatically different but much more clear, so I agree we should probably do backward compatibility with a warning.
>
> We don't currently have any global flags, but that's an interesting idea. Maybe it would be worth introducing a special facility under `dc` just for this, say `dc.compatFlags`, since we have so many things we want to fix while allowing backward compatibility.
>
> In this case, there could be a flag, say `brewerCategoricalColors`, which defaults to false. The first time we need defaulted categorical colors, because the chart doesn't have any colors set, we check this flag and if it's still false, we use the copied colors from above and issue a warning that says we're moving to brewer and mentions `schemeCategory10c`, which is close to the old default but obviously has less colors.
>
> If it's true, we use the color brewer colors with no warning.

This is just a suggestion; there are other ways to implement this. But in any case, we should not write to `d3`. `src/d3v3-compat.js` should go away before we release dc.js 3.0

**Comment by kum-deepak** [comment]
Thanks for creating this :)

**Comment by kum-deepak** [comment]
Can you suggest which colors should we use as default. Planning to work on this now.

**Comment by gordonwoodhull** [comment]
Tough choice! Please start with [schemeSet1](https://github.com/d3/d3-scale-chromatic/blob/master/README.md#schemeSet1) and we'll see how it works. It is going to change our look dramatically!

@tttp in his proposed #831 noted that there may be difficulties with the default white label text and some background colors. I can't recall if this was a problem with the old color scheme.

Elsewhere I have implemented labels that switch from white to black depending on the luminosity of the background color. We could add that if we need it.

**Comment by kum-deepak** [comment]
Please see #1409

I have created a framework so that changing the pallet will not cause huge breakage in the specs.

**Comment by gordonwoodhull** [comment]
@kum-deepak implemented a nice solution with a new global configuration`dc.config.defaultColors` which defaults to a copy of the old colors, deprecated with a warning.

Released in dc.js 3.0 alpha 10.

**Comment by tadiraman** [comment]
@gordonwoodhull i dont think 3.0 alpha 10 is working, actually the comment at the top of the file says dc 3.0.0-alpha.9.  This change is breaking the cross filter charts. Is there any immediate solution to this?

**Comment by gordonwoodhull** [comment]
Please try beta 1, which was just released today. 

What do you mean, not working? If you want help you **always** need to describe the problem and how to reproduce it. In particular, what errors do you see in the browser console?

**Comment by tadiraman** [comment]
@gordonwoodhull 
Here is the console log error.
_You are using d3.schemeCategory20c, which has been removed in D3v5. See the explanation at https://github.com/d3/d3/blob/master/CHANGES.md#changes-in-d3-50. DC is using it for backward compatibility, however it will be changed in DCv3.1. You can change it by calling dc.config.defaultColors(newScheme). See https://github.com/d3/d3-scale-chromatic for some alternatives._

**Comment by gordonwoodhull** [comment]
That's a warning, not an error. It tells you what you can do to make the warning to away.

**Comment by tadiraman** [comment]
OK. You are right! The actual error which caused breaking was the way d3.csv function working. I think some examples refer the old way d3.csv("filename", function(error, data){}); I did correct to d3.csv("filename").then(function (data) {});

**Comment by gordonwoodhull** [comment]
Yes, that has changed with D3v5. 

If you see an example we missed, please let us know. Aside from every fiddle and every SO answer now being wrong, I think we have updated everything in the repo and website.

**Comment by tadiraman** [comment]
OK. Thanks for the quick responses. I appreciate it!

**Comment by tttp** [comment]
Ooh, i like the idea of automatically switching colours based on the
background! Probably better to set the class dark vs light, so we can more
easily tune them

Imo should be an default for all the charts, adding the class, those that
want something different can simply css their way out of it

**Comment by badrinath389** [comment]
Warning on D3V5.
"d3": "5.1.0",
"dc": "3.0.0",
"crossfilter": "1.3.12",

**## Getting below warning for this code `dc.barChart('#variationDollarGoal')`**

`dc.js:965 You are using d3.schemeCategory20c, which has been removed in D3v5. See the explanation at https://github.com/d3/d3/blob/master/CHANGES.md#changes-in-d3-50. DC is using it for backward compatibility, however it will be changed in DCv3.1. You can change it by calling dc.config.defaultColors(newScheme). See https://github.com/d3/d3-scale-chromatic for some alternatives.`

Can you give me some suggestions? Thanks in advance

**Comment by kum-deepak** [comment]
@badrinath389 it is a warning, please check https://github.com/d3/d3-scale-chromatic for some alternatives. If you are confused, you can ignore the comment.

**Comment by gordonwoodhull** [comment]
The warning is mostly there because the colors will change (probably to one of the colorbrewer schemes) in 3.1, so you need to take steps if you want to keep the old colors.

The old colors are arguably defective because they imply relationships which are not there - see the above links for details.
