### ISSUE TITLE
horizontal brush is showing in scatter plot

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1406]
<img width="594" alt="screen shot 2018-04-14 at 12 49 57 pm" src="https://user-images.githubusercontent.com/1366709/38770537-66b190a0-3fe2-11e8-8cdc-4e9faf46d227.png">

It looks like somehow we have two brushes in the scatter plot. The XY brush works fine, but the horizontal brush crashes if you try to drag it.

I haven't looked closely at the implementation to see why this is.

**Comment by kum-deepak** [comment]
It was fixed in one of the later commits for #1402, I will open another PR with the remaining changes.

**Comment by kum-deepak** [comment]
Please check #1407

**Comment by gordonwoodhull** [comment]
Oh phooey did I miss a commit? Thanks for the prompt fixup!

**Comment by kum-deepak** [comment]
No, not your issue, it was buried as part of refactoring. I have created a simple PR (just one line change) and also used this opportunity to add a test case, which fails without this commit.

**Comment by gordonwoodhull** [comment]
fixed in 3.0 alpha 8
