### ISSUE TITLE
Color interpolation difference in D3 v5.1.0

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1427]
In the test case `dc.colorMixin with numeric domain linear` results are different for D3 v 5.0.0 and v 5.1.0:

- [ 'rgb(71, 115, 179)', 'rgb(69, 117, 180)', **'rgb(88, 198, 186)'**, 'rgb(255, 255, 191)', 'rgb(255, 255, 192)', 'rgb(69, 117, 180)' ] in D3 v 5.0.0
- [ 'rgb(71, 115, 179)', 'rgb(69, 117, 180)', **'rgb(77, 198, 193)'**, 'rgb(255, 255, 191)', 'rgb(255, 255, 192)', 'rgb(69, 117, 180)' ] in D3 v 5.1.0

Please notice the difference in the 3rd item.

This test case does test an important aspect, so, would like to drop it. @gordonwoodhull any suggestions?

**Comment by gordonwoodhull** [comment]
I couldn't find documentation to back this up, but the implementation of the HCL color space did change in 5.1. If interpolation uses HCL then that would explain it. 

But that's the part I couldn't find documented - [d3-interpolate says](https://github.com/d3/d3-interpolate#interpolate) it uses RGB interpolation for colors , which would not be very good, and also would not have changed.

**Comment by kum-deepak** [comment]
I will look onto this issue deeply. That is bit interesting because just change in D3 version from 5.0.0 to 5.1.0 makes this case fail.

I might move this test into an independent group - as this does not fit with rest anyways.

**Comment by gordonwoodhull** [comment]
We are always vulnerable to changes in the color algorithms in D3, but I don't expect this to change again soon.

I'd be interested to know if interpolation uses HCL instead of RGB

**Comment by kum-deepak** [comment]
I checked the code. The test case calls `chart.linearColors` which uses `d3.interpolateHcl`.

**Comment by gordonwoodhull** [comment]
I don't understand why 5.1 was not pulled in automatically, given that we had 

```json
    "d3": "^5"
```

Even with `^5.x` (and removing `package-lock.json`) it didn't get pulled automatically. I had to use `^5.1`.

This is not how I read [caret ranges in semver documentation](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004). Ah well.

**Comment by gordonwoodhull** [comment]
Thanks @kum-deepak, I'm having trouble verifying that but it seems to be the case. If so, the documentation for `d3-interpolate` may be out of date, because it says it uses `d3.interpolateRgb`.

**Comment by kum-deepak** [comment]
Oh, the `d3.interpolateHcl` is in [dc color mixin](http://dc-js.github.io/dc.js/docs/html/dc.colorMixin.html#linearColors__anchor):

```javascript
    _chart.linearColors = function (r) {
        return _chart.colors(d3.scaleLinear()
                             .range(r)
                             .interpolate(d3.interpolateHcl));
    };
```

**Comment by gordonwoodhull** [comment]
Duh!!! It was right before my eyes. Okay, that's great that we use that, much better than the default.

Fixing the test right now.

**Comment by kum-deepak** [comment]
Actually we may not need to set dependency to `"d3": "^5.1"`. `npm` uses cache when installing locally, so forcing a cache update should allow installing newer version without changing `package.json`. Let me check.

**Comment by kum-deepak** [comment]
Running `npm update d3` will update `d3` to latest version as allowed by `package.json`. See https://docs.npmjs.com/cli/update

Your change however is still correct, so, I do not see any reason to change anything. 😄

**Comment by gordonwoodhull** [comment]
Ah that explains it. Thank you!

`npm update` instead of `npm install`, right, of course. That always trips me up because "install" sounds like it would start from scratch.
