### ISSUE TITLE
Possible issue in dc.filters.RangedTwoDimensionalFilter - Math.max / Math.min

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1432]
There may be a possible issue in dc.filters.RangedTwoDimensionalFilter as it uses Math.max and Math.min. These functions do not go well if parameters are dates.

I will investigate further, probably write test case(s) and if indeed it is a problem, I will submit a PR.

I have also searched the complete src folder, could not find any other potentially dangerous usage of Math.max / Math.min.

**Comment by kum-deepak** [comment]
It is not an issue as proved by additional test cases added by #1437.

**Comment by gordonwoodhull** [comment]
I think less-than and greater-than are okay for dates. It's only `===` that causes trouble.

Anyway it's great that we test this now!
