### ISSUE TITLE
D3v4 tests failing (on IE?)

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1434]
I did make the main page (stock example) dependent on D3v5. I don't think we currently test the main page.

I can't find the actual error in the log. I probably didn't look close enough - might take a look tomo if I'm not busy having a weekend:
https://travis-ci.org/dc-js/dc.js/jobs/377935673

It looks like IE is failing. But it also says all but one Jasmine test succeed on all browsers and I don't know what it means by that.

Probably it means that IE is failing one test duh.

**Comment by kum-deepak** [comment]
It does not necessarily mean that tests failed on IE. The logs just indicate that SauceLabs did not connect. Triggering a rebuild might be sufficient.

**Comment by kum-deepak** [comment]
I have checked later builds, IE tests are passing. So, probably this can be closed.

**Comment by gordonwoodhull** [comment]
I see. Guess it is just saucelabs instability.
