### ISSUE TITLE
Some of your tests did a full page reload!

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1451]
Saw this in [Job #2023.1](https://travis-ci.org/dc-js/dc.js/jobs/385830363).

I doubt this actually happened. @kum-deepak, is it Karma flakiness?

Wish we weren't getting so many spurious errors these days!

**Comment by kum-deepak** [comment]
It is definitely annoying.

Let me have a look. It indeed looks like Karma flakiness. I will try to find a way to mask/ignore this error.

**Comment by gordonwoodhull** [comment]
Thanks @kum-deepak! That looks reasonable - let's try it, if it's not too difficult.

Although, this is actually the first time this has happened, so we can also wait to see if it's a recurring problem.
