### ISSUE TITLE
what is supported d3 version for dc.js?

### ISSUE THREAD

**Issue by js418** [dc-js/dc.js#1453]
I have done a project one years ago, and I used d3 v3 and dc. Now dc does not support d3 v5. What should I CHANGE? 

```html
<script type="text/javascript" src="https://dc-js.github.io/dc.js/js/d3.js"></script>     

<script type="text/javascript" src="https://dc-js.github.io/dc.js/js/crossfilter.js"></script>      

<script type="text/javascript" src="https://dc-js.github.io/dc.js/js/dc.js"></script>     

<script type="text/javascript" src="colorbrewer.min.js"></script>    

<script type="text/javascript" src="d3.layout.cloud.js"></script>
```

**Comment by gordonwoodhull** [comment]
Please don't use github.io as a CDN, because you never know what version you'll get.

That said, the new version 3.* emphatically *does* support D3v5, and that's also what you should be picking up with the code above.

What error are you getting?

**Comment by js418** [comment]
Here is the my link:
http://www-edlab.cs.umass.edu/~jiesong/

All the plots can not be drawn. And I tried to edit my code by using v5, but it seems that I need to change so many codes there~

**Comment by gordonwoodhull** [comment]
Cool, Amherst is my hometown!

Right, porting to D3v4 or v5 is a serious effort. Once you get the hang of it, it's not a big deal, and a lot of the changes are just renames. But if you want your code to just work, use these CDN links for dc.js 2.*, d3.js 3.*, and crossfilter 1.4.*

Then you won't be susceptible to breaking changes in anyone else's code:

### using unpkg
```
https://unpkg.com/d3@3/d3.js
https://unpkg.com/crossfilter2@1.4/crossfilter.js
https://unpkg.com/dc@2/dc.js
https://unpkg.com/dc@2/dc.css
```

### using CDNJS
```
https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js
https://cdnjs.cloudflare.com/ajax/libs/crossfilter2/1.4.6/crossfilter.js
https://cdnjs.cloudflare.com/ajax/libs/dc/2.2.0/dc.js
https://cdnjs.cloudflare.com/ajax/libs/dc/2.2.0/dc.css
```

**Comment by js418** [comment]
Thanks a lot!!!!

**Comment by ninjakx** [comment]
@gordonwoodhull 

I am using version:
d3: v5
dc: 3.2.1
crossfilter: 1.1.1

I am able to render graphs but I am getting this error when I filter via clicking on other graph.

```
dc.js:1488 Uncaught TypeError: dimension.filterFunction is not a function
    at _filterHandler (dc.js:1488)
    at applyFilters (dc.js:2405)
    at Object._chart.filter (dc.js:2505)
    at dc.js:2563
    at Object.dc.events.trigger (dc.js:1233)
    at Object._chart.onClick [as _onClick] (dc.js:2562)
    at Object.onClick (dc.js:5223)
    at SVGPathElement.onClick (dc.js:6004)
    at SVGPathElement.<anonymous> (d3.v5.min.js:2)
```
When I click on each bar of Bar types graph (on right) I get this error. This happen with all of the graphs.

![Screenshot from 2020-04-01 18-04-34](https://user-images.githubusercontent.com/29797787/78138650-e95ce980-7444-11ea-9185-11ab7f241dc2.png)
![Screenshot from 2020-04-01 18-04-39](https://user-images.githubusercontent.com/29797787/78138662-ed890700-7444-11ea-9056-ee24d3cda984.png)
![Screenshot from 2020-04-01 18-04-44](https://user-images.githubusercontent.com/29797787/78138671-f11c8e00-7444-11ea-9c6d-0f42e2f8f748.png)

**Comment by gordonwoodhull** [comment]
Hi @ninjakx, the dimension referenced here is a crossfilter object, and that version of crossfilter is very old. Please use version 1.3 or above. 

Note that there is a community fork of crossfilter in NPM which goes by `crossfilter2`. It has a few more features, but either should work!
