### ISSUE TITLE
bower.json: wrong d3 dependency for v3.04

### ISSUE THREAD

**Issue by silentmantra** [dc-js/dc.js#1458]
v3.04 uses d3.timeFormat, that was introduced in d3 v4.x
however the bower.json contains a dependency to d3 v3.x.

**Comment by devleaks** [comment]
Please keep bower.json in sync with package.json
(as today: package.json has "crossfilter2": "^1.4.5", "d3": "^5.4.0", while bower still "d3": "3.x", "crossfilter2": "~1.4")
Thank you.

**Comment by seantai** [comment]
Is there any plan for this to be updated? It seems like the bower.json is still out of date in its d3 dependency.

**Comment by gordonwoodhull** [comment]
Sorry, bower is not on my radar, obviously. 

I'll correct this in the next release, and see if it can be generated from package.json somehow.

**Comment by seantai** [comment]
Cool, thanks!

**Comment by gordonwoodhull** [comment]
Sorry for the extreme delay. 

I'm updating `bower.json` in version 3.1.7 and deprecating Bower support - dc.js version 4 will not support Bower. Please make sure you have configured for version 3 if you are still using Bower.
