### ISSUE TITLE
add pagination + sortable to dataTable

### ISSUE THREAD

**Issue by tttp** [dc-js/dc.js#1465]
as per: https://tttp.eu
https://github.com/TechToThePeople/mep/blob/master/index.html#L494
Rationale: using an existing library (datatable is awesome) means that you duplicate a lof of the features from crossfilter that is pretty good at filtering and sorting... and that you have to draw the full table with dc, initialise the pagination/sort library (datatable) that will hide all the rows but the first page...
it is paintfully slow if you have more than a few k's of rows

**Comment by tttp** [comment]
@gordonwoodhull could you assign to me?

**Comment by gordonwoodhull** [comment]
I still disagree with duplicating so much existing functionality. See https://github.com/dc-js/dc.js/issues/1391#issuecomment-403646776

I'd prefer to see if there is a way to avoid the performance problems of datatables.js

 e.g.
https://datatables.net/examples/data_sources/js_array

**Comment by tttp** [comment]
On the other hand, the datatable duplicates a lot more functionality from crossfilter than adding pagination (that is already in dc) and filtering on headers

But I see your point, and it's quite easy to keep the filtering + pagination outside of dc, let's close and if someone wants to copy paste, let's keep https://github.com/TechToThePeople/mep/blob/master/index.html#L494 as a ref and close the issue
