### ISSUE TITLE
Sunburst : filtered elements should be animated

### ISSUE THREAD

**Issue by Frozenlock** [dc-js/dc.js#1467]
Filtered elements instantaneously disappear without animation.

See the [Sunburst example](https://dc-js.github.io/dc.js/examples/sunburst-cat.html).

Without animation, it's not immediately clear what is being removed from the chart.

The pie chart calls `dc.transition` which is missing for the sunburst chart.
Could it be as simple as that?

Pie chart : https://github.com/dc-js/dc.js/blob/develop/src/pie-chart.js#L124
Sunburst : https://github.com/dc-js/dc.js/blob/develop/src/sunburst-chart.js#L128

**Comment by ialarmedalien** [comment]
There are various bugs in the code that are stopping the transitions from being performed—the main problem is that the existing code talks about `x`, `dx`, `y`, and `dy`, which are from the d3 v3 era, but v4/v5 uses `x0`, `x1`, `y0`, and `y1`. I am working on a branch that fixes those errors and adds some new functionality to the sunburst chart.

**Comment by gordonwoodhull** [comment]
Thanks @ialarmedalien! 

Please let us know how it goes. Even a partial solution would be a big help.

**Comment by Frozenlock** [comment]
Appears to be fixed in the last version.
Thank you very much!

**Comment by gordonwoodhull** [comment]
Yes @ialarmedalien fixed it in #1481 for 3.0.7
