### ISSUE TITLE
controlsUseVisibility documentation is incorrect in Getting Started guide

### ISSUE THREAD

**Issue by ialarmedalien** [dc-js/dc.js#1474]
An easy documentation fix I spotted...

According to the [dc.js Getting Started guide](http://dc-js.github.io/dc.js/docs/stock.html#section-9):

> `dc.js` >=`2.1` uses `visibility: hidden` to hide/show controls without disrupting the layout. To return the old `display: none` behavior, set `chart.controlsUseVisibility(false)` and use that style instead. 

However, the API docs and the dc behaviour is the opposite: the default is to use `display: none` and `chart.controlsUseVisibility` has to be set to `true` to trigger the behaviour. Suggest changing the docs to

> By default, `dc.js` uses `display: none` to control whether or not chart controls are displayed. To use `visibility: hidden` to hide/show controls without disrupting the layout, set `chart.controlsUseVisibility(true)`.

**Comment by gordonwoodhull** [comment]
Thanks! I think I originally thought I would just change the behavior, then went back and made it backward-compatible instead. But I forgot I had documented it in the Getting Started guide.

**Comment by gordonwoodhull** [comment]
Thanks @ialarmedalien! fixed via #1475 in 3.0.7.
