### ISSUE TITLE
sunburst: ordering not working

### ISSUE THREAD

**Issue by tttp** [dc-js/dc.js#1480]
Hi,

I've been trying to change the order on a sunburst.  The goal is to set the order on the first level based on the position of the key in a ref array (eg ["for","against","abstention"]

I'm not super sure what is supposed to be the format, but no matter what I tried:

    return [  ref.indexOf(d.key[0]),d.key[1] ]
    return ref.indexOf(d.key[0])

it doesn't change the order. I did check that indexOf is properly set (it is). Am I missing something or is this a missing feature? I'm not sure I understand how the hierarchy code works or how it should use ordering

**Comment by tttp** [comment]
Yeah, talking about flexibility: Its likely that the 1st and 2nd rings would be sorted differently... Let me hack what I need and I'll come back to the issue to discuss how it could be done more generically ;)

**Comment by alexnb** [comment]
@gordonwoodhull 
Hello Gordon, we have a requirement to sort segments of sunburst descending by value, like it is done here: https://observablehq.com/@d3/sunburst?collection=@d3/d3-hierarchy , for every ring.

We know that a full fledged sorting interface is planned in #1161 but it sounds like a long way. Would it be possible to implement the proposal of @ialarmedalien for sunburst to make its behaviour consistent with the other charts of dc.js?

We'll provide a PR with tests :)

**Comment by gordonwoodhull** [comment]
Hi @alexnb!

#1161 actually isn't all that complicated but I overexplained it. 😏 Now we are using built-in sort, so we could expose a predicate, #1658.

The same predicate could be used with `partition.sort` as suggested by @ialarmedalien. This would not satisfy @tttp's idea of sorting rings differently, but it would be a simple way forward.

**Comment by gordonwoodhull** [comment]
And of course it would be simpler just to use `ordering` here, exactly as proposed by @ialarmedalien. I would accept a PR in either direction.

**Comment by the3ver** [comment]
Hi @gordonwoodhull,

#1659 is an attempt to implement @ialarmedalien 's suggestion in 3.x. One issue might be that before, the capMixin set the ordering to sort by -value and I overrode that by setting ordering to the default function from baseMixin. The tests are all green but this potentially breaks sunbursts that use the capped functionality. On the other hand it seems capped sunbursts did not work anyway if I interpret #1573 correctly.

**Comment by gordonwoodhull** [comment]
Fixed by #1659. 

Right, capping doesn't work correctly in sunburst charts, so it's okay to change the behavior.
