### ISSUE TITLE
How to access bar value when user clicks

### ISSUE THREAD

**Issue by Dhevendhirancs** [dc-js/dc.js#1483]
I need to initiate a function when the user clicks the particular bar in a bar chart. There is some code to interact with multiple charts. But I cannot access the bar value outside the dc function, even I cannot see the value inside. So, is there any other way to access the bar value when user clicking and use it outside of the dc function?

**Comment by tttp** [comment]
Hi,

Could you use SO for questions rather creating an issue here?

In general, the strategy to interact with the data (for instance to display a tooltip on a mouse over) is to call a function after the graph is drawn ( graph.on("renderlet", function(){ ...)
and within that function d3.selectAll("rect or whatever the graph draws).on("click",function(d) {... use the data linked to the object

**Comment by gordonwoodhull** [comment]
I started to answer your question on the users  group but just saw this - yes @tttp has exactly the right idea. 

Please follow up your question on the users  group if this is still not clear. It's possible even if you don't have access to any of the chart code.
