### ISSUE TITLE
Truncating long category axis labels with ellipsis

### ISSUE THREAD

**Issue by RamanDhoot** [dc-js/dc.js#1486]
Hello, I was trying Bar chart Its plotting perfectly, but x-axis labels are name of approx 120 characters long so it is overlapping next label.
I have also tried to rotate it Now the space is allowing to show around 70 characters but others are hidden.
Do we have any idea to Truncating long category axis labels with ellipsis.

**Comment by gordonwoodhull** [comment]
Hi @RamanDhoot! I think the best way to go about this is to change the axis' [tick format](https://github.com/d3/d3-axis/blob/master/README.md#axis_tickFormat).

You supply a function which takes the key and returns a string value. So you could do something like

```js
chart.xAxis().tickFormat(d => d.slice(0,67) + '...')
```

or whatever you like. (I am assuming that your chart has an ordinal domain and the keys are strings - they will be other types for other scales.)

Note that you should [typically only modify `.xAxis()` on its own source line](https://github.com/dc-js/dc.js/wiki/FAQ#why-does-everything-break-after-a-call-to-xaxis-or-yaxis).

Let us know if you run into any trouble with this approach. It would be nice to include rotated labels in the library, or at least an example (#778).
