### ISSUE TITLE
dc fails to roll up

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1489]
@AdamCottrill [asked on SO](https://stackoverflow.com/questions/52672184/how-to-bundle-dc-js-plot-with-rollup):
> I'm working on an application that uses d3 to create some interactive maps and have successfully used rollup to bundle the javascript. I have used dc.js in the past, and wanted to incorporate a bunch of dc.js plots into the application. However I have been unable to figure out how to get dc.js to work with rollup. It is mentioned in some discussions in the dc.js issue tracker (#1175) , so I'm pretty sure it can be done. I'm hoping someone can point out my mistake.

> I have create a minimal example that demonstrates the issue(s) using a single, simple dc.barChart modified from here: dc Bar Chart Example. When I call rollup -c, bundle.js is created but:

> 1.   a warning that "dc.barChart is not exported by node_modules\dc\dc.js" and

> 2.   when the html page loads, the figure does not appear and the console says: "Uncaught TypeError: Cannot add property box, object is not extensible". "box" appears to be referring to d3.box, but I have no idea why.

> Here is my minimal index.html:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>dc.js Rollup</title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/dc/3.0.7/dc.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.css" />
    </head>
    <body>

        <div id="container" class="container" >
            <h3>A dc.js bar graph:</h3>
            <div id="test"></div>
            <p>modified from <a href="https://dc-js.github.io/dc.js/examples/bar.html">this example</a>.</p>
        </div>

        <script type="text/javascript" src="bundle.js"></script>


    </body>
</html>
```

> Here is main.js:
```js
import * as d3  from 'd3';
import crossfilter from 'crossfilter2';
import * as dc from 'dc';


let chart = dc.barChart('#test');

d3.csv('morley.csv').then(function(experiments) {
  experiments.forEach(function(x) {
    x.Speed = +x.Speed;
  });

  let ndx  = crossfilter(experiments);
  let runDimension = ndx.dimension(function(d) {return +d.Run;});
  let speedSumGroup = runDimension
      .group().reduceSum(function(d)
                         {return d.Speed * d.Run / 1000;});

  chart
    .width(768)
    .height(480)
    .x(d3.scaleLinear().domain([6,20]))
    .brushOn(false)
    .yAxisLabel('This is the Y Axis!')
    .dimension(runDimension)
    .group(speedSumGroup)
    .on('renderlet', function(chart) {
      chart.selectAll('rect').on('click', function(d) {
        console.log('click!', d);
      });
    });

  chart.render();

});
```
> and finally here is rollup.config.js:

```js
function onwarn (warning, warn) {
  if (warning.code === 'CIRCULAR_DEPENDENCY') return;
  warn(warning);
}


export default {
  input: 'main.js',

  output: {
    name: 'dcjs_rollup',
    file: 'bundle.js',
    format: 'iife',
    sourceMap: true,
    globals: {
      'd3': 'd3',
      'dc': 'dc',
      'crossfilter2': 'crossfilter'
    }

  },
  onwarn: onwarn,
  plugins: [
    resolve({
      jsnext: true,
      main: true,
      browser: true
    }),
    sourcemaps(),
    json(),
    commonjs(),
    globals(),

  ]
};
```

> I'm hoping that I am missing something simple in my configuration file or just need to include another plugin, but I am completely out of ideas.

> Any suggestions?

**Comment by gordonwoodhull** [comment]
We don't yet support rollup - we have the idea to split up dc the way that d3 was, but this is a ton of work and hasn't happened.

Fixing this issue will be a good start. There is no reason we need to modify `d3.box` in order to provide box plots - that came up here because this code was originally from the d3-plugins library. I don't know if this will be the only issue, but let's start here!

**Comment by gordonwoodhull** [comment]
Hi @AdamCottrill, I'm trying to repro right now. 

I have used rollup for some basic use cases but I am basically new to transpilation.

In case you are online atm, is there more configuration needed in order to get this rollup configuration to work? First I ran into `ReferenceError: resolve is not defined` so I added rollup-plugin-node-resolve as a devDependency and added 

```js
import resolve from 'rollup-plugin-node-resolve';
```
to rollup.config.js. 

Apparently you didn't need to do this, but also it still complains about `sourcemaps()`, and I bet it will not like `json()`, `commonjs()`, or `globals()` either.

Are you using another level of tooling on top of rollup?

Here is my start of a project to test this configuration: https://github.com/dc-js/dc-rollup

**Comment by gordonwoodhull** [comment]
Hmm, if I remove those from rollup.config.js, I get an error in processing crossfilter2:

```
$ rollup -c rollup.config.js main.js

main.js → bundle.js...
[!] Error: 'default' is not exported by node_modules/crossfilter2/index.js
```

Clearly I am missing some tooling, and you got further than me. Any clues?

**Comment by gordonwoodhull** [comment]
Okay, I was able to add most of the plugins and dependencies, except commonjs which failed with this obscure error:

```
[!] (commonjs plugin) TypeError: parse is not a function in /Users/gordon/src/dc-rollup/main.js
main.js
TypeError: parse is not a function in /Users/gordon/src/dc-rollup/main.js
    at error (/usr/local/lib/node_modules/rollup/dist/rollup.js:175:14)
    at Promise.resolve.then.catch.err (/usr/local/lib/node_modules/rollup/dist/rollup.js:18045:6)
    at <anonymous>
```

Not surprising, it didn't help with the crossfilter2 error. Although the [hint URL in the error](https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module) seems to imply that the commonjs plugin might help? I am semi-lost.

**Comment by AdamCottrill** [comment]
Hi Gordon.  I can't access my minimal example right now.  I will look at it tonight and see if I have additional dependencies that I failed to capture.  I started out with a larger configuration file that included things like babel and uglify. I sequentially removed those from the config file until I that what I thought was a minimal working example that still had the problems. It is possible that something wasn't completely removed from my environment.

Regrettably,  I am new to rollup (and far from a js ninja).  This is my first attempt at using rollup.  It was pretty slick when it worked, but now that it doesn't I'm completely lost.  

Adam

**Comment by AdamCottrill** [comment]
I just noticed that the listing of rollup.config.js above is missing the import statements from the top of the file:

    import  resolve  from 'rollup-plugin-node-resolve';
    import  globals  from 'rollup-plugin-node-globals';
    import commonjs from 'rollup-plugin-commonjs';
    import json from 'rollup-plugin-json';
    import sourcemaps from 'rollup-plugin-sourcemaps';

These lines are in the rollup.config file of your git repo, so I doubt this has anything to do with the issues you are having.  Thought I should mention it just in case someone is copy-and-pasting from the post above.

**Comment by gordonwoodhull** [comment]
Thanks @AdamCottrill! I bet we will get there if we keep plugging away at it. Glad to hear that the imports were necessary.

I got a little further by following the advice in https://github.com/ng-packagr/ng-packagr/issues/657. By backing out to rollup-plugin-commonjs 8.3, I got past the "parse is not a function" error, and crossfilter2 seems to be imported correctly.

Then I got `Unknown option found: sourceMap`, so I commented that out.

Now I'm getting

```
barChart is not exported by node_modules/dc/dc.js
```

which is odd - I *think* rollup should be able to detect classic `dc.barChart = function (...) { ... }` declarations.

I think we have now reached the same stage. It seems likely that different versions of rollup or its plugins might account for the different errors we are getting.

To solve the initial problem you raised, you may be able to change `d3.box` to `dc.d3box` in the two places it occurs (`src/d3.box.js` and `src/box-plot.js`). But I'd really like to be able to test this myself. (Even better if we could automate the testing of build frameworks somehow, hmmm..)

**Comment by AdamCottrill** [comment]
Hi Gordon,

As you suspected,changing d3.box to dc.d3box in those two locations and rebuilding dc.js with grunt appears to have solved the first issue.  The error "Cannot add property box, object is not extensible" disappears but is has been replaced by another.  Now the error is "Uncaught TypeError: undefined is not a function"  which corresponds to this line in my version of bundle.js:

    let chart = undefined('#test');

which is the transpiled version of line 7 from main.js:

    let chart = dc.barChart('#test');

so this is clearly associated with the warning from rollup that barChart is not exported from dc.js, or isn't being detected by rollup. 

For completeness, here is the package.json file from my minimal test case:

    {
      "name": "rollup_dcjs",
      "version": "0.0.0",
      "description": "A minimal example to test rolling up dc.js.",
      "main": "index.js",
      "scripts": {
        "dev": "rollup -c --watch",
        "reload": "live-server --wait=500",
        "watch": "npm-run-all --parallel reload dev",
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "me",
      "license": "ISC",
      "devDependencies": {
        "live-server": "^1.2.0",
        "rollup": "^0.66.4",
        "rollup-plugin-commonjs": "^9.1.8",
        "rollup-plugin-node-globals": "^1.4.0",
        "rollup-plugin-node-resolve": "^3.4.0",
        "rollup-plugin-json": "^3.1.0",
        "rollup-plugin-sourcemaps": "^0.4.2"
      },
      "dependencies": {
        "crossfilter2": "^1.4.6",
        "d3": "^5.7.0",
        "dc": "^3.0.7"
      }
    }

There are some slight differences in versions that may explain different errors and configuration options (e.g. SourceMap).

**Comment by gordonwoodhull** [comment]
dc.js is an AMD module. This is an old way to define modules before the language had features for this.

Looks like perhaps it needs to be converted to ES6 in order to work with rollup. This plugin could help: 

https://www.npmjs.com/package/rollup-plugin-amd

Then again, there is no guarantee that any of this will work, since rollup is intended for genuine ES6 modules.

**Comment by gordonwoodhull** [comment]
Yeah, I dunno, adding this plugin causes ordinary d3 modules to fail. I think somehow it would have to be configured only to transform dc.js itself (and crossfilter) and not further dependencies.

```
$ rollup -c rollup.config.js main.js 

main.js → bundle.js...
[!] (amd plugin) TypeError: Cannot read property 'type' of undefined
node_modules/d3-color/src/color.js
TypeError: Cannot read property 'type' of undefined
    at error (/usr/local/lib/node_modules/rollup/dist/rollup.js:175:14)
    at Object.error (/usr/local/lib/node_modules/rollup/dist/rollup.js:18000:6)
    at promise.then.previous (/usr/local/lib/node_modules/rollup/dist/rollup.js:18009:32)
    at <anonymous>
```

Sorry, I think this is a lost cause. My hunch is that it would either take a lot of rollup configuring, or dc.js would have to be translated to ES6 module(s). The huge effort described in #1175 is breaking dc.js up into dozens of little modules; perhaps it won't be so hard to just make it one big module (and rely on tree-shaking for any savings).

If anyone wants to give this another shot, [here is the repo](https://github.com/dc-js/dc-rollup)

**Comment by gordonwoodhull** [comment]
dc@4 uses ES6 modules and rollup
