### ISSUE TITLE
Sunburst : doesn't recenter when redrawn

### ISSUE THREAD

**Issue by Frozenlock** [dc-js/dc.js#1490]
### Behavior

Expected : the sunburst chart should recenter itself like the pie-chart when redrawn width different width/height.

Actual : the sunburst chart doesn't move.

### Potential cause
The sunburst chart doesn't have a cx/cy based transition in the `drawChart` function like the pie-chart does.
Pie chart : https://github.com/dc-js/dc.js/blob/develop/src/pie-chart.js#L124
Sunburst chart : https://github.com/dc-js/dc.js/blob/develop/src/sunburst-chart.js#L94

**Comment by gordonwoodhull** [comment]
Hi @Frozenlock, would you care to give this a try and see if the proposed fix works?

I believe you are correct about what this line does.

**Comment by gordonwoodhull** [comment]
We also require a test - we need to make a new [resizing example](https://dc-js.github.io/dc.js/resizing/). I can handle that if you care to contribute the fix.

**Comment by Frozenlock** [comment]
I'll let you handle the resizing example.
I don't program in JS... simply read it once in a while.
