### ISSUE TITLE
stacked rowChart doesn't use label, always displays the key

### ISSUE THREAD

**Issue by tttp** [dc-js/dc.js#1495]
Hi,

I'm using a composed key [country, region], but want to only display the region name as the label of the bar chart.

I've tried

     chart.label(function(d) { return d.key[1]; });

but it doesn't change (chart.legend works fine)
it works fine with keyAccessor (function(d) { return d.key[1]; })... but obviously doesn't properly filter the other graphs

Am I missing something?

**Comment by gordonwoodhull** [comment]
Yeah, the label for the bar chart is used for displaying text above the bars. (This is inconsistent between charts.)

A clue here is that (in most cases) the axes in dc.js are straight from d3.

You want to use [axis.tickFormat](https://github.com/d3/d3-axis/blob/master/README.md#user-content-axis_tickFormat). Something like this should work:

```js
chart
  .xAxis().tickFormat(function(d) { return d[1]; });
```

lmk if probs!
