### ISSUE TITLE
dataCount takes a crossfilter as its dimension

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1499]
Continuing the tradition of misnaming methods (#855), you need to pass a crossfilter object as the dimension to the `dataCount` widget.

C'mon, really? Why? Are we deliberately trying to trip people up?

**Comment by kum-deepak** [comment]
I did get tripped over it during my effort to split crossfilter into an interface (as part of my effort to create remote data providers).

**Comment by gordonwoodhull** [comment]
Hi @kum-deepak! I started a library for wrapping what's needed by dc.js of the crossfilter interface here:

https://github.com/att/xfilter

So far it supports Nanocubes and a simple restful server as backends.

It could be improved a lot but maybe it will provide you some ideas.

**Comment by kum-deepak** [comment]
Actually my code would have reached very similar to this project. Many thanks!

Quite timely for me.

**Comment by gordonwoodhull** [comment]
A way forward for these places where a method is reused in an incompatible way:
1. Change `mandatoryAttributes` for these classes so that the problematic properties are not required.
2. Implement a new property with a more appropriate name. (I guess `crossfilter` here, and perhaps also `groupAll` instead of `group`... neither of those is entirely satisfactory but they would be more clear.)
3. Deprecate the existing property with a warning that the property name is misleading, and forward the setter to the new property.
