### ISSUE TITLE
polyfill missing stuff for IE

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1507]
dc.js 3.* still supports IE, sad as it is.

D3v5 introduced a couple of ES6 library dependencies, Fetch and Promise. We should include polyfills on all our pages so that they still work in IE.

**Comment by gordonwoodhull** [comment]
They are easy to polyfill; just grab [whatwg-fetch](https://github.com/github/fetch) and [promise-polyfill](https://github.com/taylorhakes/promise-polyfill) from NPM, and include the libraries in your page before the use of [d3.fetch](https://github.com/d3/d3-fetch).

I tried this on the main page and IE works again. I'm now looking into how to conveniently add it to all the pages (or at least those that use Fetch). I guess none of our tests use `d3.csv` or `d3.json` or we would have noticed this earlier.

Thanks @sgavathe for [the report](https://github.com/dc-js/dc.js/issues/1391#issuecomment-444947374)!

**Comment by sgavathe** [comment]
@gordonwoodhull Thanks for giving a solution to it! The polyfill fixes for IE does makes sense.

**Comment by gordonwoodhull** [comment]
Fixed all examples in dc.js; will now proceed to https://github.com/dc-js/dc.datatables.js/issues/7

**Comment by gordonwoodhull** [comment]
There are a few remaining arrow functions and `Object.assign` - following up with a few more commits here.

**Comment by gordonwoodhull** [comment]
boxplot and sunburst examples now work - the `Object.assign` polyfill is built-in and the `Array.find` polyfill is pasted into the relevant examples. All examples are tested to work.
