### ISSUE TITLE
move to eslint

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1508]
JSCS was merged into ESLint a couple of years ago, and then hit [end of life](https://eslint.org/blog/2016/07/jscs-end-of-life).

Although it's still working for us, it's a source of security warnings from NPM because it uses an old lodash etc. Probably ESLint has some nice newer features which will be handy. And we could probably get rid of JSHint, making our linting faster.

**Comment by gordonwoodhull** [comment]
Migrating jshint is a little easier. I tried [eslint-rules-mapper](https://github.com/vs-archive/eslint-rules-mapper) and it produced a much larger .eslintrc, and 918 errors. However, all of them were due to the migration tool adding rules we don't want.

**Comment by gordonwoodhull** [comment]
For now I'm adding .eslintrc.jscs and .eslintrc.jshint to develop, to be merged later.

Mostly I couldn't figure out how to use [grunt-eslint](https://www.npmjs.com/package/grunt-eslint) correctly - even though it clearly is reading my .eslintrc, it reports a whole bunch of new errors.

Here is how I attempted to change Gruntfile.js:

```diff
diff --git a/Gruntfile.js b/Gruntfile.js
index d3d220f0..0b5ac66e 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -82,7 +82,7 @@ module.exports = function (grunt) {
                 }
             }
         },
-        jscs: {
+        eslint: {
             source: {
                 src: [
                     '<%= conf.src %>/**/*.js',
@@ -91,9 +91,9 @@ module.exports = function (grunt) {
                     'Gruntfile.js',
                     'grunt/*.js',
                     '<%= conf.web %>/stock.js'],
-                options: {
-                    config: '.jscsrc'
-                }
+            },
+            options: {
+                configFile: '.eslintrc'
             }
         },
```

**Comment by gordonwoodhull** [comment]
Aha, polyjuice can also convert .jshintrc, so we now have a decent start at .eslintrc

Also, it looks like the extra errors when running in grunt are simply because we also check `spec/`, which used to have looser rules - how did we do that?

**Comment by kum-deepak** [comment]
If nothing else works, we can switch to what Angular does - use two different configs

**Comment by kum-deepak** [comment]
You have excellent memory of all issues 😄

**Comment by gordonwoodhull** [comment]
Haha, I've just gotten really good at searching the repo, and the unkindly-named `git blame`, which is a great history tool. Amazing how much I have learned (and forgotten) maintaining this library. :wink:

**Comment by gordonwoodhull** [comment]
It turns out the specs simply override rules using comment directives - so instead of jshint/jscs overrides, there are a few less eslint overrides now.
