### ISSUE TITLE
the way we save the stack in errors defeats the stack

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1521]
I did this in bbee2c435:

https://github.com/dc-js/dc.js/blob/81082815b830ffc442fc8b57cc2cc7085db7da63/src/errors.js#L11

I presume it helped in some old browser, but now it replaces the usual stack with a stringy stack that doesn't work well in debuggers.

**Comment by gordonwoodhull** [comment]
I'm not even seeing an error in the browser console in Firefox, so I wonder if throwing objects derived from Error is a good idea.

**Comment by gordonwoodhull** [comment]
There are no try-catch blocks in the code at all, so for better or worse, removing the classes would only potentially affect clients of the library.

A brief search across repos on github did not reveal anyone using `InvalidStateException` but I guess the rest should be searched too... if that's the right approach. Maybe it's possible to fix the current derivation.

**Comment by kum-deepak** [comment]
It has already been updated. This issue can be closed.

**Comment by gordonwoodhull** [comment]
fixed in #1548
