### ISSUE TITLE
jsFiddle and bl.ock templates not operational, dc.js cannot get loaded

### ISSUE THREAD

**Issue by joergplewe** [dc-js/dc.js#1539]
Cannot load jsFiddle and bl.ock templates due to missing dc.js:

> Request URL: https://unpkg.com/dc@3/dc.js
> Request Method: GET
> Status Code: 500 
> Remote Address: 104.16.124.175:443

The answer is: 
> Found. Redirecting to /dc@3.1.0/dc.js

Does not redirect but responds with 500. This resource pointed to is available.

Presumably not a dc.js issue, just want to raise hand there is something not right.

**Comment by gordonwoodhull** [comment]
Thanks for the report @joergplewe.

Are you still seeing this issue? I'm not able to repro. Maybe it is some kind of transient problems with unpkg.com? HTTP error 500 indicates an [internal server error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500).

unpkg.com does strongly depend on redirects. These examples point to the major version only (eg `dc@3`); unpkg.com will redirect to the current minor version that matches.

**Comment by joergplewe** [comment]
Yep, seemed to be a temporary error, works again.

**Comment by gordonwoodhull** [comment]
Awesome! Thanks for following up.
