### ISSUE TITLE
ES6 - uglify fails with generated rollup output

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1541]
Currently uglify step has been commented out from Grunt tasks. Ref #1520

**Comment by gordonwoodhull** [comment]
[grunt-contrib-uglify-es](https://www.npmjs.com/package/grunt-contrib-uglify-es) may be the solution here.

**Comment by kum-deepak** [comment]
Thanks @gordonwoodhull, works via commit https://github.com/dc-js/dc.js/pull/1540/commits/72276c5a86c24ded2b1260f868cc4d3e0819bcaf
