### ISSUE TITLE
ES6 - updaing version from package.json

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1542]
Ref #1520 

Earlier the concat grunt task was placing the version number. Current thinking to factor only version to a file (module) of its own and only pass that through grunt processor.

**Comment by gordonwoodhull** [comment]
So the module would be generated from package.json instead? Sounds reasonable.

**Comment by kum-deepak** [comment]
I was thinking of one template file and use grunt to generate the actual version.js

**Comment by kum-deepak** [comment]
Currently, also, it is generated from package.json.

**Comment by kum-deepak** [comment]
Please check commit https://github.com/dc-js/dc.js/pull/1540/commits/d635e49984222902dc6927ac41df38ab321c1c72, close the task if you are happy with the approach.

**Comment by gordonwoodhull** [comment]
There may be a simpler way to do this (poke around and see how D3 uses rollup for this), but I'm cool with this for now. Thanks!
