### ISSUE TITLE
ES6 - eslint configuration changes

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1544]
With code shifting to ES6, does eslint configuration need updating?

**Comment by kum-deepak** [comment]
Currently linter fails. @gordonwoodhull, if you have updated config please let me know.

**Comment by gordonwoodhull** [comment]
The big one is to tell eslint to use ES6:

```json
  "parserOptions": {
    "ecmaVersion": 6
  },
```

I'm sure other options/rules will need to change too.

**Comment by kum-deepak** [comment]
Basic setup completed via commit https://github.com/dc-js/dc.js/pull/1540/commits/74a9dfd429a462937f29f71f36001ac6ddefcb85

The updated setup complained about some indentation issues, those were corrected and now it is lint clear.

We can close the task now and create a new one later in the conversion process.

**Comment by gordonwoodhull** [comment]
Thanks @kum-deepak!
