### ISSUE TITLE
use specific D3 ES6 modules?

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1545]
Instead of `import * as d3 from 'd3';` we can import the specific D3 functions and/or modules we are using. 

This ought to cut down bundle sizes. It's a big task though!

**Comment by gordonwoodhull** [comment]
This also means instead of depending on the d3 package, we'd depend on submodules we actually use, like d3-scale, d3-axis, etc. 

This would allow us to target the components that will be in D3v6 before D3v6 is actually released.

**Comment by kum-deepak** [comment]
Yes, it indeed should be to the roadmap to ES6.

**Comment by kum-deepak** [comment]
As preparation `utils.add` and `utils.subtract` need to be updated to not use `d3[funcName]` to call a function. I will create a separate PR for this.

**Comment by gordonwoodhull** [comment]
The latest d3-selection and d3-transition have not landed yet, but we could try the `two` branch for those ones.

No word yet if/when D3 will do a release candidate - see d3/d3#3333. That would be a little easier than pulling individual dependencies (although we may still want to do that since it's lighter weight).

I hope that the choice between the d3 bundle and the individual modules doesn't cause another split in our build artifacts - that might be one reason to choose one or the other. My guess is that UMD would stay on the bundle and ESM/ESF would go to specific modules, but I'm not sure about that.

**Comment by kum-deepak** [comment]
I am planning to experiment. I am unable to get my head around (without actually writing code) how to tell the build system that in some cases dependencies will come from `d3` while in other from smaller modules.

**Comment by gordonwoodhull** [comment]
Yeah I don’t see it either. Each source file needs to import from particular modules, either `d3` or `d3-stuff`... seems like we’d have to abandon UMD if we went this route.

I’d love to be proven wrong.

**Comment by gordonwoodhull** [comment]
More precisely, we would force our users to use the unbundled D3 modules rather than d3.js.

All of the unbundled D3 modules are available in UMD form, so UMD would be okay.

The interfaces would get complicated because the `d3` dependency would go away and the third line in `dc.js` would resemble

```js
define.amd ? define(['d3-selection','d3-transition',...], factory`
```

and the body would be like 

```js
}(this, (function (exports, d3selection, d3transition, ...) { 'use strict';
```

It would mean a lot more HTML `<script>` includes for folks who are not bundling their sites, potentially slower if the connection is not HTTP2.

I think it's probably worth it so that people can optimize their builds and we can go ahead and start pulling in D3 6.0 modules, just want to think it through.

**Comment by kum-deepak** [comment]
I have been reading the rollup documentation and plugin system. It has quite a lot of goodies.

It should be possible that in our sources we use specific imports, but for some of the release versions we can rewrite it to d3.

I am currently modifying the stocks sample to use different models - a rollup generated bundle, directly module  etc. I will publish these as an experimental PR for our discussion.

**Comment by gordonwoodhull** [comment]
Oh cool, yeah it makes sense that Rollup should be able to do that.

Eager to see how each configuration looks. For sure we should have an example of each on github.io.

**Comment by kum-deepak** [comment]
Currently working on creating examples outside the main repo. I wanted to test how does it work when including `dc` as a npm package and then trying to use it in different modes.

Just finished one of those - using `dc` esm split modules with rollup to bundle everything (including d3 and crossfiler).

I will update details later today.

**Comment by kum-deepak** [comment]
Close by #1616
