### ISSUE TITLE
4 simple date tests fail on Linux

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1547]
I'm sure I've run the tests on my Linux laptop before, but this is likely just a local problem.

The tests are all run in UTC so it's probably not a timezone problem. The same tests fail on both Chromium and Firefox.

```
Firefox 64.0.0 (Ubuntu 0.0.0) dc.barChart rendering filtering should set filter text after slice selection FAILED
	Expected '[05/31/2012 -> 06/29/2012]' to be '[06/01/2012 -> 06/30/2012]'.
	@spec/bar-chart-spec.js:750:60
.....
Firefox 64.0.0 (Ubuntu 0.0.0) dc utils dc.printer.filter print date string FAILED
	Expected '01/31/2012' to equal '02/01/2012'.
	@spec/utils-spec.js:29:51
..
Firefox 64.0.0 (Ubuntu 0.0.0) dc utils dc.printer.filter print date range FAILED
	Expected '[01/31/2012 -> 02/14/2012]' to equal '[02/01/2012 -> 02/15/2012]'.
	@spec/utils-spec.js:38:76
Firefox 64.0.0 (Ubuntu 0.0.0) dc utils dc.printer.filter print single element array FAILED
	Expected '01/31/2012' to equal '02/01/2012'.
	@spec/utils-spec.js:41:53
................................
Firefox 64.0.0 (Ubuntu 0.0.0): Executed 1295 of 1295 (4 FAILED) (19.731 secs / 18.645 secs)
```

These tests are not much more than "construct date, print date"... really weird. I think there would be more failures if it's ignoring UTC or something.

**Comment by gordonwoodhull** [comment]
I'm seeing the same tests [fail](https://travis-ci.org/dc-js/dc.js/jobs/570788986) on Firefox/Linux via SauceLabs .(but not in either browser in the direct Travis tests). I can't think how the switch to Rollup could have triggered this

**Comment by kum-deepak** [comment]
One thing I observed that Firefox on SauceLabs seems to be quite old (v45).

**Comment by gordonwoodhull** [comment]
`grunt ci` was running on Firefox 64. 

I just thought to try the browsers.  It also fails on Firefox Developer Edition v69.0b12 and Chromium 73.0.3683.86

**Comment by gordonwoodhull** [comment]
But yes, we should also update the SauceLabs browsers at some point. There's no reason to run on old browsers except for IE (and we will stop supporting that with this release).

**Comment by kum-deepak** [comment]
It is definitely puzzling.

**Comment by gordonwoodhull** [comment]
The fact that it's reproducible in a browser should make it pretty easy to troubleshoot.

**Comment by kum-deepak** [comment]
For info - I am developing on Linux (Ubuntu 18.04). I have been regularly running `grunt ci` and it succeeds.

**Comment by gordonwoodhull** [comment]
You might not see these problems because you are 5.5 hours ahead of UTC (I'm guessing :). I'm currently 4 hours behind UTC, so a date like 2012/2/1 becomes 2012/1/31 (8pm)

It's probably this line:

https://github.com/dc-js/dc.js/blob/3396eea50ba7cdbca4babaef25f74740a45cab6f/spec/utils-spec.js#L23

As you said, we can't just set things on `dc` anymore, right? Is there a way to turn these into errors? Since there are quite a few things which currently have to be customized by overwriting members of dc (and some classes unfortunately).

**Comment by gordonwoodhull** [comment]
More precisely, it's here:

https://github.com/dc-js/dc.js/blob/3992570efdd7d387702d8e1030cdd064efbf108b/src/utils.js#L111-L115

```diff
-        s = dc.dateFormat(filter);
+        s = dateFormat(filter);
```
from 15eab3b16a473fbb52e66988e6af6137c6641102

It's the nature of modules that our exports might get overwritten but that won't overwrite the original variable. (This export is `const` so I wish there were an error too.)

So it's an instance of #1543.

**Comment by kum-deepak** [comment]
Good, cause is known now :+1:, should get covered during refactoring.

**Comment by kum-deepak** [comment]
#1553 has one approach to fix it. Please review.

I have a hunch that there are more test cases that rely on this setting. However, currently those work because of side effect of these tests (these tests do not reset this setting). I will run a check.

**Comment by kum-deepak** [comment]
Can we close this issue?

**Comment by gordonwoodhull** [comment]
Yes, thanks @kum-deepak!
