### ISSUE TITLE
drop D3 v4

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1550]
We are still repeating the tests on D3 4.* and 5.*, however dc.js 4.0 will support D3 6.0 only.

That hasn't been released yet, but we could drop D3 4 now.

We could also target the packages that will be in D3 6.0, even though it hasn't been released, via #1545 specific dependencies.

**Comment by kum-deepak** [comment]
I am planning to carry this out during conversion to ES6 classes.

**Comment by gordonwoodhull** [comment]
Fixed in #1552
