### ISSUE TITLE
Cleanup Gruntfile

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1556]
It seems `jasmine` task is no longer used (superseded by karma tasks).

Earlier list of jsfiles had ordering constraint needing it to be maintained manually. No longer needed.

**Comment by gordonwoodhull** [comment]
I still use `grunt jasmine` for testing stuff in the browser - it generates HTML with whatever tests you want.

Is there a better way to run tests using an interactive debugger? I like to set a breakpoint on the test that is failing and inspect what's going on.

**Comment by kum-deepak** [comment]
That is useful. Only cleaned up the js files list. #1557 

It might be possible to use Karma to launch a browser and then run debug in the browser - Angular projects do that. Maybe for later :smile:

**Comment by kum-deepak** [comment]
Closing this as there is no more cleanup targeted as of now.
