### ISSUE TITLE
Should crossfilter.quicksort be replaced by Array.sort

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1559]
It seems `crossfilter.quicksort` is the only function used by dc itself from `crossfilter`. If this can be replaced by `Array.sort` (or something similar), `crossfilter` can become a dev dependency.

**Comment by gordonwoodhull** [comment]
Yes, in fact we recently had a discussion about this on the crossfilter repo. 

It shouldn't be using a hand rolled sort either: crossfilter/crossfilter#1559

**Comment by gordonwoodhull** [comment]
Let's do this in 3.1.x as well as 4.0. I can backport if you fix it in the es6 branch.

**Comment by kum-deepak** [comment]
I have created a pull request. The change should work without ES6 as well.

**Comment by gordonwoodhull** [comment]
fixed by #1560
