### ISSUE TITLE
Change mixins back to bases?

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1563]
The "mixins" aren't truly mixins as they can't be mixed and matched. Really they are base classes in a class hierarchy: they depend on having certain bases present, and call methods on those bases.

The only trouble with changing this straight into ES6 classes with `extend` is that there is multiple inheritance.

I documented the class hierarchy, slightly simplified, [on the landing page of the documentation](https://dc-js.github.io/dc.js/docs/html/).

For example, the margin "mixin" is actually a base of the coordinate grid "mixin" because the coordinate grid mixin uses `.margins()` all over the place. There isn't any practical reason why you would want to substitute a different implementation of `.margins()`, and the public interface for the charts doesn't let you change the mixins, so calling it a mixin instead of a base just makes things more confusing.

It would be possible to get rid of the big clump of the multiple inheritance, the classes derived from the margin, color, and cap mixins, by using single inheritance: really all 6 of those derived classes use the color mixin, so the color mixin could be a base of the margin and cap mixins. (This doesn't make any logical sense but it works.)

However, it's not obvious how to deal with the multiple inheritance in the bubble chart, since the bubble mixin derives from the color mixin, but the bubble chart derives from the coordinate grid mixin. 

In the ES6 branch, @kum-deepak's has a clever approach of representing the old "mixins" as functions which take a base class. This nicely simulates the old behavior where each mixin extended an object given it. That's a great approach for now, but since we are moving to ES6 classes which have "real" inheritance, we might consider cleaning this up.

**Comment by kum-deepak** [comment]
Closing, no additional action now.
