### ISSUE TITLE
Question: capped accessors

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1566]
Is there any known case of a chart that uses capped mixin to use the original (i.e., non capped) accessors?

**Comment by gordonwoodhull** [comment]
I doubt it - if so it would have to be one of the base classes; row and pie do not.

The strategy is: 
- replace the data with capped data 
- the "others" bin has a special format with multiple keys 
- now the charts need a special accessor to deal with the nonstandard data format 

It is possible that users use the plain accessors. If so they would need some other workaround (or they are not showing "others").

Are you thinking of using a straight override here? If so, note that of course users do need to *set* the plain accessors.

**Comment by kum-deepak** [comment]
That makes sense :+1: Let me think if it can be improved.

**Comment by kum-deepak** [comment]
Closing for now, no action.
