### ISSUE TITLE
Using localhost URL in README

### ISSUE THREAD

**Issue by skarmaniolos** [dc-js/dc.js#1569]
In the README file between lines **`100-102`** the links provided for screenshots uses **`localhost`**.

```
* Jasmine specs are hosted at http://localhost:8888/spec
* The stock example is at http://localhost:8888/web
* More examples are at http://localhost:8888/web/examples
```

**Comment by gordonwoodhull** [comment]
Yes, that section describes the development environment, where you would run a server locally to test your changes to the code.

I'll close this, but I'm glad to reopen if there is a problem or something to clarify in the docs.
