### ISSUE TITLE
defaultColorAccessor in colorMixin

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1570]
The method `defaultColorAccessor` is undocumented and not called from anywhere (src/spec) backed by `_defaultAccessor`.

Any idea where it is used?

Removing does not impact test cases.

**Comment by gordonwoodhull** [comment]
It looks like it is supposed to tell you if the color accessor is the default or not, but it doesn't show up in `src/`, `web/`, or `spec/`, so it's unused by us.

Running `git blame src/color-mixin.js` turns up commit 824b139c2, which was a large refactor, and it was already unused in the initial commit.

I doubt anyone ever used it, but the new ES6 design exposes private members, so someone could check `chart.colorAccessor() === chart._colorAccessor` if they really needed to. Let's remove it.

**Comment by kum-deepak** [comment]
Fixed by https://github.com/dc-js/dc.js/pull/1561/commits/902634fdc525c5d5a1cd6d2ac6be509626006ed4
