### ISSUE TITLE
Canvas scatterplot DC V3

### ISSUE THREAD

**Issue by icoert** [dc-js/dc.js#1571]
I like the idea of using a scatterplot with larger datasets, but the performance is affected and that's why a canvas scatterplot is necessary. This issue was disscused [before](https://github.com/dc-js/dc.js/pull/1361). For now, the implementetion of canvas scatterplot works only with DC V2, which uses D3 V3. I would really like to port it to DC V3 with D3 V5. Any help?

**Comment by gordonwoodhull** [comment]
Ok I ported the PR and released 3.1.3

Here are the new examples:

[scatter canvas brushing](http://dc-js.github.io/dc.js/examples/scatter-canvas-brushing.html) 

[scatter canvas large](http://dc-js.github.io/dc.js/examples/scatter-canvas-large.html)
