### ISSUE TITLE
Cap by size, order by alphabet

### ISSUE THREAD

**Issue by Thimbleby** [dc-js/dc.js#1574]
I am posting here, following the direction to do so on https://dc-js.github.io/dc.js/docs/html/dc.capMixin.html. I did try to check that someone else hadn't already done so, but my apologies if I missed it. 

I would like to cap my pie chart to around 5 countries. 
About 80-90% of my data is UK based, but the data has a very long tail.
I would like the data to cap to ~5 segments according to the number of data points (or size of segment), but order them alphabetically. 

As it is currently, if I try to cap it to 5 and order alphabetically, I get a tiny sliver consisting of null values with countries like Australia, Argentina, etc... then a massive 'other' category, which includes the UK.

**Comment by gordonwoodhull** [comment]
Well, this is unpleasant and I'm not sure if it's what I was thinking when I wrote that comment in the documentation.

But you can replace the `.data()` function with your own implementation that first sorts and caps the data using the defaults, then sorts the results again before adding the Others category. (I'm guessing you still want Others at the end.

Here is the relevant code in the cap mixin:

https://github.com/dc-js/dc.js/blob/e48b9d2fca14e67df218e134e7116dedc54f3fa2/src/cap-mixin.js#L53-L76

We just replace any references to private members with calls to public getters, and then sort by the key after capping:

```js
  chart.data(function(group) {
    var items = group.all(), rest;
    items = chart._computeOrderedGroups(items); // sort by baseMixin.ordering

    if (chart.cap()) {
      if (chart.takeFront()) {
        rest = items.slice(chart.cap());
        items = items.slice(0, chart.cap());
      } else {
        var start = Math.max(0, items.length - chart.cap());
        rest = items.slice(0, start);
        items = items.slice(start);
      }
    }
    items.sort((a,b) => d3.ascending(a.key, b.key));
    if (chart.othersGrouper()) {
      return chart.othersGrouper()(items, rest);
    }
    return items;

  })
```

This proves that the `.data()` / `.cap()` / `.othersGrouper()` design is flexible and customizable, but it's too bad this requires copying so much code out of the library.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1366709/64875204-980d1a00-d61a-11e9-8d2f-a0b7bb3e6e4c.png">

[Demo fiddle](https://jsfiddle.net/gordonwoodhull/hewtumq5/18/).

I'm open to suggestions on how to make this use case easier! If we don't come up with anything better, I'll create an example out of this fiddle and link to it in the documentation.

**Comment by gordonwoodhull** [comment]
I am more and more convinced that this is what I was thinking when I put that note in the docs. 

It's a sizeable chunk of code but it allows maximum customization, and most of the complication is to do with `takeFront` 

@Thimbleby, did it work for you? Waiting for your confirmation before I create an example out of this and update the docs.

**Comment by Thimbleby** [comment]
Hi Gordon - Thank you very much for this!

Sorry I've been so tardy about replying - a deadline got sprang on me for tomorrow, so I've not had a chance to try applying it yet - instead I've been working out how to allow users to sort dcjs datatables, and make them more interactive. Hopefully I will have time on Wednesday. Sorry!

**Comment by gordonwoodhull** [comment]
No rush!

Yes, the built in datatable is pretty barebones. I usually recommend [dc-tableview](https://github.com/karenpommeroy/dc-tableview) or [dc.datatables.js](https://github.com/dc-js/dc.datatables.js) for interactive tables. 

It does add the weight of of the DataTables dependency, however. 

Folks recommend [this tutorial and code](https://www.intothevoid.io/data-visualization/sortable-table-dc-js/) by @HamsterHuey. @tttp also has (some good stuff here](https://www.tttp.eu/?)

**Comment by gordonwoodhull** [comment]
OK, I'll ping you again now... @Thimbleby, did you end up using this? Did it work for you?

**Comment by Thimbleby** [comment]
Appologies for the delay. 

I'm afraid it doesn't work. The code runs fine. However the end result just shows the first X alphabetically, and lumps everything else into 'others', even if larger than one of the first 5 by alphabetical order.

**Comment by Thimbleby** [comment]
Your fiddle seems to work though. Problem is clearly at my end.
