### ISSUE TITLE
eliminate and ignore more artifacts

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1579]
Artifacts go into dist/ now, and we ignore them for npm.

We could also `.gitignore` this directory, and I think we could also ignore a lot of `web/`

We could probably have done this in the past but since we were checking in the root-level artifacts it wasn't as noticeable.

**Comment by kum-deepak** [comment]
I was thinking of rearranging docs/web in such a way to keep source and final layout (current web) in separate folders. This way we can totally ignore the output folder.

Let me know if it makes sense?

**Comment by gordonwoodhull** [comment]
I like it. Most if not all of `web/js` could be copied from `node_modules`. (We'd need to make sure the build fails if anything is missing.)

I'd want to keep all URLs for pages the same, so as not to break links. Another constraint is that a lot of people use github.io as a CDN (despite being told not to). I don't want to break a lot of old demos.

This means that all the key js and css assets should stay at the same URLs. 

Here is the github.io documentation for redirects:
https://help.github.com/en/articles/redirects-on-github-pages

Since it relies on Jekyll for the destination page it does not look like we can redirect assets. We would have to redirect pages manually (using an HTML stub at the old URL).

**Comment by kum-deepak** [comment]
Jekyll generates an html file with meta refresh in the head, which causes the redirect. If needed these files can be hand generated.

Once the new structure is finalized, either we can copy the critical assets in original paths or generate redirect files (same way as Jekyll) would have done.

The documentation site can also move to http://dc-js.github.io/ from http://dc-js.github.io/dc.js/.

**Comment by gordonwoodhull** [comment]
Fixed by #1627 - the sources have been moved, but we still generate to the old locations.
