### ISSUE TITLE
consider codemods

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1584]
We're trying not to change the interface for DCv4, but ES6 and D3v6 will require some changes to user code.

If there are enough changes that it's worth the effort, we could consider providing a [codemod](https://github.com/facebook/codemod). For example, [d3-upgrade-codemod](https://npm.taobao.org/package/d3-upgrade-codemod) is a codemod that upgrades d3v3 code to d3v4.

It looks like the javascript part of the picture is a utility/toolkit called [jscodeshift](https://github.com/facebook/jscodeshift)

**Comment by kum-deepak** [comment]
Can this be closed?

**Comment by gordonwoodhull** [comment]
Okay. We mostly kept the interface compatible.
