### ISSUE TITLE
dc.override remaining in examples

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1592]
Ran into a crashing example by accident just now. 

```bash
$ grep override web/examples/*
web/examples/focus-dynamic-interval.html:            dc.override(chart, "yAxisMin", function() {
web/examples/stacked-bar.html:          dc.override(chart, 'legendables', function() {
```

Additionally, the removal of `dc.override` is not mentioned in the v4 upgrade guide.

We should probably run through all of examples (including transitions/resizing/zoom directories) and/or grep `web/` for the items in the upgrade guide.

**Comment by kum-deepak** [comment]
Fixed in #1600
