### ISSUE TITLE
import {version} from '../package.json'

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1594]
We were discussing how to include the version number in crossfilter, which is switching to rollup in crossfilter/crossfilter#142

I did a little searching and found this technique, which is a lot simpler than a template file, and idiomatic too:

```js
import { version } from '../package.json';
crossfilter.version = version;
```

Maybe we can do something similar, and eliminate our last use of grunt-concat.

**Comment by kum-deepak** [comment]
Let me try it.

I have a suspicion that there are some other places where it relies to grunt-concat, I will run some grep.

**Comment by christophe-g** [comment]
I should try again to avoid looking like a fool, but as I can remember browser cringe under ESM; 
```
Failed to load module script: The server responded with a non-JavaScript MIME type of "application/json". Strict MIME type checking is enforced for module scripts per HTML spec
```
https://github.com/crossfilter/crossfilter/pull/142#discussion_r335940734

**Comment by gordonwoodhull** [comment]
We started discussing how to distribute dc.js as smaller files or chunks in #1588, but TBH I haven't absorbed all the complexities yet.

However I can see why this technique wouldn't work in a raw JS file / ES6 module.

The same as with crossfilter, I think it would be okay only to include the version in the UMD bundle and omit the version from the ES6 distro. If people install dc.js from npm, they will get the whole source tree and they can consult package.json. Including the version is only relevant for the bundled file, which gets copied on its own.

**Comment by kum-deepak** [comment]
I have tested this using https://github.com/rollup/rollup-plugin-json.

I will do it after #1603 is merged (as it needs to modify rollup config).

**Comment by kum-deepak** [comment]
> We started discussing how to distribute dc.js as smaller files or chunks in #1588, but TBH I haven't absorbed all the complexities yet.
> 
> However I can see why this technique wouldn't work in a raw JS file / ES6 module.
> 
> The same as with crossfilter, I think it would be okay only to include the version in the UMD bundle and omit the version from the ES6 distro. If people install dc.js from npm, they will get the whole source tree and they can consult package.json. Including the version is only relevant for the bundled file, which gets copied on its own.

As part of #1603, I have experimented with ESM chunks. Please check.

**Comment by kum-deepak** [comment]
Fixed in https://github.com/dc-js/dc.js/pull/1603/commits/97e5d1cb8dd3543a366a06f4d4048ec071774f42.

**Comment by gordonwoodhull** [comment]
Thanks @kum-deepak!
