### ISSUE TITLE
put docs in new location

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1598]
As discussed in #1593.

I know there may be larger restructuring of the website, but in case that doesn't happen, this is just a reminder to @kum-deepak to move the docs to a new directory before release of 4.0. 

I'll handle the redirects in #1597.

**Comment by gordonwoodhull** [comment]
@kum-deepak, what are your thoughts here? #1627 did not change the documentation folder; instead we went with moving the sources and then generating to the old locations.

I am okay with generating redirects within the same folder. Should we close this as outdated?

**Comment by kum-deepak** [comment]
I think we can mark it outdated and close it. All the intents, that I had, have been fulfilled.

**Comment by gordonwoodhull** [comment]
Cool, I misunderstood. 

Moving the source of the docs and web while keeping the same URLs is a great move, thanks!
