### ISSUE TITLE
Get value of selected brush

### ISSUE THREAD

**Issue by pdaems** [dc-js/dc.js#161]
Is their a quick way to get the value of the selected brush in a barChart.

I would need the startDate & EndDate of the brush that the user selects.

**Comment by marctiedemann** [comment]
Is this feature not supported anymore? if I try to grab it via brush() on dc.barChart. I keep on getting "chart1.brush is not a function". There is also no documentation about this in the dc.js api.

**Comment by gordonwoodhull** [comment]
Hi @marctiedemann. It's definitely still supported: 
https://github.com/dc-js/dc.js/blob/develop/src/coordinate-grid-mixin.js#L941

I don't know why it's undocumented.

Perhaps you've accidentally saved a reference to something that is not a chart, for example by manipulating an axis at the end of your chart initialization? (See "Why does everything break after a call to .xAxis or .yAxis??" [in the FAQ](https://github.com/dc-js/dc.js/wiki/FAQ).)

**Comment by marctiedemann** [comment]
Ah yes, thanx I was missing that!
