### ISSUE TITLE
What does `npmFileMap` key does in package.json

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1615]
I could not locate the purpose of this key. Please help.

**Comment by gordonwoodhull** [comment]
I can't seem to find any documentation on it, but I think `npmFIleMap` specifies which files CDNJS should take. Likewise `npmName` also configures CDNJS somehow.

CDNJS [has been going through a rough patch recently](https://github.com/cdnjs/cdnjs/issues/13524) and it seems like it hasn't been updated in a while, but people still use it and in some ways it is still more reliable than unpkg.com. I think we should hold onto this config until we see what happens there.
