### ISSUE TITLE
seriesChart: More than 10 data series -> legend-graph link and color error 

### ISSUE THREAD

**Issue by m-h-t** [dc-js/dc.js#1619]
`seriesCharts` starts duplicating line colors and links a single legend element to multiple graphs when using more than 10 data series. This makes it impossible to tell which graph belongs to which data series.

## Reproduction

1. Replace the content of [`morley.csv`](https://github.com/dc-js/dc.js/blob/master/web/examples/morley.csv) with data series such as this one:
```
Expt,Run,Speed
1,7,115
1,2,342
2,10,755
2,5,132
3,10,120
3,1,120
4,2,234
4,14,432
5,5,454
5,13,185
6,14,10
6,15,55
7,2,391
7,18,91
8,3,45
8,8,248
9,3,654
9,5,232
10,8,335
10,10,87
11,3,4
11,7,123
```
2. Open the [seriesChart example](https://github.com/dc-js/dc.js/blob/master/web/examples/series.html)
3. `Expt 1` and `Expt 9` each link to both graphs and have the same color

**Comment by gordonwoodhull** [comment]
It's a known issue that the legend uses colors to match up with the items #727, which is pretty messy.

However, you should be able to supply a color scheme with more than 10 colors and avoid this, right?

https://dc-js.github.io/dc.js/docs/html/dc.colorMixin.html#ordinalColors__anchor

**Comment by m-h-t** [comment]
Hi Gordon,

sorry, I did not find this previous issue and the problem originating in the color matching was rather unexpected - first I thought my group ordering was wrong before seeing the same thing happening with the series chart example.

It works now, thanks for pointing me into the right direction!

**Comment by gordonwoodhull** [comment]
That's great! Yes it's tricky searching for old issues and I don't blame you for opening this one. I just like to keep the issues linked.

However, I will close this now as it is a duplicate, an ugly consequence of #727.
