### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1628]
Seems reasonably old now :smile:

**Comment by gordonwoodhull** [comment]
Most of it still looks correct, except for some details like what tools we use for linting.

What do you have in mind?

**Comment by kum-deepak** [comment]
Yes, only the sections towards end of the guide.

**Comment by kum-deepak** [comment]
see #1641

**Comment by kum-deepak** [comment]
Fixed by #1641
