### ISSUE TITLE
Use constructors for chart creation in tests and examples

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1629]
Need your views on this before carrying out this change.

One associated task will be to change all our examples to use constructors.

**Comment by gordonwoodhull** [comment]
I agree we should use constructors everywhere in the examples and tests.

I’m not sure if we should emit a warning when the old functions are called. Experience has shown that some people take these warnings very seriously. And I like the way that we have kept the 4.0 interface stable so far.

What are the arguments for formally deprecating and warning?

**Comment by kum-deepak** [comment]
That makes sense. I will change the issue title.

**Comment by kum-deepak** [comment]
Fixed by #1633.
