### ISSUE TITLE
when a default of a property is a method, `this` should be bound

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1638]
#1634 pointed out that it's annoying to wrap the default `capMixin.othersGrouper` because it uses `this`

The problem is endemic to the ES6 transformation. 

In DCv3, almost all of these methods referenced `_chart`, not `this`, so the user didn't have to worry about passing the chart as `this` using `.call()` or `.apply()`

All of these methods need to be identified and bound to `this` in the constructor. In a year or two they can become [class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields#Browser_compatibility) with arrow functions, to clean up the mess.

There may be exceptions. 

I will do a thorough search for uses of `this` in DCv3. I expect they will be rare and accidental - almost everything used the closure for private fields and methods.

**Comment by gordonwoodhull** [comment]
To take a simple example, in DCv3, `_defaultWidthCalc` and `_defaultHeightCalc` looked like

https://github.com/dc-js/dc.js/blob/56df1dcd3f67201b750ef989aaa1c3e15632096d/src/base-mixin.js#L23-L26
https://github.com/dc-js/dc.js/blob/56df1dcd3f67201b750ef989aaa1c3e15632096d/src/base-mixin.js#L30-L33

Now they look like

https://github.com/dc-js/dc.js/blob/3b92589c7f1492ed1cf2ad0c6f7a72462616ae15/src/base/base-mixin.js#L1417-L1425

and the members are initialized in the constructor.

It's great that we are using idiomatic ES6 classes, and they are an improvement in most ways, but here they are less convenient than the closure approach we had before.

We'll need to identify all methods affected, make sure we have plenty of tests and examples wrapping the default functions. It's kind of scary that none of the tests or examples touched on this, but it's really something that users will do when they want *almost* the default behavior.

I bet if we somehow tested over all of the DCv3 jsFiddles we would see a lot of it.

**Comment by gordonwoodhull** [comment]
Searched the DCv3 code. Indeed the only uses of `this` are for D3, or accidental (should be using `_chart`).

There is one single exception where a property is set to a function that uses `this`, but we already knew about this problematic occurrence, the `colorAccessor` of the stack mixin.

So, although it is messy, there should be no loss of functionality by binding `this` for any method which is a property value.

**Comment by gordonwoodhull** [comment]
@kum-deepak, you haven't expressed any opinion on this. Any thoughts?

Unfortunately I don't think this review can be automated (or we'd have to use esprima or something). I got through the base mixin so far. Will update when I've made more progress.

**Comment by kum-deepak** [comment]
Sorry @gordonwoodhull, was traveling last week. I will review and comment in a day :smile:

**Comment by kum-deepak** [comment]
I have gone through your comments and the code as well. It all makes sense.

My guess, if we take care of just the default values (i.e., those are properly bound), it should solve the issue.

I will make a sample commit covering one accessor.

**Comment by kum-deepak** [comment]
Please see #1639. If you like this approach, all such occurrences can be converted.

**Comment by kum-deepak** [comment]
Basically I am proposing that if something is a value that will, possibly, get assigned or queried, it should be defined as an instance variable. This approach allows us to use => function, which, also binds `this`.

**Comment by gordonwoodhull** [comment]
Great approach.

I noticed that my `_defaultWidthCalc` example is a weird one, because previously these functions were not visible (scoped private). Now they are visible and reusable, which is great &ndash; viva la leaky abstraction &ndash; but it makes this task slightly more confusing, because it's not just default accessors, it's "functions we expect users may want to wrap and pass back as accessors".

Hopefully there aren't any more cases.

**Comment by gordonwoodhull** [comment]
OK I just took a closer look.

I found that you had already naturally taken this approach in most cases because charts often ***call*** these functions without a target or explicit `this`, so they already needed it this way!

For future reference, here is the list I obtained by grepping for `param.*Function` and then reading the source. It is possible that we will find more of these in the future, but it seems that the three you fix in #1639 were the exception, because the chart was calling them via `this._member(...)`

base mixin
- `_widthCalc` / `_defaultWidthCalc` - covered by #1639
- `_heightCalc` / `_defaultHeightCalc` - ditto
- _title already follows the pattern

many bases and charts
- `_data` is often overridden in a way that already follows the pattern. (Similar to `_defaultWidthCalc`, users now have access to the default function value, which they didn't before.) 

Simple example: 
https://github.com/dc-js/dc.js/blob/907254d36fa2fea84aae5e0838b3240f3c51048c/src/charts/number-display.js#L50-L53

cap mixin - othersGrouper
color mixin 
- `_colorAccessor` already follows the pattern
- `getColor` is an especially weird case #1575

box plot
- `_boxWidth` already follows the pattern

cbox menu, select menu
- `_order` already follows the pattern

data grid
- `_htmlSection` already follows

heatmap 
- `_boxOnClick` already

scatter
- `keyAccessor`, `valueAccessor`, `colorAccessor` already protected

series
- `_keySort` already

text filter
- `_filterFunctionFactory` already follows the pattern

**Comment by kum-deepak** [comment]
My suggestion, we should discourage accessing members with name starting with _ from user code. These should be treated private and should not be part of interface stability.

**Comment by gordonwoodhull** [comment]
Fixed by #1639.

dc.js is a leaky abstraction by design, and I think it's good that the ES6 transformation has exposed more ways to customize the behavior. Personally, I won't discourage people from using those private functions. 

But you're right, they are not part of the public, documented interface, and may not be stable.
