### ISSUE TITLE
update instructions for maintainers

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1644]
Some of the steps will change with 4.0 - not checking in artifacts, etc.

Review [the wiki page](https://github.com/dc-js/dc.js/wiki/Instructions-for-Maintainers) after release, and also check other pages for conflicts.

**Comment by kum-deepak** [comment]
It might need two variants - one for fixes to v3 branch and other for v4.

**Comment by gordonwoodhull** [comment]
Hmm, yeah good point. v3 will still be maintained for some time.

Hopefully not for too long - it’s really quite difficult to port changes between the branches, basically a rewrite due to all the differences.

My feeling is to backport fixes from 4 to 3 only if there is demand.

**Comment by gordonwoodhull** [comment]
I added notes about the steps that can be skipped in v4+. Eventually the page can be cleaned up. It has a lot of general git tips which might be more confusing than helpful.
