### ISSUE TITLE
Bar chart with time scale won't change domain (v3.1.9)

### ISSUE THREAD

**Issue by nanowizard** [dc-js/dc.js#1649]
I have a dc.js bar chart with a time scale x axis with which I'm trying to change the domain to ignore some major outliers, but the chart won't accept my changes. Whenever I `render()` it just goes back to whatever the auto-detected limits are.

When I initialize it I'm doing this (Where `min` and `max` are `Date` objects):
```
chart.x(d3.scaleTime().domain([min, max]));
```
But it doesn't take my provided domain. I've even tried modifying the domain after the fact:
```
chart.x().domain([min, max]);
```
But after I do `chart.render()`, the chart appears as if I never added any domain arguments and `chart.x().domain()` returns auto-detected limits.

How do I get my domain changes to stick?

**Comment by gordonwoodhull** [comment]
Do you have `elasticX` on? 

I don’t think the chart will set the domain otherwise...

**Comment by gordonwoodhull** [comment]
I’m going to guess that the answer is “yes” and close this. Please comment if this has not resolved your issue.

**Comment by nanowizard** [comment]
Please forgive the late reply. Yes that was completely the issue (oof!). I had that in a separate part of the code and completely forgot about it.

Thank you!
