### ISSUE TITLE
sunburst: use marginMixin

### ISSUE THREAD

**Issue by the3ver** [dc-js/dc.js#1652]
Feature request: add margin support to sunburst charts.

**Comment by gordonwoodhull** [comment]
Hi @the3ver.

It may be unfortunate that the sunburst chart and pie chart have different interfaces from the rest of dc.js, but it seems to me you can already specify center ([cx and cy](https://dc-js.github.io/dc.js/docs/html/PieChart.html#cx__anchor) and [radius](https://dc-js.github.io/dc.js/docs/html/PieChart.html#radius__anchor). Isn't this equivalent?

Was there something you were not able to do with the current interface? I think it would be rather tricky to support margins on top of cx, cy, radius.

**Comment by the3ver** [comment]
Hi @gordonwoodhull,
thx, you are right, of course. I did not realize that cx/cy and radius are already in place and can achieve the same thing as setting margins.
