### ISSUE TITLE
CDNJS hyperlink in readme pointing to dc v3.2.1

### ISSUE THREAD

**Issue by benjaminh** [dc-js/dc.js#1663]
Tried to use dc (for the first time !) in a project and struggled a bit with the versions of dc, crossfilter (which is crossfilter2 if I'm right) and d3 to use (already using d3 v5 in the project).
The README instructions mentioned in the `CDN Location` section to use unpkg.com links but also specifies :
> or copy the latest links from CDNJS

Yet, the page on CDNJS only provides links for dc versions until 3.2.1. Maybe the instructions should be updated for clarity ?

**Comment by gordonwoodhull** [comment]
We are having some trouble configuring CDNJS for 4.0. Please use unpkg.com for now.

We do hope to restore CDNJS for DCv4 but it's kind of a weird manual system, and so far it is unclear to me how to tell it that the artifacts are in different places for different versions.

**Comment by gordonwoodhull** [comment]
Both DCv3 and DCv4 are compatible with D3v5, and compatible with any version of crossfilter.

**Comment by benjaminh** [comment]
> Both DCv3 and DCv4 are compatible with D3v5, and compatible with any version of crossfilter.

OK, thought that there may be some incompatibilities because :+1: 
```
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.15.0/d3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.12/crossfilter.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dc/3.2.1/dc.min.js"></script>
<script>
var surfaceChart = new dc.BarChart('#surfaceChart')
</script>
```
gives me `TypeError: dc.BarChart is not a constructor` while upgrading to dc v4 and crossfilter2 v1.5 seems to be OK with `dc.BarChart`

**Comment by gordonwoodhull** [comment]
That error has nothing to do with crossfilter. Differences between DCv3 and DCv4 are documented here:

https://github.com/dc-js/dc.js/blob/develop/docs/dc-v4-upgrade-guide.md

In particular, there were no real classes in v3 so the correct syntax was

```js
var surfaceChart = dc.barChart('#surfaceChart')
```

For compatibility, this syntax is still supported in v4.

(Yes, versions are confusing things. Not much we can do about that.)

**Comment by benjaminh** [comment]
Thank you for your explanations ! I mixed things up a little bit but will be more careful in the future. Also great work with this lib :)
