### ISSUE TITLE
Composite LineChart dc.js example ignores line colors, i.e. both in default blue

### ISSUE THREAD

**Issue by d00AK** [dc-js/dc.js#1668]
**SemVer:**
    "crossfilter2": "^1.5.2",
    "d3": "^5.15.0",
    "dc": "^4.0.3"

**Source:**
https://github.com/dc-js/dc.js/blob/master/web-src/examples/composite.html

**Issue:** all composite lines are in "blue" color (see screenshot)
However, labels and hover dots are properly colored.

**Desired state:** lines in corresponding colors

![DC js line colors bug Screenshot_20200316_001855](https://user-images.githubusercontent.com/14943835/76712768-d0052f00-671b-11ea-875c-620e043372e1.png)

**Comment by gordonwoodhull** [comment]
I don't see this on the demo page. Could it be that you have changed something in the example?

https://dc-js.github.io/dc.js/examples/composite.html

**Comment by d00AK** [comment]
Nope, the code is "as-is" from example, but rendered as sub-component in my project + webpack dc/css imports and csv-loader for morley:

```
import * as dc from 'dc'
import 'dc/dist/style/dc.css'
...

    var composite = new dc.CompositeChart('#test_composed')
    const morleyData = require('./morley.csv')
    const morley2Data = require('./morley2.csv')

    // const results = await Promise.all([d3.csv(morleyData), d3.csv(morley2Data)])
    // console.log('results', results)

    // var exp1 = results[0]
    // var exp2 = results[1]
    var exp1 = morleyData
    var exp2 = morley2Data

    var ndx = crossfilter()
   ...
```


 In that case, the reason could be some global CSS override from other parts of my project. Any ideas what global CSS setting can override/reset-to-default d3 line color?

**Comment by gordonwoodhull** [comment]
Gee, that's a pretty big change - what kind of component are you talking about, React?

The colors are not controlled by CSS, they are controlled by code. (Anything that is controlled by data is via D3 data binding not CSS.)

Sorry but I guess I would need to see a complete running example in order to diagnose what is going wrong. You do agree that the demo page works on its own, right?

**Comment by d00AK** [comment]
No React, Angular, etc. In VanillaJS. Hold on, I'll do a completely clean project to render your example. I'll write back here then.

**Comment by gordonwoodhull** [comment]
In case it's not obvious, in the example, the colors are chosen here:

```js
            new dc.LineChart(composite)
                .dimension(dim)
                .colors('red')
                .group(grp1, "Top Line")
                .dashStyle([2,2]),
            new dc.LineChart(composite)
                .dimension(dim)
                .colors('blue')
                .group(grp2, "Bottom Line")
                .dashStyle([5,5])
            ])
```

It (implicitly) creates a color scale with only one color in it. It's hard to see how the surrounding code could interfere with this (but Murphy's Law).

**Comment by d00AK** [comment]
The problem is in that the explicit colors "red" & "blue" are respected by legend and while hovering over, but ignored for line itself. Moreover, adding .renderDataPoints(true) shows data points in "red" & "blue" as expected, but the lines connecting dots in default "light blue".

**Comment by gordonwoodhull** [comment]
Sounds like you have something overriding the colors, perhaps CSS. [CSS will override attributes on the SVG objects](https://stackoverflow.com/a/36755226).

I would suggest inspecting the elements in your developer tools and see if some rule is overriding the attribute. In the raw example, I see

<img width="325" alt="image" src="https://user-images.githubusercontent.com/1366709/76762581-e802a000-6767-11ea-8e66-51df2004aef6.png">

in Chrome developer tools. I.e. `stroke: red` is "winning". I suspect that you have some unrelated CSS which overrides this.

**Comment by d00AK** [comment]
I confirm override of "red" with "steelblue". Will investigate the cause. My project has at least two SVG sources for override: font awesome icons + JSONEditor which internally uses AceEditor. 
![steelBlue Screenshot_20200316_143504](https://user-images.githubusercontent.com/14943835/76763689-e64ed180-6793-11ea-96fa-a9e2dbf870ee.png)

**Comment by gordonwoodhull** [comment]
The other view of styles, not "Computed" but "Styles" in Chrome, should show you the source of each CSS rule.

AFAIK dc.js doesn't use steelblue, so I'll close this. But feel free to continue commenting if you need more help troubleshooting this.

**Comment by d00AK** [comment]
Found the override. It came from custom d3 "horizontal stacked bar chart" code, i.e. THE feature much asked from DC.js team to implement ;) Please close this issue, and thanks for your help!
