### ISSUE TITLE
fix mixin and override documentation

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1673]
When we made the upgrade to 4.0, we removed the `dc.baseMixin()` functions, and we only support the `dc.BaseMixin` classes now. However, this was documented incorrectly in [the upgrade guide](https://github.com/dc-js/dc.js/blob/develop/docs/dc-v4-upgrade-guide.md#steps-to-upgrade).

Additionally, we did not document how to access the equivalent of `super` using a direct override. It is still possible to call the mixins' methods from an override, if a little ugly.

**Comment by kum-deepak** [comment]
Wow! Good to see it working :+1:

**Comment by gordonwoodhull** [comment]
I was gratified to see that all functionality is available to folks still using ES5 closure "classes". They can upgrade their ES at their own pace.

Good work, @kum-deepak!
