### ISSUE TITLE
Bubble chart and rowchart are not sync

### ISSUE THREAD

**Issue by shakraz** [dc-js/dc.js#1681]
Hi, thank you for this amazing library!
There is a simple bubble chart (dimension by level1, level2) and row chart(dimension by level_1)

`
  var houseDim = ndx.dimension(d=>[d.district, d.name, d.price, d.flat_rate, d.building_rate]);
  var districtDim = ndx.dimension(d=>[d.district])
`
When i click on row chart i expect to see only filtered bubbles, right? But it doesn't work. 
But it works vice versa, clicking on bubble filters rowchart, why is that? 
Thank you for any advance.

**Comment by gordonwoodhull** [comment]
Should work! I’d need to see a running example to help you figure out what went wrong. 

Make sure that [each chart has its own distinct dimension](https://github.com/crossfilter/crossfilter/wiki/Crossfilter-Gotchas#a-group-does-not-observe-its-dimensions-filters), and uses a group constructed from its own dimension.

It’s really uncommon to need so many columns in a dimension key. Remember this is just used for aggregation and filtering, any aggregated values should be specified in the group reduction functions. Normally the dimension key will be a scalar not an array for bubble and row charts.

Anyway, this sounds like a support question better suited for SO, so I’ll close this. If you really think it’s a bug in the library, feel free to leave a comment.

**Comment by shakraz** [comment]
Hi, Gordon, thank you for quick reply!
Sure, https://codepen.io/shakraz/pen/dyYXxJy, i'm not a coder, sorry for ugly code)
