### ISSUE TITLE
bar chart  Label Rotate

### ISSUE THREAD

**Issue by SathishRamV** [dc-js/dc.js#1695]
![image](https://user-images.githubusercontent.com/46240800/86278622-4e3bf300-bb9e-11ea-8d4e-7e6f3768d92c.png)

is it possible to rotate label ? like i mentioned in image

**Comment by gordonwoodhull** [comment]
It just takes some tricky CSS, see for example [this example](http://dc-js.github.io/dc.js/examples/focus-ordinal-bar.html), which roasts tick labels but it’s the same idea.

As common as it is, I still don’t think it belongs as a feature of the library - too fiddly - so I’m closing this. Please feel free to ask a question on SO or the user group if you can’t figure this out.
