### ISSUE TITLE
ScatterPlot legendables

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1701]
Following is the current code:

```javascript
    legendables () {
        return [{chart: this, name: this._groupName, color: this.getColor()}];
    }
```

`this.getColor()` expects at least one parameter. Not sure what should be the correct behavior. @gordonwoodhull any idea?

**Comment by gordonwoodhull** [comment]
[It works](http://dc-js.github.io/dc.js/examples/scatter-series.html) because it is set up to use `this._groupName`:

https://github.com/dc-js/dc.js/blob/8b8ab082a5ca1f591c60919e5568cadf5962217a/src/charts/scatter-plot.js#L45

**Comment by kum-deepak** [comment]
Wow! Could have never guessed that. :laughing: 

I will adjust the type definitions.

**Comment by kum-deepak** [comment]
I am keeping this open to remind me.

**Comment by kum-deepak** [comment]
Updated the type definitions in #1711
