### ISSUE TITLE
Composite chart issue w/ bar widths when x scale is band or ordinal

### ISSUE THREAD

**Issue by aberenyi** [dc-js/dc.js#1712]
Hi there,

This could be very well a duplicate of https://github.com/dc-js/dc.js/issues/662, however, it seems the [workaround](https://github.com/dc-js/dc.js/issues/662#issuecomment-150098091) mentioned in the original issue doesn't resolve the problem any more.

The following fiddle shows the issue in action https://jsfiddle.net/aberenyi/sp78bxgf/2/

I've marked the changes I've made, so hopefully it will be clear what I'm after - basically my main concern is the overlapping of the bars.

Cheers

**Comment by gordonwoodhull** [comment]
The coordinate grid mixin detects whether the scale is ordinal or continuous by checking [.xUnits()](https://dc-js.github.io/dc.js/docs/html/CoordinateGridMixin.html#xUnits).

If you specify

```js
      .xUnits(dc.units.ordinal)	
```

on the parent (composite) chart, this causes the charts to go into ordinal mode, and the bar widths are calculated correctly:

![screenshot with correct bar widths](https://user-images.githubusercontent.com/1366709/87727638-55aeef00-c78f-11ea-8bb0-22a2bf4531bf.png)

[Fork of your fiddle](https://jsfiddle.net/gordonwoodhull/oyp9cm3a/3/) (thanks!).
