### ISSUE TITLE
Policy discussion: do we allow conf settings with side effects

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1735]
The majority of chart properties exactly do get and set. However, there are a few properties that do additional work.

Going forward, with the new conf system, do we allow properties with side effects?

Ref #1707.

**Comment by kum-deepak** [comment]
If we allow properties with side effects we will insist that properties are always set with a call to `.configure`. This method will have specific checks and code for side effects.

If we do not allow properties with a side effect, we will decide on a case-to-case basis for the updated code. In this case, we can additionally allow setting properties by a direct assignment.

**Comment by gordonwoodhull** [comment]
I'm confused what we do with the current code that has side effects, if we decide to ban them?

**Comment by kum-deepak** [comment]
I think I can see the way forward, please see https://github.com/dc-js/dc.js/pull/1736#discussion_r471228908.
