### ISSUE TITLE
Naming of the configue method

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1742]
In reference to #1736, should we keep `configure` or shorten it to `conf`?

To me, the first one sounds better when used as a setter, and the second one as a getter. In all likelihood, it would be rare for the function to be used as a getter.

@gordonwoodhull what is your opinion?

**Comment by kum-deepak** [comment]
I am getting inclined to return `this` from `.configure(conf)` to make it chainable. The getter to be named `.conf()`.

This method will not return what was set, so, not inclined to use same method.

**Comment by gordonwoodhull** [comment]
This makes sense to me too!

**Comment by kum-deepak** [comment]
Implemented as part of #1736
