### ISSUE TITLE
Big Task: Separating data/filter concerns

### ISSUE THREAD

**Issue by kum-deepak** [dc-js/dc.js#1747]
After looking at the source code for a few years and some experiments https://github.com/dc-js/dc.js/pull/1665, I think I am ready to take a plunge. Observations so far:

- It appears that a few charts will fail to work with the non-default key accessor. In some cases, these use a d3 function to preprocess data, which generates a `.key` (like `d3.nest` used by DataGrid and DataTable).
- Cross filter requires the key as it generated for filtering to work correctly. This implies that in charts if a customed `keyAccessor` is defined, the filtering will be broken. Very few charts like `BubbleChart` uses `.key` directly to work correctly with custom `keyAccessor`.
- A simple summary - very few cases where a chart can actually work with a custom key accessor. This itself may not be a limitation all user-visible usage of the key, like labels, titles, etc., have accessors.
- `.value` is never used directly, the output of `.valueAccessor` is used instead. So, we can pre-process the data to calculate and store it.
- Some charts (like CoordinateGrid) call `.data` multiple times. The output of `.data` can be cached at the beginning of the render/redraw cycle.
- Currently, filters are stored within a chart. Storing these with the dimension will resolve quite a few issues. This will also ease the development of alternative data providers.
- Capping can be handled as pure data & filter concern (as shown in https://github.com/dc-js/dc.js/pull/1665/commits/1a63f53e5760d1b03bb3fbbcd29d8d9ce5c907dc). This will allow charts to be simpler. This also enables data providers to support capping differently. For example, a remote backend may cap and send the data.
- Filters need to be easily serializable (say to JSON) to be sent to a remote data provider.
- To show deselected items, few of the carts check if a data is filtered in or out. Currently, it is checked against current filters. Remote providers may find it easier to mark items filtered in/out.
- key, value and filtered status make sense to be pre-computed. We can make a decision for other accessors independently.
- In the case of Crossfilter, other accessors are likely to need computed key/value as well as original .key/.values from the call of group.all.

I will keep amending this for a while. Please free to raise questions/issues.

**Comment by kum-deepak** [comment]
As part of this, I am working on the first PR to make `.data()` to use inheritence instead of being a callback.

**Comment by gordonwoodhull** [comment]
Everything here is likely to cause backward-compatibility problems. I understand that you want to "clean things up" but people use dc.js in a lot of messy ways, because crossfilter doesn't provide all the functionality that is needed for all uses of the data. This is why "fake groups" are so prevalent.

Some of these use cases are covered in the examples, but many are not. To really test it we'd need to grab the corpus of examples from SO, which is a lot of work.

This is looking more and more like an incompatible fork of dc.js. That may be the right way to push things forward, but I wonder if we will end up with something that needs a new name, or at least an explicit warning that it's not an upgrade, that people will have to put in significant work if they want to use the new version.

**Comment by kum-deepak** [comment]
I think that may make sense. The current v4 is stable, feature-complete, and totally usable.

While the new version will be close (when used along with the compatibility layer) to the current v4, it will break for many.

I would be for giving it a new name. That will give us the advantage to take it to version lesser than 1, indicating that the interface is likely to change. Subsequently, at second or third release it may be numbered 1.x.

**Comment by gordonwoodhull** [comment]
We have time to think about it.

Certainly a lot of projects, like D3, make big breaking changes on a major version change. That’s what semantic versioning is for. If we are clear with users then maybe it’s okay.

I guess my greatest worry is that someone might think they “must” use the latest and greatest, only to find that it’s not possible to do something that was possible before. It may take some iterations to restore functionality that gets lost through simplification of the code base.

**Comment by kum-deepak** [comment]
I understand your concerns.

Actually, when dc 3 was released, even though the dc interface did not change, the end-user code must have needed changes because of d3 changes.

In another library I maintain, I get tickets filed against syntax that was deprecated four years ago. This happens because people occasionally use some third party tutorials written a while back. In the case of dc it is more likely to happen, as there is so many snippets available across a variety of sources. 

In similar lines, I was thinking to create a tutorial, covering proper usage - maybe a tutorial that leads to the stocks example. It should cover topics like colors, scales, ordinal charts, legends, resizing (responsive), using with React/Angular, basic usage of Cross Filter, custom reductions, etc. I do not want to go there now, but, definitely after this release.

**Comment by gordonwoodhull** [comment]
Yes, in fact the changed signature on d3 event handlers in dc@6 / dc@4.1 percolated through (as it should) and caused some breakage.

https://stackoverflow.com/q/63726858

**Comment by kum-deepak** [comment]
This task is completed across several PRs #1765, #1773, #1774 and #1779.
