### ISSUE TITLE
saucelabs not working

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1752]
All our Travis builds fail.

We could disable saucelabs, or we could try configuring it from scratch.

**Comment by kum-deepak** [comment]
With GitHub actions, we may be able to test these. Since GitHub is now Microsoft, I guess their browsers might already be supported.

**Comment by kum-deepak** [comment]
https://github.com/karma-runner/karma-edge-launcher/actions - saving this for reference (might be useful)

**Comment by kum-deepak** [comment]
A first cut approach in #1754, we can move the further discussion there.

**Comment by gordonwoodhull** [comment]
Fixed by #1754
