### ISSUE TITLE
filter stacks example has invalid segment filtering

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1787]
This example worked in dc@2 or dc@3, but currently clicking on a segment produces invalid selections with undefined in them:

<img width="933" alt="image" src="https://user-images.githubusercontent.com/1366709/99891914-11e85c80-2c3d-11eb-8c5c-6503b2631af0.png">

**Comment by kum-deepak** [comment]
This example uses good knowledge of internal field names (not part of public API). Fixed to update the field names as per internal changes. Also needed was to use d3 v6 compact for the click event handler.

This example will undergo further changes to remove all deprecated calls.

**Comment by gordonwoodhull** [comment]
I tried to cherry-pick b0be203 to develop in order to close this out, but for some reason, `adaptHandler` is not exported even though it clearly has `export` in its definition. Not sure how to troubleshoot this since rollup is a black box.

**Comment by kum-deepak** [comment]
I will look into it. The entire commit is not needed here. Also, the `adaptHandler` may be exported from the file but may not be part of the library export. I will check and fix it.

**Comment by kum-deepak** [comment]
Please see #1796.
