### ISSUE TITLE
Add example demo BI dashboard

### ISSUE THREAD

**Issue by danieloberbillig** [dc-js/dc.js#1794]
Hi, I recently created a demo BI dashboard: https://webreportingstudio.com/hub/dcjs-order/start
Please feel free to add it to the examples or use it elsewhere as a demo/showcase if you'd like.
All the best from Australia.

**Comment by gordonwoodhull** [comment]
Interesting. Does the Web Reporting Studio abstract away some of the differences between Postgres, Cube.js, and dc.js?

Please feel free to add it to the [Community examples in the wiki](https://github.com/dc-js/dc.js/wiki#community-examples).

**Comment by danieloberbillig** [comment]
Thank you, Gordon. I added the link to the wiki. The website is not yet a product but just showcases different approaches of data viz - including dc.js. 
Cheers
