### ISSUE TITLE
ScatterPlot - x axis on top

### ISSUE THREAD

**Issue by aberenyi** [dc-js/dc.js#1815]
Hi there,

I've tried to implement a workaround based on this similar issue https://github.com/dc-js/dc.js/issues/1433 for the [scatter series example](https://dc-js.github.io/dc.js/examples/scatter-series.html) ([fiddle](https://jsfiddle.net/aberenyi/42qwe0yh/)).

It looks like the initial position of the axis is fine, but then it's overwritten resulting in an animated movement.

Something like the [`useRightYAxis`](https://github.com/dc-js/dc.js/blob/master/docs/api-latest.md#coordinategridmixinuserightyaxisuserightyaxis--boolean--coordinategridmixin) for the x axis would be really useful, e.g `useTopXAxis`, but a workaound would also do for now.

Cheers

**Comment by gordonwoodhull** [comment]
Good idea. I think it would be fairly easy to add `useTopXAxis` to `CoordinateGridMixin` - just search for `useRightYAxis` and make the corresponding changes for the X axis. It's only used in four methods, one of them the getter/setter.

It is technically possible to add event handlers on both pretransition and renderlet as a way to override both initial and animated position. But it's probably easier just to add the functionality instead.

I'd be glad to help if you want to give it a try!

**Comment by aberenyi** [comment]
@gordonwoodhull sound like a plan!

Will give this a go ASAP and will get back to you.
