### ISSUE TITLE
"bar colors" example from docs is missing source code ?

### ISSUE THREAD

**Issue by NgyAnthony** [dc-js/dc.js#1817]
Hi, it seems like the bar chart with colors example on https://dc-js.github.io/dc.js/examples/bar-colors.html is missing the source file. It redirects to https://github.com/dc-js/dc.js/tree/develop/web-src/examples/bar-colors.html which is empty.

There also doesn't seem to be a bar-colors HTML file in /examples.

**Comment by gordonwoodhull** [comment]
Hmm, I didn't mean to check this in, as I was just testing something in response to an issue.

However, if it's useful, I'll add it in 4.2.5
