### ISSUE TITLE
How to create new chart using HTMLelement ?

### ISSUE THREAD

**Issue by Madasamy26** [dc-js/dc.js#1820]
I am trying to create new chart with typescript like below

let chart = new barChart("#id");

But I want to create a new chart using HTMLElement node 
let chart = new barChart(node);

But in barChart type restricts the HTMLElement !!!

How to do that?

**Comment by kum-deepak** [comment]
Internally the charts use d3 selection. If it is a string, it is passed to `d3.select`, if not it is assumed to be d3 selection. So, you should try the following:

```javascript
let chart = new barChart(d3.3select(node));
```
