### ISSUE TITLE
Missing css file in the Github repo

### ISSUE THREAD

**Issue by CHEN7YU** [dc-js/dc.js#1832]
In the source of example (https://dc-js.github.io/dc.js/examples/download-table.html).
The HTML is linked with below css file.

`    <link rel="stylesheet" type="text/css" href="../css/dc.css" />
    <link type="text/css" rel="stylesheet" href="../css/dc-floatleft.css" />
`

But when navigate to the ../css folder, I am not able to find the dc.css and dc-floatleft.css files.
Can you please upload those 2 files? thanks

**Comment by kum-deepak** [comment]
Please pick it from https://dc-js.github.io/dc.js/css/dc.css and https://dc-js.github.io/dc.js/css/dc-floatleft.css. These files are there even though if you try to navigate to https://dc-js.github.io/dc.js/css/ you would get a 404.
