### ISSUE TITLE
remove d3v5 compatibility layer

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#1846]
I'm glad that we took a conservative approach for adding d3v6 compatibility, with the compatibility layer.

However, having this extra level makes the code hard to read - I was just trying to read how data table sections work, and it's confusing having also to read compat/d3v6.js in order to understand it.

I think we should remove d3v5 compatibility for dc-v5.

**Comment by kum-deepak** [comment]
Thanks for raising this. I see one more reason: it will fundamentally fix https://github.com/dc-js/dc.js/issues/1822.

Modules support in the browsers is improving, and we should make dc to work as modules directly in the browser.

**Comment by kum-deepak** [comment]
closed by #1847
