### ISSUE TITLE
Does it support faceted graphics?

### ISSUE THREAD

**Issue by bigfacewo** [dc-js/dc.js#1877]
Does it support faceted graphics?
Like tableau, it supports infinite nested faceted graphics.

![image](https://user-images.githubusercontent.com/31603897/215380990-7f1e0b45-6181-4a1e-affc-bc43ef5b7d35.png)

**Comment by gordonwoodhull** [comment]
No, dc.js will not generate the facets for you. You would generate your charts in a loop.

Some examples that do this:
* [align axes](https://dc-js.github.io/dc.js/examples/align-axes.html)
* [compare unfiltered](https://dc-js.github.io/dc.js/examples/compare-unfiltered.html)
* [splom](https://dc-js.github.io/dc.js/examples/splom.html)
