### ISSUE TITLE
Simple way to color bar chart

### ISSUE THREAD

**Issue by textplusdata** [dc-js/dc.js#200]
Hi.
I'm trying to color a stacked bar chart, and I've looked at some other complicated solutions, but I need something simple!

I am trying this which seems to be a hotch-potch of code. I've tried the selectAll with about every combination: rect.bar, rect.stack, g.rect.bar etc.

```
.renderlet(function(chart){
       chart.selectAll("g.rect.stack").attr("fill", function(d){
            if(d.key == "a) Free")   
         return "green-bar";
    else if(d.key == "b) Partly Free")
         return "yellow-bar";
     else if(d.key == "c) Not Free")
         return "red-bar"; 
        });})
```

Anyone help me get over this?

**Comment by claud-alex** [comment]
In case anyone still runs into something like this, Nick's solution works fine for me but only operating on the chart selection with "style" rather than "attr", i.e. ```chart.selectAll("g.rect.stack").style("fill", ``` etc.
   No idea why, but it solved issue for me.

**Comment by ozermm** [comment]
Thank you @rajeshr6r for this great contribution. For some reason, it did not work for me. Do you have a working example? Thanks.

**Comment by rajeshr6r** [comment]
Hi

I do Hv one . Will share as soon as I get to my laptop . I'm hoping you are us dc 2.0

**Comment by gordonwoodhull** [comment]
Note there are also a couple of PRs for grouped bar charts, if that's the intended purpose. Would appreciate some reviews of them. #1043 #984

**Comment by ozermm** [comment]
Thank you @gordonwoodhull!

**Comment by ozermm** [comment]
Hi again Rajesh,

I will be very happy if you can share you working bar chart example.

Thanks,

Murat

**Comment by nitinsurana** [comment]
The `renderlet` solution doesn't seem to work for me. Tried with both `.attr` & `.style`. 
I'm using `dc 2.0.0-beta.30`

**Comment by nitinsurana** [comment]
The below works instead :
```
chart.selectAll("g rect").style("fill", function (d) {
  if (d.layer === "Advanced")
   return "green";  //return "#898989";
```

**Comment by nitinsurana** [comment]
`renderlet` solution creates a flickering effect. Is there any way to use `colorAccessor` to set the color ?

**Comment by gordonwoodhull** [comment]
Use pretransition instead of renderlet to avoid the flicker.

**Comment by nitinsurana** [comment]
Thanks @gordonwoodhull , works like a charm.

Anyone looking, here's the no flickering solution with bar color, legend color on `pretransition`.

```
.on('pretransition', function (chart) {
                    chart.selectAll("g rect").style("fill", function (d) {
                        return colorMap[d.layer];
                    });
                    chart.selectAll('g.dc-legend-item rect').style('fill', function (d) {
                        return colorMap[d.name];
                    });
                });
```

**Comment by nitinsurana** [comment]
Oops, with `pretransition` - the filtering doesn't dim all the other unselected bars.

**Comment by nitinsurana** [comment]
Here's the solution for filtering not dimming the stackedbars.
```
chart.selectAll("g rect").style("fill", function (d) {
                        return colorMap[d.layer];
                    });
                    chart.selectAll('g.dc-legend-item rect').style('fill', function (d) {
                        return colorMap[d.name];
                    });
                    chart.selectAll("g rect.deselected").style("fill", function (d) {
                        return '#ccc';
                    });
```

**Comment by rassemdev** [comment]
@nitinsurana what is chart.selectAll('g.dc-legend-item rect') for?
