### ISSUE TITLE
Add Axis Padding for Coordinate Grid Chart

### ISSUE THREAD

**Issue by jrideout** [dc-js/dc.js#229]
In the barChart, using CenterBar it will clip the leftmost bar

Example (look at A):

![screen shot 2013-07-26 at 3 30 54 pm](https://f.cloud.github.com/assets/197338/864822/1bcda544-f62a-11e2-8576-86eddd170e6c.png)

We can fix this padding for the a axis

**Comment by chinna-clustrex** [comment]
hey...to use 
 .outerPadding(1.0)
