### ISSUE TITLE
Ability to sort and limit number of items in row chart

### ISSUE THREAD

**Issue by bskelton** [dc-js/dc.js#237]
Similar to data table size() method. This would be helpful for situations where the height of the chart is set, but the number of data items is unknown.

**Comment by JackStouffer** [comment]
I would like to point out to the project maintainers that none of the methods listed are in the API documentation.

**Comment by gordonwoodhull** [comment]
@JackStouffer, you probably just have to look at the parent "mixins", mostly the cap mixin:

https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#cap-mixin

**Comment by JackStouffer** [comment]
Ah, sorry I was looking in the wrong place!

**Comment by akuji1993** [comment]
@adg29 I get .rowsCap() is not a function when trying to use it. Do you have a pointer for me?

**Comment by gordonwoodhull** [comment]
@akuji1993 not sure how that could happen. Are you using dc.js 2.0? Looks like the function has been available since at least 1.6.

**Comment by akuji1993** [comment]
Importing dc via npm, using version: "^2.0.0-beta.33". I could only cap the rows by filtering my dimensions. I'm sure, I do something wrong, but it should be called like this right: 

```
import * as dc from 'dc'; 
...
chart = dc.barChart(myHook); 
chart.margins(...).width(...).height(...) // and so on. 
chart.rowsCap(14); --> rowsCap is not a function. 

```

Do I have to manually import the mixins as well or is it something else?

**Comment by gordonwoodhull** [comment]
Oh. That's a bar chart not a row chart. Unfortunately the bar chart does not support capping, see #609. It's a pretty simple transformation of the data and it could probably be added with a [take group](https://github.com/dc-js/dc.js/wiki/FAQ#fake-groups).

**Comment by akuji1993** [comment]
See, I knew it would be something I'm not aware of. Thank you for the explanation, though, I guess I can stop trying to get the method to work then. 
I'm doing exactly that, extracting a fake group, instead of the complete group to my graph. For anyone wandering into this thread at a later time, here it is: 

`var chart = dc.barChart(this.hook);
    let _x = this._x;
    let _y = this._y;

    var ndx = this.chartGroup.getCrossfilter();

    var dimension = ndx.dimension(function(d) {
      return d[_x];
    });


    var group = dimension.group().reduceSum(function(d) {return d[_y];});
    const getTops = (source_group) => {
      return {
        all: function () {
          return source_group.top(50);
        }
      };
    };
    var fakeGroup = getTops(group);
    let groupSize = this.getGroupSize(fakeGroup, _y); 

    let minimum = group.top(groupSize)[groupSize-1].value;`

The Function call getGroupSize gives you this: 

`return group.all().filter(function(d) { return d[value] !== 0; }).length;`

**Comment by gordonwoodhull** [comment]
Yeah the only thing the capped mixin will give you over what you're doing is the ability to group the remaining unshown bars into an "others group". If you don't need that then your approach is simpler.

**Comment by akuji1993** [comment]
Okay, no, then I don't really need it. We have about 1000 product categories, and only the top 50 need to be shown. If you would group all the others to one, it would be the biggest bar of them all. 

Thank you for your help.

**Comment by amirroaster** [comment]
For using rowsCap(), you should use it separately.
`permitReasonChart
            .margins({top: 20, left: 10, right: 10, bottom: 20})
            .width(500)
            .height(800)
            .dimension(permitReasonDim1)
            .group(permitReasonGroup1)
            .label(function (d) {
              return d.key;
            })
            .title(function (d) {
              return d.key + ": " + d.value;
            })
            .elasticX(true)
            .xAxis()
            .ticks(4);
            
          permitReasonChart.rowsCap(10);

          permitReasonChart.on('filtered', function(chart, filter) {
            var CSSs = chart.filterPrinter()(chart.filters());
            if(undoFlag === false) {
              actionFunction(chart, CSSs);
            }
          });`

**Comment by amirroaster** [comment]
For using rowCap(), you should use it separately.

`permitReasonChart
            .margins({top: 20, left: 10, right: 10, bottom: 20})
            .width(500)
            .height(800)
            .dimension(permitReasonDim1)
            .group(permitReasonGroup1)
            .label(function (d) {
              return d.key;
            })
            .title(function (d) {
              return d.key + ": " + d.value;
            })
            .elasticX(true)
            .xAxis()
            .ticks(4);`

`permitReasonChart.rowsCap(10);`

`permitReasonChart.on('filtered', function(chart, filter) {
            var CSSs = chart.filterPrinter()(chart.filters());
            if(undoFlag === false) {
              actionFunction(chart, CSSs);
            }`
