### ISSUE TITLE
Brush range on page load

### ISSUE THREAD

**Issue by strangeapparition** [dc-js/dc.js#249]
Is there a way to set a specified range for the brushes to cover on page load?

Right now I have 4 bar charts that all react to one another but it defaults to having all the data selected on page load. Ideally I'd like to have no data selected until the user drags across a chart to filter. But at least, is there a way to control the start and end of each chart's brush? I've looked at d3's brush.extent and I'm not sure how it would apply in this case.

**Comment by KatiRG** [comment]
For barChart, you can use:

`.filter([0,10])`
