### ISSUE TITLE
BarChart Date xAxis Bar Width

### ISSUE THREAD

**Issue by aaronhoffman** [dc-js/dc.js#293]
The bar width is always set to 1 when the BarChart's xAxis/Dimension is a date value.

**Comment by rassemdev** [comment]
Alot of thing changed, Is there any update about fixing the bar width?

**Comment by gordonwoodhull** [comment]
Hi @rassemdev, what issue are you asking about?

As explained above, the issue of bar width 1 is something that happens when `xUnits` is not configured correctly.
