### ISSUE TITLE
how to get just the filtered records?

### ISSUE THREAD

**Issue by jdarling** [dc-js/dc.js#343]
I haven't got around to the line chart thing yet as I'm busy trying to figure this out and a few other things first.

What I want to do is after the user has filtered by clicking on different parts of the report screen then allow them to view/download only the records that fit the filtered view.  I've tried creating a new dimension and group then extracting it using group.all() but that still gives me everything from the original filter.  Any ideas?

I do have a groupAll() but that only returns a count, granted the count is correct :)

Basic code follows (may have some typo's as I'm not copy/pasting):

``` javascript
var downloadData = function(collection){
  var d = ndx.dimension(function(d){return d.pin[0];}), g = d.group();
  var url = '/api/v1/export?collection='+collection;
  var records = g.all();
  var i, l=records.length;
  for(i=0; i<l; i++){
    url += '&filter[pin][$in][]='+records[i].key;
  }
  g.dispose();
  d.dispose();
  window.location = url;
}
```

As I said no matter what I do, I see all the records from the original filter applied via crossfilter.  I'm guessing there is a private filtered recordset some place, but I haven't been able to find it yet :(

**Comment by ubershmekel** [comment]
Googling brought me here and it was hard to find the answer there. Here's how to pull out a filtered record:

    dimension.top(1)
