### ISSUE TITLE
Filter data in DataTables and Redraw all charts

### ISSUE THREAD

**Issue by zhx828** [dc-js/dc.js#420]
Hi,

Is there anyone know how to filter data in DataTables and Redraw all charts? I combined the dataTable in dc.js and the DataTables(http://datatables.net) by adding $("dataTable").dataTable and dc.dataTable("#dataTable") at same time. Right now, it's able to redraw the data table based on the clicks of each charts. But is there anyway to do the reverse? 

Peter

**Comment by jsmedmar** [comment]
@zhx828 could you provide and example on how you achieve this? would be much appreciated.
