### ISSUE TITLE
stacked bar chart

### ISSUE THREAD

**Issue by aritra16** [dc-js/dc.js#423]
Hi,
   First of all I would like to thank everyone for providing us with such a wonderful js library. Currently I'm working on creating a stacked bar chart and I'm facing a slight problem in the sense that suppose I have a data like the one below. 

```
 Market     Product_Type        Sales
```

---

```
  West        Espresso          120
  West        Tea               100
  West        Coffee            85
 Central          Espresso          250
 Central          Espresso          750
 Central          Tea               100
 Central          Coffee            120
  East        Espresso          120
  East        Tea               650
  East        Tea               350
  East        Coffee            560
```

Now I want to create a stacked bar chart where the x-axis will contain the market area(i.e. East,West,Central) and the y-axis will contain sales. The stacked bar chart will be based on creating a group for each product_type(i.e. Tea,Expresso and Coffee) for each market area. For example, if I want to create a stacked bar chart out of the above data, the x-axis of the chart must consist of three bars (viz West,Central and East) and each bar will be stacked with the sum of each product types for each market area. Also the number of product type may vary at runtime. 
    I've created bar charts and stacked bar charts before but that was with a single column as dimension say market or say product type. But with 2 columns coming into the picture and with the use case mentioned above, I'm unable to solve the problem. Could anyone help me out with this problem?
 Thanks all.

**Comment by Hirajis** [comment]
@aritra16 @jrideout Hey Dear, Do you have running example URL for above case because above URL is not working

**Comment by Hirajis** [comment]
Thanks, @jrideout this helps me a lot to create a stacked bar chart 
Here is the workable link http://jsfiddle.net/myrsq3Ly/
