### ISSUE TITLE
cap and ordering sort function clarification

### ISSUE THREAD

**Issue by jeffsteinmetz** [dc-js/dc.js#468]
Wondering about the artifact of using .cap and ordering by "undefined" as shown in the following:
see jsfiddle:
http://jsfiddle.net/jeffsteinmetz/aZyQ8/

ordering by (d.key) makes sense, in this case, it orders by name (alphabetical)
ordering by (d.value) orders by the total count of each grouped item (ascending)
I was playing around with the ordering, and wanted to start the ordering out with descending group values (those with the most counts in first bar, or first wedge in pie chart, second greatest in second bar or pie wedge, etc.).

So, my intuition was to sort by negative d.value (-1* d.value)
Turns out, any undefined sort function will give me the result I wanted. I walked through the source code for .ordering() and wasn't sure why an undefined function would give me the sort I wanted. Does crossfilter by default sort groups in descending order?

**Comment by gordonwoodhull** [comment]
Hmm, sorry we left this open for so long, thanks for finally closing it. I think the answer is "yes".

`group.top()` does by default sort by descending value. It gets more confusing because dc.js does its own sorting on top of that.
