### ISSUE TITLE
Use more efficient crossfilter range/value filters

### ISSUE THREAD

**Issue by mtraynham** [dc-js/dc.js#478]
Even though Crossfilter does give us the dimension.filterFunction capabilities, the code should still try and use dimension.filter whenever possible.  In the case of brush ranges, crossfilter can use it's bisect function (which binary searches the values) and processes add/remove on portions of the index, rather than the whole index.

Adding the filters.length === 1 conditional to dc.baseMixin's _filterHandler would work accordingly:

```
    var _filterHandler = function (dimension, filters) {
        dimension.filter(null);

        if (filters.length === 0)
            dimension.filter(null);
        else if (filters.length === 1)
            dimension.filter(filters[0]);
        else
            dimension.filterFunction(function (d) {
                for(var i = 0; i < filters.length; i++) {
                    var filter = filters[i];
                    if (filter.isFiltered && filter.isFiltered(d)) {
                        return true;
                    } else if (filter == d) {
                        return true;
                    }
                }
                return false;
            });

        return filters;
    };
```

**Comment by gordonwoodhull** [comment]
one idea in #988, devolving the chart registry, is to sort of "render" the filter into a query rather than always generating a filter function as we're doing now.
