### ISSUE TITLE
Different shapes and legend in bubble/scatter chart

### ISSUE THREAD

**Issue by nawaab** [dc-js/dc.js#485]
It will be great if we can have something like the following in nvd3
http://nvd3.org/ghpages/scatter.html

Or if there can be a few step guide saying in abstract what one really needs to do .. to take one of these and make them dc.js compatible. 

:)

Thanks a lot in advance.  NICK ROCKS !!! \m/

**Comment by rmiddlekauff** [comment]
does this legend work for the bubble chart as well?

I am having trouble getting a legend to show up for the bubble chart.

**Comment by gordonwoodhull** [comment]
Doesn't look like it. Each chart has to define `.legendables()` to work with a legend, and only some have that method.

One difficulty here is that legends tabs to work better for distinguishing categorical dimensions (shape, color) - they are harder to define right for size and quantitative colors.

Or, at least, it has to be implemented a different way.

It's not difficult, but it takes a little thought. And you could always monkey-patch the chart to provide that method if you want to give it a shot...
