### ISSUE TITLE
permalink or href to share the visualisation filter state

### ISSUE THREAD

**Issue by Edouard-Legoupil** [dc-js/dc.js#490]
As recommanded here(http://stackoverflow.com/questions/20853794/dc-js-permalink-or-href-to-share-the-visualisation-filter-state), i am submitting this feature request.

When users find a specific fact while they explore the data, it is not easy to reproduce the exact filters they used in order to share their findings with other users (and initiate a discussion). A solution could be to have permalinks for each filter state.

It would be great to have the capacity to freeze a certain filters state and pass it to a #href. Ideally such href would be then shared through a share button or through the regular facebook/twitter sharing function. The interface would be similar to the 'reset' button.

**Comment by gordonwoodhull** [comment]
Another way to do this, saving the filters of all the charts on the page by index,  shown in this question: http://stackoverflow.com/q/27675327/676195

Somewhat more brittle but a quick solution if the number and order of charts on the page will not change.

**Comment by mr23** [comment]
Regarding the Legoupil proposal, I'd prefer a solution that encodes only the changed parameters.
