### ISSUE TITLE
choropleth map size not changing, only svg

### ISSUE THREAD

**Issue by pkpp1233** [dc-js/dc.js#508]
I named my choropleth chart 'usChart'. When I create the chart the width and height attributes do nothing except change the svg element size.

usChart.width(200).height(200)

I'm only changing the size of the svg, not the actually map inside. what i end up seeing is Washington and Wyoming and the rest of the country is cut off. Any idea how to change the actual size of the map? In d3, if I change the width or height attributes the entire graph will fit into that size. Confused what's happening here..

(update) the graph seems to automatically want to size to the entire window width no matter what...

**Comment by yedurag** [comment]
Hi,

What solution did u find for this . Please reply
