### ISSUE TITLE
Change text and axis colors

### ISSUE THREAD

**Issue by otana** [dc-js/dc.js#513]
I have been tasked to put a graph on a site that has a dark theme.  The problem is that for the life of me I can't figure out how to change the color or the axis labels or the axes themselves.  Below is a fiddle that shows the issue.  

http://jsfiddle.net/alanquist/5UEQn/

I have attempted to change the color to #fff through css and through the color mixin.

I'm sure that there is a simple solution that I am overlooking.  Any assistance or direction would be most appreciated.

**Comment by gordonwoodhull** [comment]
@coffeetea-synchestra, you're commenting on an issue from 4 years ago, so you're not likely to get a response. It should just be CSS though; that's how all the styles are applied in the first place. Search for `axis` in [dc.scss](https://github.com/dc-js/dc.js/blob/develop/style/dc.scss).
