### ISSUE TITLE
support ordinal y scale for bubble/scatter plots

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#539]
While it has special cases for an ordinal X scale, currently coordinateGridMixin assumes that the Y scale is linear.  This doesn't always makes sense for bubble or scatter plots.

Here is a fiddle sort of halfway hacking around the problem in `prepareYAxis`:
http://jsfiddle.net/gordonwoodhull/xZFx4/10/

**Comment by the3ver** [comment]
At least for a scatter plot I was able to get a simple example running with both x and y scales ordinal:
http://jsfiddle.net/the3ver/Lf72gmmy/3/

Looks linke the `prepareYAxis` workaround is no longer necessary.

**Comment by gordonwoodhull** [comment]
I see.. probably because `d3.scaleBand` is its own thing now, instead of having to call`d3.scale.ordinal.rangeBands`

**Comment by gordonwoodhull** [comment]
This is fixed by using d3v4 in dc.js 3.0, except for the ticks undefined problem, which is fixed by #1448.
