### ISSUE TITLE
Improving boxplot performance

### ISSUE THREAD

**Issue by mrmin123** [dc-js/dc.js#543]
Hi,

I'm trying to use dc.js to generate dynamic boxplots, but was having some performance issues with larger datasets (~50k float entries). I narrowed the issue down to this line under the reduce().reduceRemove function (taken from example):

``` JavaScript
p.splice(p.indexOf(v.Speed), 1);
```

I was thinking that if the p returned was pre-sorted (I'd imagine that the boxplot function already sorts the array to calculate quartiles) so that a more efficient binary search tree can be used to find the index for the splice. Is this something that can be implemented?

Thanks

**Comment by mr23** [comment]
Changing from p.indexOf to d3.bisectLeft saved 25% (no pre-sorting). _.indexOf was only about 12%.

**Comment by gordonwoodhull** [comment]
A second action item here is to add an option saying that the data is pre-sorted. The d3 boxplot plugin is always sorting the data, which does not make sense in case of incremental changes.

**Comment by gordonwoodhull** [comment]
Moving the pre-sorting option to #543. Fixing the examples now.
