### ISSUE TITLE
changing number of bars

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#593]
A couple of things don't seem to work here:
1. elasticX doesn't seem to be recalculated correctly - although `prepareXAxis` attempts to reset the domain, `_data` is set up to use `d3.stack` (which seems a bit inefficient anyway), which calls `prepareValues`, which then... filters the data on the domain.
2. the bin width is not recalculated unless `rescale` is called

**Comment by MarkHerhold** [comment]
I believe I am experiencing the same issue @gordonwoodhull. The overlap is not as severe as in the original post but is still a problem. See the Feb/Mar bars.

Here is a jsfiddle example: http://jsfiddle.net/MarkHerhold/rxLn6yn4/
The demo uses `dc 2.0.0-beta.23`. If this is not the same issue let me know and I will open a new issue.

![screen shot 2015-12-17 at 11 04 40 pm](https://cloud.githubusercontent.com/assets/4934732/11889069/a44f9a3c-a512-11e5-99d0-b98100d357eb.png)
