### ISSUE TITLE
scatterplot/bubble chart symbols being clipped

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#603]
I can't find a workaround presently, except for removing the clip area.

https://groups.google.com/forum/#!topic/dc-js-user-group/yvaukx41okk

![image](https://cloud.githubusercontent.com/assets/1366709/3077847/52f48f5e-e447-11e3-86c2-2300dbc7fb56.png)

Possible solutions:
- align the clip rectangle clipPadding with the origin (most useful here)
- pad evenly on all sides (as documented).
- generalize clipPadding to be more CSS-like and allow padding on each side.

**Comment by lastlegion** [comment]
The points are not clipped by #717 but it doesn't let you brush/filter the edge points.

**Comment by gordonwoodhull** [comment]
@lastlegion, I take it you're talking about the case where the center of the point is right on the boundary. I guess we could either allow the brush to go to the clip boundary, or have the brush match a point when the point is right on the edge.

**Comment by lastlegion** [comment]
Yes when the point is right on the boundary. If the point is visible it should be brushable IMO.
