### ISSUE TITLE
Guidelines on choropleth - mapping library integration (e.g., leaflet)

### ISSUE THREAD

**Issue by dgorissen** [dc-js/dc.js#608]
First of all props for releasing this nice lib. I love the choropleth support and a natural extension is to render it as some kind of layer in a mapping lib like leaflet, cartodb, ..  

So I was looking for something like [this](http://bost.ocks.org/mike/leaflet/) but linked into dc and that I can extend to multiple layers, each binding to a different set of dimensions/groups.

Advice from Google seems to be to look at the [snack](http://jeroenooms.github.io/dashboard/snack) dashboard by @jeroenooms but I failed to find the unminified source with the relevant code.

@yurukov mentions he did something similar in #119 and @NickQiZhu in #14. Im sure it cant be that hard but would appreciate some pointers or example code.

**Comment by KatiRG** [comment]
@yurukov How come the colours of the pie chart in Le Choropleth in your example http://opendata.yurukov.net/demo/dcjs_leaflet/ do not match the colours on the map?

**Comment by yurukov** [comment]
@KatiRG do yoy mean in the last map? The colors in the map show where there're the most people, while the pie chart shows different age groups. Selecting one age group from the pie chart filters the results and updates the map where the darkest colors on the features will show where there're the most people from that age group. In any case, the color accessor method allows setting custom colors on each feature.

**Comment by KatiRG** [comment]
Thanks @yurukov. I thought the pie chart was supposed to be like a colourbar. Is there a way to add a colourbar to the choropleth? Also, can your code handle `.valueAccessor` like the other dc charts? I need to display mean values, so I have made custom reduce functions.

**Comment by yurukov** [comment]
@KatiRG yes, valueAccessor is available like any other chart. This implementation extends baseChart and colorChart, so it uses all of their customizations.

**Comment by KatiRG** [comment]
Thanks @yurukov. The `.valueAccessor` works fine, but the `.popup` option does not produce any popup window when hovering over a region on the map in my code and also in your example. And I would like a colorbar, so I followed these leaflet guidelines: http://leafletjs.com/examples/choropleth.html, but I am not able to get it to work. Do you have any suggestions? Thanks in advance.

**Comment by KatiRG** [comment]
It seems that if `.brushOn` is false, then clicking on a map region displays the popup, but then you lose the filter action (i.e. the dc charts won't be filtered according to the region clicked). Is there a way to have the popup appear on mouse-over instead of mouse click, so that `.brushOn` can be left as true?

**Comment by ozermm** [comment]
Thanks for sharing this great library. I am trying to add a map layer to the marker chart in order to define the border of the city but I couldn't do it. Can anyone tell me how to do it? Thanks.

**Comment by gordonwoodhull** [comment]
Hi @ozermm are you asking about [dc.leaflet.js](https://github.com/dc-js/dc.leaflet.js) or about this library, dc.js?

**Comment by gordonwoodhull** [comment]
BTW I'm going to close this issue because the answer is dc.leaflet.js or @ruhley's [fork, which also has a ton of features](https://github.com/Intellipharm/dc-addons).

**Comment by ozermm** [comment]
Thank you very much for you quick response gordonwoodhull! I am asking about dc.leaflet.js. When I use dc_leaflet.markerChart option to generate the map, I cannot add any other layers. Could you please help me on this. I tried to find a solution but couldn't do. Any help is greatly appreciated.

**Comment by Tim-Intellipharm** [comment]
@ozermm Your issue is with a dc leaflet chart which isn't currently part of the base dc.js library. I have duplicated your issue at https://github.com/Intellipharm/dc-addons/issues/14. Please direct any further questions about the leaflet charts to that repository instead.

**Comment by gordonwoodhull** [comment]
FWIW https://github.com/dc-js/dc.leaflet.js and those parts of @Tim-Intellipharm (@ruhley) dc-addons are pretty much the same so either place is a good place to talk about this.

I think since those boundaries aren't data driven you'll really just end up accessing the underlying leaflet map and it won't have much to do with the dc layer.

**Comment by ozermm** [comment]
Thank you Gordon! Tim replied me back and open the above ( Intellipharm/dc-addons#14) to discuss. I will continue to follow that issue. I am really impressed how you are responsive for any related questions. Thank you very much again!
