### ISSUE TITLE
Proposing a logo for dc.js

### ISSUE THREAD

**Issue by kadimisetty** [dc-js/dc.js#618]
A logo is not a necessary component but it definitely contributes to dc's perceived quality and adds some flair to it's identity. I looked around the issues etc. but couldn't find any logo yet. This is my recommendation. It is based on the ["unofficial" Javascript logo ](http://www.2ality.com/2011/10/logo-js.html) and reference's dc's attachment to D3.js as well.

The Javascript logo.
![js](https://cloud.githubusercontent.com/assets/535947/3282319/a3eeabec-f4e6-11e3-9b0f-8aa85434c56d.jpg)

The D3.js logo
![screen shot 2014-06-15 at 6 26 07 pm](https://cloud.githubusercontent.com/assets/535947/3282320/baca7d8c-f4e6-11e3-93ae-2125ef533a3d.png)

So here's the logo I'd like to propose - 
![dc charts - 152](https://cloud.githubusercontent.com/assets/535947/3282313/1d514748-f4e6-11e3-88aa-22aef8e7975f.png)

If this is acceptable, I'd like to adapt the logo in any relevant formats like SVG's and multiple dimensions to suitable contexts like favicons or for the Github README page etc.

Awaiting criticism/suggestions.
Thanks :)

**Comment by mr23** [comment]
Where did this end up?

**Comment by gordonwoodhull** [comment]
I plan to go with this one:

![image](https://cloud.githubusercontent.com/assets/1366709/5689132/b0bba1e6-982d-11e4-8e4c-917247c0fa10.png)

There has been no actual release but let's make it official when 2.0 goes beta soon.

**Comment by gordonwoodhull** [comment]
Added to the repo and the main page.  Also made it the favicon, since png icons seem to work with current browsers.  

Any suggestions about layouts or formats welcome.

Thanks @kadimisetty!!!  Nice work.
