### ISSUE TITLE
Candlestick/OHLC chart type

### ISSUE THREAD

**Issue by jcamins** [dc-js/dc.js#626]
It would be really nice to have a candlestick/OHLC chart type (preferably both, but either one would be a good start) for dc.js. Unless anyone else already has this implemented somewhere, I plan on working on it. My plan is to add an assetChart which can be drawn as either a candlestick or an OHLC chart.

**Comment by gordonwoodhull** [comment]
@jcamins told me in email that they dropped this. If anyone is interested in taking it up, perhaps his repo would be a good starting point.
