### ISSUE TITLE
Implement .elasticRadius for Bubble Overlay charts

### ISSUE THREAD

**Issue by hypsypops** [dc-js/dc.js#661]
Circles should resize as data is filtered in other charts using [.elasticRadius([boolean])](https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#elasticradiusboolean) as done in the standard bubble chart.

Seems like it would be simple, but I'm still a little noob-ish and haven't been able to successfully do it myself. :)

Thanks for a great library!

**Comment by gordonwoodhull** [comment]
Implemented in dc.js 2.1.2
