### ISSUE TITLE
Row chart label alignment

### ISSUE THREAD

**Issue by dgorissen** [dc-js/dc.js#669]
First of all stellar work on dc and the recent bug fixing spree.

Small rendering issue I noticed. For row charts the labels do not align nicely with the bars, particularly if the charts/bars get smaller (font does not seem to scale). Would also be nice if the labels grayed out like the bars when making a selection.

![row1](https://cloud.githubusercontent.com/assets/644951/3873722/91ce3a96-2136-11e4-90ae-042a06ac0f95.png)

![row2](https://cloud.githubusercontent.com/assets/644951/3873723/91d18dcc-2136-11e4-8d1b-c470dd329f63.png)

Code used:

```
    rowChart = (chart, dim, group) ->
      chart
        .width(null)
        .height(null)
        .margins({top: 10, left: 10, right: 10, bottom: 20})
        .group(group)
        .ordering((x) -> -x.value)
        .dimension(dim)
        .cap(10)
        .label((d) -> d.key)
        .title((d) -> d.key)
        .elasticX(true)
        .xAxis().ticks(4)
```

**Comment by OzgunBas94** [comment]
where can i find this example.. is there a jsfiddle link or something like that.

**Comment by gordonwoodhull** [comment]
@OzgunBas94, I'm not sure what example you're referring to. This is a fixed bug. Are your row chart labels misaligned?

**Comment by OzgunBas94** [comment]
![d57868e2-26f5-11e4-8158-ea8ac887a0fb](https://cloud.githubusercontent.com/assets/11558065/13981832/bc9ca86c-f0e6-11e5-903d-5cd40934d190.png)


I'm just looking for a example like that :)

**Comment by gordonwoodhull** [comment]
Ha, got it!  Did you check out the community contributed examples?

https://github.com/dc-js/dc.js/wiki#examples-contributed-by-community

**Comment by davisford** [comment]
@OzgunBas94 what are you looking for specifically?  That's a screenshot of the app I built for our startup co.  The source is not open, unfortunately, but it was all built with dc.js/d3.js/crossfilter.js + angular.  I can't just dump the code, b/c I don't have a self-contained example, but if you're looking for something specific, I can try to help.
