### ISSUE TITLE
Any reason for div.dc-chart { float: left; } in dc.css ?

### ISSUE THREAD

**Issue by drjimbob** [dc-js/dc.js#673]
Is there any reason for this?  This seems to be styling orthogonal to the library.  This causes issues when used with bootstrap (or similar responsive grid systems).

If you have a responsive design like the following fiddle (where the colored div's are placeholders for dc charts):

http://jsfiddle.net/e1fap4bs/1/

where resizing the "Result" frame dynamically changes it from 3 columns, to 2 columns, to 1 column, while keeping the `<h2>` above the associated chart.

However, if we used dc, then dc.css would add float: left;  to the all the chart divs.  Then when resizing (when not at the largest or very smallest window size), all the HTML elements associated around a chart would lose their relative location to the chart.  (This caused issues for me where the chart titles and footers were getting lost).  Try resizing the following frame:

http://jsfiddle.net/e1fap4bs/2/

**Comment by privateOmega** [comment]
@gordonwoodhull Is it possible to remove it? Because I just had the same experience as @drjimbob and finally found out the cause and did a quick google search which led me to this issue.

**Comment by gordonwoodhull** [comment]
It'll break everyone's layout who isn't overriding it, and we'll probably have to add the rule to every example. So it needs a version bump. (dc.js uses scaled-down semantic versioning, so that'd be 3.1.)
