### ISSUE TITLE
Composite charts should pass filters to children

### ISSUE THREAD

**Issue by jcamins** [dc-js/dc.js#706]
It seems to me that if you have a composite chart, changing filters on the parent chart should change the filters on the children. Can anyone think of a reason not to have composite charts call their children's filter functions?

**Comment by gordonwoodhull** [comment]
I think this was fixed a while ago but wasn't functioning correctly until #1408, released in 3.0.2

If I'm missing something, please let me know and I'll reopen.

**Comment by gordonwoodhull** [comment]
This is the programmatic version of #1408 and still needs to be implemented.

**Comment by gordonwoodhull** [comment]
Fixed by #1435 in 3.0.4
