### ISSUE TITLE
Wishlist: export data

### ISSUE THREAD

**Issue by awildeep** [dc-js/dc.js#708]
It would be very cool if we could use a DC object to export our filtered dataset.  I am thinking of an interface similar to the dataTable.  Essentially it would need an ID to bind an event to (such as click on a <button>Export</button>) a dimension, a group, and a custom defined set of columns just like dataTable.

On even trigger, the object would build an export string (I am thinking just CSV, but this might be customizable) from the data and then have a function to deliver the content to the user that could be customizable (in case someone wants to use this for a reason other than data export, such as verbose logging).  The default behavior of the date export method would be to set the header (eg: "data:text/csv;charset=utf-8,"), and then call window.open(encodeURI(headerPlusDataString)).

Some awesome options would be to have a way to configure the header row, disable the header row, set the field delimiter and set the quotation string.

What do you all think?  I am pretty sure that Chrome and FF support this out of the box right now.  I can't speak to IE support however.

**Comment by tttp** [comment]
FYI: there is an example of how to export
https://github.com/dc-js/dc.js/blob/master/web/examples/download-table.html

**Comment by gordonwoodhull** [comment]
Thanks @tttp that's a great point. Yeah, you don't really need DataTables (although it's pretty slick). You really just need FileSaver.js.
