### ISSUE TITLE
Consider changing boxPlot yAxisPadding default

### ISSUE THREAD

**Issue by mr23** [dc-js/dc.js#725]
The default of 12 forces doesn't work well for 'small values' (ex 1+-0.1). I think the original selection might have been made based upon the example offered, which used relatively large integer values. And I believe the purpose is to avoid clipping the text and outlier circles.

Should the default be changed to '1%' or similar ? It would accomplish the same goal but allow many/most/all uses to not have to override the default. Meaning, a default value should work for many, not a few, cases.

**Comment by gordonwoodhull** [comment]
Dupe of #1120, which has more details.
