### ISSUE TITLE
X axis tick labels overlap

### ISSUE THREAD

**Issue by yiyezhiqiu** [dc-js/dc.js#731]
I'm using dc.js now.
But now I found a visualize bug, when the width is smaller than 900, then the timestamp will cover.

You can find from the img bellow.
Is there any solution to fix?

![screen shot 2014-10-16 at 6 10 40 pm](https://cloud.githubusercontent.com/assets/1655359/4660933/93d4eca2-551d-11e4-823f-09a76b603933.png)

**Comment by chaoflow** [comment]
Increasing the bottom margin (meanwhile) helps as well.
