### ISSUE TITLE
implement tooltip

### ISSUE THREAD

**Issue by christianmalek** [dc-js/dc.js#780]
Hi,

I tried to use d3-tip, but at some points it's failing. I think it's because of some events raised by dc.js. For example the line chart show ".dot" elements when you mouseover an data point. If you use d3-tip the points will be shown for a very short time, disappear and then the d3-tips will be visible. An other misbehaviour I found is that tips won't hide and stay if you're use it with an pie chart and change the filter through clicking on an slice. I've already informed the author of d3-tip (https://github.com/Caged/d3-tip/issues/87), but would glad to see an dc implementation. In my opinion it's something that dc.js is missing.

**Comment by Tim-Intellipharm** [comment]
I have created something like this that uses d3-tip. Check it out at [dc-addons](https://github.com/intellipharm/dc-addons/)

**Comment by nitinsurana** [comment]
+1

**Comment by akuji1993** [comment]
@Tim-Intellipharm Can you give an explanation to how one can use tooltipMixin when my app is written in ES6? Can't seem to get it to work.

**Comment by Tim-Intellipharm** [comment]
@akuji1993 The standard dc.js library uses the svg `<title>` tag which behaves very similarly to the html `title` attribute. How and when it is displayed is controlled by the browser. Also you cannot use html or any styling inside of it. The dc-addons tooltipMixin removes that tag and replaces it with a `<div>` tag that you can use any html and styling with.

**Comment by akuji1993** [comment]
@Tim-Intellipharm Okay, I'll need to use either your library then, or d3-tip (which doesn't really want to cooperate for me right now). Thanks for the explanation.

**Comment by alokreddy** [comment]
I had similar issue with DC chart's tooltips. d3-tip worked for me.

`var bubbleChart = dc.bubbleChart('#bubble');`

`var tip = d3.tip().attr('class', 'd3-tip').html(function (p) { return p.key; });`

```
bubbleChart
    .width(..)
    .height(..)
    .blah..blah more code
```

add below code after `dc.renderAll();` or after the chart is rendered.

`bubbleChart.selectAll("circle.bubble").call(tip);
                d3.selectAll("circle.bubble").on('mouseover', tip.show)
                    .on('mouseout', tip.hide);`

The important point is to use `bubbleChart.selectAll` over `d3.selectAll`.

**Comment by gordonwoodhull** [comment]
Thanks @alokreddy. Yes I recommend d3-tip. (Have not tried the dc-addons one.)

This wiki page lists some of the needed selectors: 
https://github.com/dc-js/dc.js/wiki/Chart-selectors

It's best to install the tips in a `pretransition` or `renderlet` event handler, in case later redraws add elements to the chart. (Depends how your groups are set up.)

Definitely always namespace your event listeners, as mentioned above.

Since this extension works fairly painlessly, I think we can close this.
