### ISSUE TITLE
x axis not changing on date range change

### ISSUE THREAD

**Issue by gordonwoodhull** [dc-js/dc.js#791]
Perhaps related to #790, in this case it looks like the scale is not changed correctly.
http://stackoverflow.com/questions/25710058/dc-js-x-axis-not-changing-on-date-range-change

It could be due to the too-complicated domain comparison code which will not work for dates because it uses `!==` (when comparison is not needed at all).

**Comment by awojtas** [comment]
Also having similar issue. Have added an onClick handler to update xAxis when the crossfilter is changed but the x-axis labels don't update.

My onClick:
    $('#dcChartTime').on('click', function(){
        var minDate2 = timeDimension.bottom(1)[0].dtt;
        var maxDate2 = timeDimension.top(1)[0].dtt;
        console.log("Range from '" + minDate2.toString() + "' to '" + maxDate2.toString() + "'");
        dcChartTime.x(d3.time.scale().domain([minDate2,maxDate2]));
        dcChartTime.rescale();
        dcChartTime.redraw();
    });

This is after page load:
![2015-06-09 12_06_46-mozilla firefox](https://cloud.githubusercontent.com/assets/3030232/8047973/1ff719a8-0ea0-11e5-8ba3-731bfcd59d8f.jpg)

And then I click "2014" on another pie chart, so the data is filtered but the graph isn't scaled:
![2015-06-09 12_07_27-mozilla firefox](https://cloud.githubusercontent.com/assets/3030232/8047976/2e46b482-0ea0-11e5-8629-381a911c31d2.jpg)

And then I trigger the onClick event by clicking somewhere in the graph itself and the chart becomes scaled but the x-axis isn't updated:
![2015-06-09 12_08_14-mozilla firefox](https://cloud.githubusercontent.com/assets/3030232/8047988/4a72f850-0ea0-11e5-985a-50161dd5a51c.jpg)

**Comment by gordonwoodhull** [comment]
Thanks @awojtas, I misunderstood this bug the first time around, so your images helped a lot. 

It turns out that the axes did not respond to a rescale, only to a zoom event or a render. I have fixed this, and also made it unnecessary to call `.rescale()` when setting the x or y scales. (It is still necessary to call rescale when changing just the domain of the scale.)

**Comment by awojtas** [comment]
That was quick! Will keep an eye out for next release.
