### ISSUE TITLE
grunt doesn't copy dc.js to web/js/dc.js

### ISSUE THREAD

**Issue by tttp** [dc-js/dc.js#830]
So I modified a graph in src and grunt, all good and built sucessfully.

I wanted to see the result on the examples under web, but I didn't see my change. took me a while to see that the examples have their own web/js/dc.js

What's the point of having two dc.js? and shouldn't grunt automatically copy the css and dc.js to the web folder?

**Comment by gordonwoodhull** [comment]
It really should. If not you've got the wrong grunt target. Did you run grunt web?

**Comment by tttp** [comment]
Just realised that I ran grunt without param and that does run only build

Can I modify the default to
    grunt.registerTask('default', ['build','web']);

to idiotproof a bit more?

**Comment by gordonwoodhull** [comment]
Hrrrmmm... you are not imagining things.  The default used to build the docs, but people were complaining about `grunt test` creating doc artifacts (#799), so I changed it to only build the source.

Maybe there is no way to make everyone happy, or maybe `grunt test` should have less dependencies than default `grunt`.
