### ISSUE TITLE
chart.focus() is not working the same in 2.0 as 1.7

### ISSUE THREAD

**Issue by stevemandl** [dc-js/dc.js#851]
I am adding time series data to the crossfilter in real time, then calling chart.focus() with the new time window. The example below works great in 1.7. But 2.0 is causing the dimension to be filtered.
This may be related to #821 

Please see these examples:
1.7 example: http://jsfiddle.net/smandl/1v8L2vhh/
The same example using 2.0.0-beta.5 http://jsfiddle.net/smandl/f5o1w23b/

**Comment by gordonwoodhull** [comment]
Thanks for the report @stevemandl.  It looks like in your case it is the new `zoomOutRestrict` that causes the wrong domain for you:

https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#zoomoutrestricttruefalse

Setting it to false restores the correct behavior.  It was added in #402 and I guess you could say that zooming is prioritized over scrolling right now.

http://jsfiddle.net/gordonwoodhull/f5o1w23b/5/

In addition, I am not sure why the brush is always showing but you can probably turn that off:

http://jsfiddle.net/gordonwoodhull/f5o1w23b/6/
