### ISSUE TITLE
Irregular histograms

### ISSUE THREAD

**Issue by pelegm** [dc-js/dc.js#858]
I am using `dc 2.0.0-beta.5`.

I was wondering whether it is possible to easily modify a histogram to let it be irregular in one of two senses:

1. have non equal width bins (like [here](http://bl.ocks.org/mbostock/1624660)); generally, let the width of a bin be pre-determined as a function of the bin number, say.
2. have non linear custom x axis, so, for example, it will have the values 1, 3, 5, 19, 321, but equally spaced.

I am not sure whether this is a feature request or not, since maybe a minor d3 extension may do the trick.

**Comment by gordonwoodhull** [comment]
There's no support for 1) in dc.js but there is a pull request #599 you might try out. I am unsure if it is a good idea but am willing to consider it.

For 2) I think you can just use an ordinal scale, unless I am mistaken.

Either of these what you are looking for?

**Comment by pelegm** [comment]
Regarding 1, I'll have a look at the PR, thanks for the reference.

Regarding 2, ordinal scales are indeed a (partial) solution, but these do not support brushing, which is an important feature (see #348).

**Comment by gordonwoodhull** [comment]
Ordinal brushing would be great. It's just a matter of some careful refactoring. Are there other problems with using ordinal scales here?

**Comment by pelegm** [comment]
Not really. Since both directions are already taken care of, I guess I can close this issue.

**Comment by gordonwoodhull** [comment]
I am doubtful about variable width bars because wide bars look like they contain more observations than skinny bars, when they don't. But perhaps it is not the place of a charting library to decide what makes sense.

I'd be interested to hear your feedback on #599.
