### ISSUE TITLE
A migration guide from 1.7 to 2.0 ??

### ISSUE THREAD

**Issue by alan-unravel** [dc-js/dc.js#882]
Hey guys, I'm just wondering if it would possible to have a migration guide or a rough outline of breaking changes between 1.7 and 2.0 when it stableizes. Thanks

**Comment by gordonwoodhull** [comment]
Unfortunately we have only started a change log for the changes between the 2.0 and 2.1 branch, and many of the big changes that happened between 1.7 and 2.0 could only be discovered by reading the commit log since we lost the maintainer who made most of them.
