### ISSUE TITLE
Series Chart Example...cont

### ISSUE THREAD

**Issue by DasNaughtie** [dc-js/dc.js#902]
Turns out that the version you have in the examples is 2.1.0 and the version you claim to be the latest stable release is 1.7.0.

Where do I get version 2.1.0...on your master branch I only see 2.0.

That is really bloody annoying!

**Comment by DasNaughtie** [comment]
Are you still maintaining this?  I want to use it in a project but this little experience has scared me some what so want to confirm before I use it.

**Comment by gordonwoodhull** [comment]
Sorry for any time lost on this! Yes I am maintaining this but it is a side project so updates are not as often as I would like.

Right, the site is running develop which is 2.1. The example should run on 2.0, which is in beta. It can be found e.g. here:

https://github.com/dc-js/dc.js/tree/2.0.0-beta.5

**Comment by gordonwoodhull** [comment]
Will try to clarify the versioning/branches somewhere more prominent. Thanks for the feedback.

**Comment by DasNaughtie** [comment]
Cheers!!

Thanks for the swift update...greatly appreciated
