### ISSUE TITLE
Restrict line chart zoom in upto hours in dc chart library

### ISSUE THREAD

**Issue by alpeshkumarpr** [dc-js/dc.js#905]
We are facing issue with the line chart of dc library.

http://dc-js.github.io/dc.js/

Take an example of above link where Monthly Index Abs is a line chart. When you zoom in, It goes upto minutes on X-Axis like 5.15, 5.30, 5.45 etc.

we would like to this zoom in functionality to restrict upto hours like 4 pm, 5 pm, 6 pm etc and not upto minutes.

Thanks in advance.

**Comment by gordonwoodhull** [comment]
GitHub issues are for bugs and feature requests, and this is already supported. 

I answered the question on SO: 
http://stackoverflow.com/questions/29465884/restrict-line-chart-zoom-in-upto-hours-in-dc-chart-library
