### ISSUE TITLE
change label text color in row chart

### ISSUE THREAD

**Issue by dataliven** [dc-js/dc.js#911]
I'm using css like this in html style section: 
text.row {
   fill: black;
}

but it does not work. Yet, if I use d3.selectAll('text.row').style('fill','black'), it works but will changed to white when clear all filters.

please help!

**Comment by mtraynham** [comment]
Row is a parent selector of text.  I have this and it works for me :)

.dc-chart g.row text {
    fill: black;
}

**Comment by gordonwoodhull** [comment]
I had the same thought but I see I forgot to respond. @dataliven, I'm going to close this, but please comment if @mtraynham's solution doesn't work for you.

**Comment by dataliven** [comment]
yes, it works.

**Comment by jaygovind** [comment]
.dc-chart g.row text {
    fill: black;
}


yee budyy its working,,, in dc js
