### ISSUE TITLE
When using crossfilter.remove and crossfilter.add the graph svg renders with ghosting?

### ISSUE THREAD

**Issue by alan-unravel** [dc-js/dc.js#912]
Not sure if this is a crossfilter issue or a dcjs issue. If crossfilter.remove() is called and a small dataset is added to the crossfilter following this then the render graph contains ghosted svg elements from the previous rendering. Has anyone experienced this? Using dc.js 1.7.3
![screenshot-localhost 2015-04-13 16-58-44](https://cloud.githubusercontent.com/assets/9106990/7119627/d3bea31c-e1fe-11e4-982f-c7a337129441.png)

**Comment by gordonwoodhull** [comment]
Definitely looks like a dc.js issue. I'm not sure if we have adequate test cases for adding/removing crossfilter data, although in principle it should already be handled through the regular code paths. 

Are you able to produce a jsfiddle demonstrating the bug? Can you test if the bug still exists for 2.0 beta 6?

**Comment by alan-unravel** [comment]
It does not seem like I can emulate the effect in the beta. I am not sure if this is due to the issue being fixed  in the beta or our use case being too specific. If I find a fix I will post here to give insight to others who may have the same problem. Thanks

**Comment by alan-unravel** [comment]
It seems like when the circle elements are generated by a larger dataset then when it is cleared the circle elements in the graph are not cleared and are just situated outside of the views and behind populated circles. This is very odd behaviour from my perspective. Does it sound familiar to you?

**Comment by alan-unravel** [comment]
http://jsfiddle.net/9kL9kk52/

**Comment by alan-unravel** [comment]
As this does not occur in the current master I understand that you have no obligation to help me, any insight you could offer for a work around would be very much appreciated though

**Comment by gordonwoodhull** [comment]
Thanks for the fiddle. I will verify if it is something we fixed, and if so I'll try to point you to the changeset that fixes it. There are a *lot* of fixes between 1.7 and 2.0.

It is safe to use the beta, as there will be no more breaking changes to the API. There may be occasional mistakes, however, so just be prepared to back out to earlier betas.

**Comment by alan-unravel** [comment]
Thanks, Now to dig into migrating to the beta!

**Comment by alan-unravel** [comment]
I have partially updated to the 2.0.0-beta.7, this problem no longed seem to occur so I will close this issue. Thanks again
