### ISSUE TITLE
Use the stable version for the demo page

### ISSUE THREAD

**Issue by monfera** [dc-js/dc.js#918]
Version 2.1 is still not yet solid; observe the weird transitions here: http://dc-js.github.io/dc.js/

I suggest a reversion to v1.7 on that page until 2.x is mature enough, because those rendering artifacts dissuade potential users.

**Comment by gordonwoodhull** [comment]
Well... there never was any stable version where everything worked perfectly. So while backing out to 1.7.3 would fix the line chart transition bug #507, it would introduce other annoying bugs.

Thanks @monfera for the suggestion.

**Comment by monfera** [comment]
Thanks, I understand now. My foggy memory was that 1.6 was faster and free of issues as disturbing as #507 (which manifests by simple operations on the time line itself), the difference being whether a casual evaluator would be able to recommend or use it on an upcoming project or pass on the opportunity.
