### ISSUE TITLE
Series Chart X-axis  does not recalculate on crossfilter data change

### ISSUE THREAD

**Issue by alan-unravel** [dc-js/dc.js#926]
When the crossfilter data is changed to data no longer matching the x domain then the graph appears to have no data. Here is a fiddle of the issue : http://jsfiddle.net/zvfqmzaz/

**Comment by donalt** [comment]
+1

**Comment by gordonwoodhull** [comment]
Ugh. I don't think either domain is always getting propagated right for series/composite charts. 

See #662 and #667.

**Comment by alan-unravel** [comment]
Are you aware of any workarounds I could use in the mean time?

**Comment by alan-unravel** [comment]
After having a bit of a look around it seems as though the sub line chart groups are instanciated with  a mock group using dc.functor. This causes the data on the sub-charts to be wiped and never replaced when they crossfilter is changed. See  [here](https://github.com/dc-js/dc.js/blob/develop/src/series-chart.js#L69)

**Comment by gordonwoodhull** [comment]
Looks like you found the culprit, although I don't see your comment anymore:

https://github.com/dc-js/dc.js/blob/develop/src/series-chart.js#L69

If our understanding is correct, this needs to be replaced with something that calculates from the current group rather than having frozen data. It could probably be replaced in each subchart. I will try to work something up later today if you don't figure it out first.

**Comment by alan-unravel** [comment]
Yes sorry I thought I was mistaken for a minute so took it down. I will try to figure it out. Thanks

**Comment by alan-unravel** [comment]
Actually it seems this is not the issue as when I changed the data and make a call to sub_chart.group().all() then I get the new data. I think there is a missing step where there new data should be propagated to the object that is returned from sub_chart.data()  as the values array in this object is empty on data change. I am however having a hard time finding where this is updated

**Comment by gordonwoodhull** [comment]
Okay, this is a lingering effect of #454, where the points were getting filtered by the current domain and making it impossible to calculate elasticX. 

We have a special case to not filter the points by the current domain, when elasticX is true. But elasticX was not passed down to the child charts, so they were still getting filtered on the current domain.

Passing elasticX down to the children fixes this.

**Comment by gordonwoodhull** [comment]
fixed in b836da497789ec401c34fcca1e645edb6a968192

**Comment by gordonwoodhull** [comment]
fiddle pointing at develop version now works: http://jsfiddle.net/gordonwoodhull/tzcLzrhp/7/

i also had to add `remove_empty_bins` because crossfilter does not automatically remove bins when they drop to zero.

**Comment by alan-unravel** [comment]
That is fantastic, thank you very much for all your help. Sorry I could not be more helpful!
