### ISSUE TITLE
A flaw in the way `keyAccessor` is used in the scatterplot?

### ISSUE THREAD

**Issue by danse** [dc-js/dc.js#931]
I am trying to wrap my head around accessors and filtering in the scatterplot. When i read the code, i was surprised to find [the key accessor used to extract the value for the y coordinate](https://github.com/dc-js/dc.js/blob/607f730fd84a4492f7b276c115f68f09af2dc6fa/src/scatter-plot.js#L45). Might this be the original sin leading to all the troubles? I would expect the value accessor to be used here, and the chart `x` and `y` accessors to grab either the first and second element in an array or the `.x` and `.y` properties in an object or whatever is defined by the user

**Comment by gordonwoodhull** [comment]
Yes. This is #621

**Comment by danse** [comment]
Thanks. Do i understand correctly that with this version of the code, if i override the key accessor to provide a value suitable for `translate` i will hamper indexing, while if i keep a key suitable for indexing i will break the scatterplot rendering?
