### ISSUE TITLE
Pie chart crash when 1. Filtered to no data; 2. filter back data

### ISSUE THREAD

**Issue by stevenxi** [dc-js/dc.js#933]
Problem is because the empty "empty" pie data added from pieChart.drawChart();

Temporary fix I did is in function tweenPie(b)

Change 
if (isOffCanvas(current))

To 

if (isOffCanvas(current) || (current.data && current.data.key && current.data.key === _emptyTitle))

**Comment by gordonwoodhull** [comment]
This sounds like it's probably the bug fixed in #1085 & #1151. @stevenxi, if you're still around, please comment if this is not fixed by 2.0 beta 33 and above.
