### ISSUE TITLE
default _filterHandler performs unnecessary filter clear ?

### ISSUE THREAD

**Issue by Sumbera** [dc-js/dc.js#960]
first call in default _filterHandler resets all filter. I don't think this is needed as all filters are anyway controlled by filterFunction.

       var _filterHandler = function (dimension, filters) {
        dimension.filter(null);  // --  is this really  needed ?

this is causing unnecessary cycles for adding all data back and then removing all of them based on added filter (or vice versa). My guess is it somehow breaks incremental nature of crossfilter. Commenting this out caused less calls to custom reduce functions (while keeping same correct filtering behavior). crossfilter used is 1.3.11

**Comment by gordonwoodhull** [comment]
Thanks @Sumbera. Have you tried running the test suite to be sure?

**Comment by Sumbera** [comment]
run grunt test : 38 specs in 33.066s. 0 failures

**Comment by Sumbera** [comment]
Great, this  performance problem has been fixed  in 2.0.0 beta 19 
  •Enable crossfilter optimizations by not resetting the filter

**Comment by gordonwoodhull** [comment]
Ah, thanks for pointing this out, should have pointed to this in the release notes.
