### ISSUE TITLE
Bar charts: Allow xUnits to depend on width/height / override on render

### ISSUE THREAD

**Issue by amergin** [dc-js/dc.js#970]
Use-case: composite chart that consists of multiple bar charts. The extent of values for these figures can differ significantly as they are drawn dynamically. That is also why I've had problems in determining the correct xUnits as in one case an integer precision is the correct, while in another it could be fractions of a thousand. 

To overcome this problem, I use a value `45` for `xUnits`. This works reasonably well if the figure width/height are adequate.

**The problem now:** Once the chart is initially drawn to some width/height, the xUnits is locked and cannot be overridden by setting it again and calling `render()`. 

The first figure is the initial draw (`xUnits=45`). The second figure is larger but still uses the same xUnits value: as you can see, the bars are too narrow. If I could reset `xUnits` to have it depend on the new width/height and then call render, the bar width could be more appropriate.

I really wish `dc.js` will address the [resize support](https://github.com/dc-js/dc.js/issues/544) in the coming versions. For the time being, are there any workarounds for my problem? One solution that comes to mind is to completely erase the figure and then create it from scratch, but that seems excessive.

![too_thin_resized_1](https://cloud.githubusercontent.com/assets/1969229/9086007/39c483a4-3b8a-11e5-8c26-42a4f9d1fefd.png)
![too_thin_resized_2](https://cloud.githubusercontent.com/assets/1969229/9086013/3ecec120-3b8a-11e5-8667-aa5417701458.png)

**Comment by gordonwoodhull** [comment]
I really hate `.xUnits` - it's very unintuitive and trips people up all the time. But I think you can get the bar widths corrected by calling `.rescale()`, right?

**Comment by amergin** [comment]
I think the problem is more that the chart cannot determine a sane default width for the bars (hence the xUnits). Here's what the chart looks like when there's no xUnits (bulky, too wide):

![image](https://cloud.githubusercontent.com/assets/1969229/9091918/aa6d53bc-3bab-11e5-9561-7e3d6f69e799.png)

With xUnits & rescale on width/height change, I see no difference. Changing the width/height without having to `render()` is another problem, that I asked [here](https://groups.google.com/forum/#!topic/dc-js-user-group/1Nbp0X2tk3g).

**Comment by gordonwoodhull** [comment]
Right, I wish there were a good way to determine bar widths without `.xUnits`... but let's leave perfect design aside for the moment.

I just double-checked, and calling `rescale` definitely causes `xUnits` to be reread and the bar width to be recalculated. You can set breakpoints in `calculateBarWidth` to verify this. The new example [web/resizing/resizing-bar.html](http://dc-js.github.io/dc.js/resizing/resizing-right-axis.html) verifies this.

I've solved the svg resize-on-redraw problem in 2.0 beta 15. Let me go ahead and push that now - please let me know if it helps.

**Comment by amergin** [comment]
Yep, now changing the width/height works as expected using `redraw()` and xUnits as well.

Btw, I noticed that for charts where height is small (in the picture 197px) the brush is drawn incorrectly:
![image](https://cloud.githubusercontent.com/assets/1969229/9094986/9836f754-3bbd-11e5-93a2-fc44e074b1e6.png)
I don't remember seeing this bug earlier.

**Comment by amergin** [comment]
Also, it seems that the "set width/height -> redraw()" technique does not work for heatmaps, x axis is not changed properly:

![image](https://cloud.githubusercontent.com/assets/1969229/9095112/3d268c2a-3bbe-11e5-9669-50a180237001.png)

**Comment by amergin** [comment]
The problem seems to be true for `rowChart` as well.

**Comment by gordonwoodhull** [comment]
That's right. I've only fixed the coordinate grid and pie charts so far. 

These comments belong on #544, thanks. I'll move them.

Is this issue fixed by using rescale+redraw or not?

**Comment by amergin** [comment]
Yep, this issue is fixed, closing.

**Comment by gordonwoodhull** [comment]
Great, thanks for the cogent and precise reports as always!
