### ISSUE TITLE
Feature request: Implement sparkline graphs

### ISSUE THREAD

**Issue by peterbrescia** [dc-js/dc.js#993]
In the [roadmap](https://github.com/dc-js/dc.js/wiki/Roadmap), last updated over a year ago, it says sparklines will be added as a graph type somewhere in version 2. Is this still a planned feature, and if so is there a specific version that this is likely to be included in?

Sparklines, especially if featuring a summary statistic like a percentage change, would be a very useful feature!

**Comment by gordonwoodhull** [comment]
Sorry, that was added by a previous maintainer who is no longer here, so I'm not entirely sure what was intended.

Aren't sparklines just small charts with spans without any axes?

**Comment by peterbrescia** [comment]
Apologies for not being clearer. Yes, sparklines are just small charts with no axes. The thing about summary statistics is tangential and unrelated to this.

**Comment by gordonwoodhull** [comment]
I think this functionality is available and we just need a decent example. It would take some troubleshooting, mostly. 

The summary statistic can be done with a renderlet or pretransition hook, too, say adding a highlighted point and some text.

**Comment by edmapd** [comment]
@gordonwoodhull here's an example from excel if helpful

[sparklines.xlsx](https://github.com/dc-js/dc.js/files/120079/sparklines.xlsx)
![sparkline excel](https://cloud.githubusercontent.com/assets/14082721/12863648/d5f5585a-cc2d-11e5-9710-fe08f3045844.jpg)

Also, thoughts from the originator of the idea:  http://www.edwardtufte.com/bboard/q-and-a-fetch-msg?msg_id=0001OR

**Comment by gordonwoodhull** [comment]
Thanks @edmapd, I'm a fan and have read the books. 

All that is required here is
 * to use a `span` instead of a `div` for the chart
 * use very small width and height
 * a little CSS to hide the axes

[Here's an example](http://dc-js.github.io/dc.js/examples/sparkline.html)

**Comment by edmapd** [comment]
Very nice!

The filtering is adorable   :)
