### ISSUE TITLE
Feature request: Change Selection Of Groups to Mimic File Browsers

### ISSUE THREAD

**Issue by JackStouffer** [dc-js/dc.js#996]
In dc.js, when you click on a bar chart bar, and you already have another bar selected, both bars become selected. This is counterintuitive when compared to how most software, like file browsers, work. In file browsers, clicking on a separate item will deselect the previous item and select the currently clicked item. To select both, you would control/command click on the item. You could even go so far as to add shift clicking to select multiple at once. Changing this would make dc.js easier to use when comparing, for example, line charts controlled by a categorical row chart, as it would one take one click instead of two to compare each of the different groups.

BTW, this is not just me theorizing about what would make more sense. Most of the people using my system that was built with dc.js have complained about this as it bucks their expectations.

**Comment by gordonwoodhull** [comment]
It would be good to have a way to define and specify the desired behavior, because there are actually a lot of different behaviors that different people expect.

The way to get what you want currently is this:

```{js}
chart.on('renderlet', function(chart) {
    chart.selectAll("rect.bar").on("click", function (d) {
        chart.filter(null)
            .filter(d.data.key)
            .redrawGroup();
    });
```

**Comment by gordonwoodhull** [comment]
One proposed PR is #601, supporting some of the features you mention.

Closing this as a duplicate of #716

**Comment by gordonwoodhull** [comment]
Updated code above - there is actually a moment you can "click on the old handler" if you use renderlet instead of pretransition. Also adding example here:

http://dc-js.github.io/dc.js/examples/bar-single-select.html
